skin/popup.css
skin/popup.html
src/background.js
src/popup.js

Added "why isn't anything blocked" question with answer and link to FAQ into pop-up. The question is hidden if:
* no third party domains were detected,
* some domain is blocked,
* some domain was manually configured.
FFPB issue: https://github.com/EFForg/privacybadgerfirefox/issues/179

Less frustrating pop-up for new users

---

doc/sample_cookieblocklist.txt
src/heuristicblocking.js

adds to cookie block list and removes cookie name entropy check. 
CC @jsha @swartzCr

multiple bugfixes

---

doc/sample_cookieblocklist.txt

more additions to cookie block list

---

doc/sample_cookieblocklist.txt

lots of things added to cookieblock list

---

doc/sample_cookieblocklist.txt

Cookieblock

---

doc/sample_cookieblocklist.txt

add fastly to list. fixes #334

---

lib/options.js
src/popup.js

temporary psychosis, removing useless code

---

lib/adblockplus.js
lib/options.js
manifest.json
src/background.js
src/heuristicblocking.js
src/popup.js
src/webrequest.js

please test this code, if it causes a performance hit it should be adjusted before merging
seen third party data is now being stored on disk instead of memory
Each third party origin gets its own filter and then in that filter ["subscriptions"][1] has an object that tracks the first parties it's been seen on
Added a check for first party domain in computeOriginsForTab.
added a bunch of comments about awful adblockplus code

Localstorage

---

_locales/en_US/messages.json
lib/adblockplus.js
src/popup.js

below a message that says that they're not setting or reading cookies

non tracking 3rd parties now appear in the popup

---

src/background.js

@gunesacar did you mean to make  a pull request of this? Should I merge this changeset?

Check if tab is closed during updatecount.

---

src/background.js

show badge. fixes #406

---

doc/sample_cookieblocklist.txt

cookie blocklist changes to fix hello mozilla

---

doc/DESIGN-AND-ROADMAP.md

@SwartzCr is this what we mean?

Attempt to clarify Noah's correction :)

---

_locales/en_US/messages.json
skin/popup.css
skin/popup.html
src/popup.js

added field reporting text about what it sends
added real endpoint

added error reporting button

---

manifest.json
src/background.js
src/heuristicblocking.js
src/supercookie.js
src/utils.js
src/webrequest.js
tests/selenium/super_cookie_test.py

localStorage based potential supercookie detection, see #362

Detect potential localStorage supercookies.

---

doc/sample_cookieblocklist.txt
skin/options.html
tests/selenium/options_test.py

rearrange options page and add things to cookie block list

---

doc/sample_domain_exception_list.json

Fixes #369  
Fixes #387
Fixes privacybadgerfirefox#360
cc @SwartzCr for review

fix url for youtube 1 click whitelising .

---

_locales/de/messages.json
_locales/en_US/messages.json
skin/firstRun.html
src/domainExceptionDialog.js

Hi
I added I18n support to Privacy Badger. I also added the German translation

I18n and German

---

_locales/en_US/messages.json
skin/popup.css
skin/popup.html
src/popup.js

In addition to restyling the popup, this adds a feature to notify the
user whether or not their report was submitted successfully.

Restyle error reporting popup

---

_locales/de/messages.json
_locales/en_US/messages.json
_locales/fr/messages.json
_locales/sv/messages.json
src/background.js
src/popup.js
src/utils.js
tests/selenium/localstorage_test.py
tests/tests/utils.js

Remove redundant code related to enabled/disable button and move closeOverlay out of init. This is to fix #451.

Remove redundant code related to enabled/disable button (#451).

---

src/popup.js

code was removed that generated and reverted user override control in #478

fixing some issues with gcommit 39d2413642a5d36c5157488c46c9fa05304caa41

---

skin/firstRun.css

Minor style tweaks for first run page, merging TBR
cc @SwartzCr for review.

style tweaks

---

skin/firstRun.js

People may like navigating the carousel with the arrow keys. Minor improvement for #230.

Add keyboard controls to jcarousel on the firstRun page.

---

_locales/de/messages.json
_locales/en_US/messages.json
_locales/nl/messages.json

Retry after build failed and fix by @gunesacar

locales: added Dutch translation

---

src/popup.js

fixed problem where someone could send a lot of junk error reports all at once polluting the DB

added closing of overlay and deactivation of submit buttons

---

lib/options.js

full height options page. Fixes #495

---

_locales/en_US/messages.json
lib/options.js
skin/options.html

ui tweaks on options page, fixes #488

---

doc/sample_cookieblocklist.txt

fix site-bugs for issue 485 and 455

---

doc/sample_cookieblocklist.txt

Which was breaking CSS on Microsoft Forums.

Yellowlist i1.social.s-msft.com

---

src/popup.js

Fix broken copyright header

---

_locales/en_US/messages.json
skin/popup.css
src/popup.js

added a tooltip explaining what privacy badger checks for in trackers

Non tracker subheading

---

src/webrequest.js

Fixes #473 by keeping a quota to rate limit `handlerBehaviorChanged` calls. Based on adblockpluschrome code: https://github.com/adblockplus/adblockpluschrome/blob/1bae543987593f4e5638d8797cb60a84d5b6da05/chrome/ext/background.js#L336

Add a quota to limit handlerBehaviorChanged calls (#473)

---

lib/adblockplus.js

Fixes #540 
fixes #337 
fixes #526 
fixes #536 
Merging TBR
CC @jsha or @SwartzCr for review.

check for base domain before stopping datastructure build. Fixes #540

---

_locales/sv/messages.json

Made changes to Swedish translation and added strings from en_US that were missing. This translation is based on those English text strings than the previous Swedish translations.

Update of Swedish locale

---

doc/sample_cookieblocklist.txt

adding twitch CDNs to cookieblock list

added domains to fix twitch as laid out in FF issue #499

---

src/clobbercookie.js

removed uneeded console logging

---

doc/sample_cookieblocklist.txt

adding larger extension for microsoft cdn

---

_locales/en_US/messages.json

change to potential trackers. cc @jgillula to review.

*potential* trackers

---

doc/sample_cookieblocklist.txt

For chrome issues: #565 and #59
Firefox issues: 578 & 585 (https://github.com/EFForg/privacybadgerfirefox/issues/578 & https://github.com/EFForg/privacybadgerfirefox/issues/585)

fixing a number of sitebugs

---

doc/sample_cookieblocklist.txt

site-bugs from chrome issues #513, #515, #503, & #602 fixed by adding to the cookieblocklist

fixing chrome issues #513, #515, #503, & #602

---

LICENSE

- Clarify current license status
- EFF is working to offer dual licenses to the Privacy Badger codebase; we
would like to ensure that all contributors agree to that change

Update License file

---

doc/sample_cookieblocklist.txt

@@||cloudfront.net^$third-party already on line 11
@@||5min.com^$third-party already on line 65
@@||cursecdn.com^$third-party 365
... etc

fix duplicates

---

doc/sample_cookieblocklist.txt

added alicdn to the cookie blocklist as per issue #617

---

doc/CONTRIBUTION-GUIDELINES.md

@cooperq please read this over and give feedback !

added contribution guidelines

---

_locales/en_US/messages.json

Edited the top level menu message.

#627 fixed

---

skin/popup.html

The occurances of stlye is replaced by style.

#651 fixed Corrected the type errors

---

_locales/es/messages.json

Created spanish translation locale file

spanish translation

---

src/background.js

The number now represents the total trackers blocked and not the potential trackers.

#628 Making Red number gameable

---

.gitignore
doc/sample_cookieblocklist.txt

fixes EFForg/privacybadgerfirefox#664
cc @jsha for review.

Firefox issue 644

---

_locales/en_US/messages.json

add slide text to localization strings (still need to actually implement, but now people can start translating.)

Firstrun l10n

---

skin/popup.css

Very small css fix but it's been bugging every time I open privacy badger :D

Have pointer cursor on switch and first run hover

---

manifest.json
src/clobberlocalstorage.js

If cookie blocking on a domain is enabled, also clear and block the L…ocal storage api
Also refactor cookieclobber to the new style
fix for #664

Block local storage setting if cookie blocking is enabled

---

lib/options.js

#683 Patch to properly form tooltip texts responsible due to options.js

Tooltip formed properly in options.js #683

---

doc/sample_cookieblocklist.txt

cc @jsha or @SwartzCr for review.

add all netflix cdn servers to the list

---

doc/sample_cookieblocklist.txt

cc @jsha or @SwartzCr for review.

fixes EFForg/privacybadgerfirefox#683

---

_locales/de/messages.json
_locales/en_US/messages.json
_locales/es/messages.json
_locales/fr/messages.json
lib/options.js
skin/options.html
skin/popup.css
src/background.js
src/utils.js
tests/selenium/localstorage_test.py

Fixes https://github.com/EFForg/privacybadgerchrome/issues/693

Add a new settings tab, and an option to disable the counter badge on the icon.

---

doc/sample_domain_exception_list.json

fixes #697 
merging TBR
cc @jsha or @SwartzCr for post review.

add soundcloud to domain exception list, fixes #697

---

src/utils.js

fixes issue brought up in #610

added wildcard subdomains to whitelist settings

---

.travis.yml
setup_travis.sh
src/popup.js
tests/selenium/cookie_test.py
tests/selenium/super_cookie_test.py
tests/selenium/website_testbed/first-party.html
tests/selenium/website_testbed/first-party.js
tests/selenium/website_testbed/third-party.html
tests/selenium/website_testbed/third-party.js
tests/selenium/window_utils.py

This PR is a first shot at a PB selenium test. If it looks like I'm headed in the right direction with this, I'll start adding to this suite.
It implements a basic cookie test, where three different websites are loaded, all of which pull in a tracking cookie from a fourth site. The fourth site has no DNT policy. Each time the popup UI is checked to make sure the third party site is greenlisted. When the first site is reloaded, the popup UI is checked to make sure that the third party's site has been yellowlisted.
I think the question here is, where will the testbed websites live? Just to get things rolling, I put them in my AWS s3 buckets. I'd like some feedback about where they should really live and admins I should be working with to get these in place. Getting this question sorted out …

Cookie test cases

---

lib/basedomain.js
src/webrequest.js
tests/tests/baseDomain.js

Updated to whitelist requests from private domains and clean up formatting of the affected function checkAction in webrequest.js. Let me know if you'd like to see any changes to this. If this looks good I can update the Firefox version to properly check for 127.0.0.0/8 addresses.

Whitelist private domains

---

doc/DESIGN-AND-ROADMAP.md
doc/dnt-policy/dnt-policy.txt

Updated the DNT policy with a copy from the EFF dnt-policy repo
Small changes in the DESIGN-AND-ROADMAP.md document.

Updates to documentation

---

doc/sample_cookieblocklist.txt

cc @jsha @Hainish @SwartzCr for review.

add fonts.net to cookieblock list. Fixes #729

---

_locales/en_US/messages.json
_locales/it/messages.json
lib/options.js
skin/options.html

This ports domain searching on the option page from the Firefox version. Issue #691 is related but this doesn't completely resolve it.

Add domain searching on options page

---

lib/options.js

This refactors options.js by removing some duplicated code and using a cached copy of origins (refreshing when necessary). Just let me know if this needs any changes.

Refactor options.js

---

doc/sample_cookieblocklist.txt

add calendar.google.com to cbl fixes #760

---

doc/sample_cookieblocklist.txt

see https://github.com/EFForg/privacybadgerchrome/issues/774

Add Fasterize CDN to cookie block list

---

lib/options.js
manifest.json
src/htmlutils.js
src/popup.js
tests/index.html
tests/tests/htmlutils.js

This is a start for consolidating some of the HTML utility functions in popup.js and options.js. For the most part I just cleaned the functions up without making major changes, and I added some tests.
I think there are about 12 other functions that I can investigate consolidating. I figured it was best to split the changes up instead of submitting one huge pull request.

Remove DRY code in popup.js and options.js

---

lib/options.js
src/background.js
src/heuristicblocking.js
src/webrequest.js

cc @SwartzCr for review. Can be tested by seeing that privacy badger still works and that the number of instances of "waiting for privacy badger" has decreased...

Blockingtest

---

doc/sample_cookieblocklist.txt

cc @jsha or @Hainish for review.

add several domains to cookieblock list

---

doc/sample_cookieblocklist.txt

adding cbsi to cookieblock list to fix cbs sites

---

doc/DESIGN-AND-ROADMAP.md

These changes contain some suggestions to make the design and roadmap documentation a bit more readable and fixes a typo.

Update design and roadmap documentation

---

tests/selenium/pbtest_org.py
tests/selenium/pbtest_org_test.py

Created a new class, pbtest_org_test.py, to run the pbtest.org acceptance tests, and report the passes, fails, and tests with 'undefined' results. It will assert out on any failed tests.

Selenium test to run the pbtest.org test suite

---

doc/sample_cookieblocklist.txt

add images.rapgenius.com to the cookieblock list

---

doc/sample_cookieblocklist.txt
doc/sample_cookieblocklist_legacy.txt

add giphy to cookie block lists

---

doc/sample_cookieblocklist.txt
doc/sample_cookieblocklist_legacy.txt

cc @SwartzCr or @jsha for review.

add a bunch of stuff to the cookie block list

---

TODO
manifest.json
skin/options.html
src/background.js
src/clobbercookie.js
src/clobberlocalstorage.js
src/constants.js
src/domainExceptions.js
src/fingerprinting.js
src/heuristicblocking.js
src/htmlutils.js
src/incognito.js
src/migrations.js
src/options.js
src/popup.js
src/storage.js
src/supercookie.js
src/utils.js
src/webrequest.js
tests/index.html
tests/run_selenium_tests.sh
tests/selenium/cookie_test.py
tests/selenium/localstorage_test.py
tests/selenium/options_test.py
tests/selenium/pbtest.py
tests/selenium/pbtest_org_test.py
tests/selenium/qunit_test.py
tests/tests/storage.js
tests/tests/utils.js

To get privacybadgerchrome to work with firefox, it needs to use the [`"incognito": "spanning"`](https://developer.chrome.com/extensions/manifest/incognito) manifest key.
To get spanning mode to work, privacy badger needs to manage the state of two sessions *in the same process*. One for the normal browsing mode, the other for incognito mode.
To do this, we need to encapsulate all the state of a privacy badger session. The current codebase takes for granted that there will only ever be one `pb` instance, so a lot of stuff is passed around globally.
So this pull request is a **major refactoring of privacy badger** which tries to encapsulate all this state, and add management for normal and incognito privacy badger sessions.

Fixing incognito mode

---

_locales/zh/messages.json

And I added up "show_counter_checkbox".
ps.The former translation like machine translation.. So I changed some expressions of Chinese.
And should zh rename as zh_CN(because language code of simplified Chinese is zh_CN. )?

Chinese translation

---

manifest.json

fix content verification

---

_locales/es/messages.json
_locales/sv/messages.json

remove duplicate keys in JSON

---

doc/sample_cookieblocklist.txt
doc/sample_cookieblocklist_legacy.txt

add c.o0bg.com to cookie block list. Fixes #903

---

_locales/en_US/messages.json
skin/popup.css
skin/popup.html

Tweaks in response to #919. I should note that my CSS is limited, so I don't know if the way I adjusted the font size for `<p>` and `<span>` is in any way best practice. Feel free to make adjustments and leave comments!

Rename 'Report Broken Site' button and adjust some font sizes

---

.travis.yml
src/background.js
src/domainExceptionDialog.js
src/webrequest.js
tests/run_selenium_tests.sh
tests/tests/baseDomain.js
tests/tests/storage.js

Fix eslint errors and run eslint in travis 

---

_locales/de/messages.json
_locales/es/messages.json
_locales/fr/messages.json
_locales/it/messages.json
_locales/nl/messages.json
_locales/ru/messages.json
_locales/sv/messages.json
_locales/zh/messages.json
src/htmlutils.js
tests/run_selenium_tests.sh
tests/tests/htmlutils.js

cc @rcutmore finishes the work in #946

add tooltip messages to other locales (untranslated) fixes #830

---

src/options.js

This pull request fixes the issue described in #1004 by using the existing htmlUtils.compareReversedDomains function

Sorts whitelisted domains #1004

---

src/heuristicblocking.js
src/options.js
src/storage.js
src/webrequest.js

@alexristich @cooperq Let me know what you guys think.

Followup to #982 (Adding ability to import and export tracker list)

---

src/options.js

remove deprecated API

---

doc/sample_cookieblocklist.txt
doc/sample_cookieblocklist_legacy.txt
src/multiDomainFirstParties.js

add several domains to cookie block list

---

data/surrogates.js

Work around a couple of redirect conflicts with uBlock

---

data/surrogates.js

Add more surrogate scripts

---

data/surrogates.js

Add Gigya surrogate

---

data/surrogates.js

Add analytics.js surrogate

---

_locales/zh_TW/messages.json

Hi
We are Taiwan's Mozilla community.
We add one more language to privacybadger, Traditional Chinese.
Which used in Taiwan and Hong Kong.
The full commit history: <https://github.com/moztw/privacybadger/commits/langs/zh-tw>

Add Tradational Chinese language strings

---

src/background.js
src/migrations.js
tests/selenium/popup_test.py

removes legacy migration from background script. places it in migration path. cc @ghostwords

move migration code to migration

---

doc/DESIGN-AND-ROADMAP.md
release-utils/post-release.sh

patch contains some spelling fixes ( just in comments ) as found by a bot ( https://github.com/ka7/misspell_fixer )

spelling fixes

---

doc/DESIGN-AND-ROADMAP.md

- Minor typo fixes for the `DESIGN-AND-ROADMAP.md` doc

[doc/design-and-roadmap.md] minor typo fixes

---

_locales/fr/messages.json

Hi,
I added many missing entries based on the en_US JSON file, translated them and improved the overall translations of the file.

Missing entries

---

_locales/de/messages.json

based on email feedback we received.

add the word poential before trackers in dutch translation

---

_locales/de/messages.json
_locales/nl/messages.json

accidentally added translation to german local instead of dutch local. This fixes that.

fix german translation and add dutch translation

---

README.md

Still not yet super straightforward, but at least now everything involved should be noted in one place.

Update automated test running docs in README.

---

src/_locales/uk/messages.json

Some corrections for better view.

Update Ukrainian translation

---

.travis.yml
scripts/setup_travis.sh
tests/firefox_selenium.sh
tests/run_selenium_tests.sh
tests/sel_requirements.txt
tests/selenium/options_test.py

Always install latest geckodriver

---

src/_locales/sv/messages.json

Hello. I cleaned up the Swedish translation + translated everything that wasn't translated already. It looks much better now IMO.

Update the Swedish translation + error fixes

---

src/_locales/sv/messages.json

@jony0008 @Dyras Could you take a look please? I pulled in the latest from Transifex (and auto-sorted the file by message key). We have a few untranslated strings at this point (the source file in Transifex was out of date) but that's OK.

Update Swedish translations

---

release-utils/make-signed-xpi.sh
src/manifest.json

To get around the following server error uploading the CRX in Chrome Web Store:
> An error occurred: Failed to process your item.
> Can not verify crx email of author.

Update author email again, this time only for Firefox

---

doc/sample_cookieblocklist.txt
doc/sample_cookieblocklist_legacy.txt

Fixes #1208
Fixes #1246
Fixes #1254
Fixes #1300
Fixes #1313
Fixes #1317
Fixes #1409

Add more Google domains to yellowlist

---

doc/fixing-broken-sites.md

[Link to doc in this branch](https://github.com/EFForg/privacybadger/blob/document-fixing-broken-sites/doc/fixing-broken-sites.md). Needs step-by-step examples, what else? @cowlicks Feel free to revise.

Document how to fix broken sites

---

tests/selenium/pbtest.py

Might help with issues like #1483.

Wait a growing number of secs when retrying tests

---

src/js/multiDomainFirstParties.js

Add abc7ny.com, 6abc.com, abc7.com to mdfp.

---

doc/sample_cookieblocklist.txt

Add dotsub.com to cookieblock list.

---

doc/sample_cookieblocklist.txt
doc/sample_cookieblocklist_legacy.txt

Add content.jwplatform.com to yellowlist

---

src/js/multiDomainFirstParties.js

Add Dow Jones & Company properties to MDFP

---

tests/selenium/pbtest.py

See issue with selenium here https://github.com/SeleniumHQ/selenium/issues/4444

remove broken set_script_timeout to fix tests

---

src/_locales/cs/messages.json

Hello, 
I updated Czech translation (#1193)  with new strings from en_US translation, fixed minor and major grammatical mistakes and rewrote some of the translations to make them more readable and coherent. I also translated word "tracker" in different way because the current translation is not technically accurate.

Updated and corrected Czech (cs_CZ) translation

---

doc/sample_cookieblocklist.txt
doc/sample_cookieblocklist_legacy.txt

Fixes #1238, fixes #1225.
Privacy Badger debugging info ([instructions](https://gist.github.com/anonymous/8aebb8e48a1ce3c256b21dcfe37af84b)):
```
**** ACTION_MAP for vidible
cdn.vidible.tv {
"dnt": false,
"nextUpdateTime": 1502124781559,
}
delivery.vidible.tv {
"dnt": false,
"nextUpdateTime": 1502203550920,
}
img.vidible.tv {
"dnt": false,
"nextUpdateTime": 1501870102330,
}
strips.vidible.tv {
"dnt": false,
"nextUpdateTime": 1502076855602,
}
trk.vidible.tv {
"dnt": false,
"nextUpdateTime": 1502132602591,
}
vidible.tv {
"dnt": false,
"nextUpdateTime": 0, …
```

Add vidible.tv to yellowlist

---

doc/sample_cookieblocklist.txt

Add wikipedia.org to yellowlist

---

doc/sample_cookieblocklist.txt
doc/sample_cookieblocklist_legacy.txt

Add unicornmedia.com to yellowlist

---

src/js/multiDomainFirstParties.js

Add nbcnews.com to MDFP

---

src/skin/popup.css

Fix misalignment  of key/legend icons

---

src/js/multiDomainFirstParties.js

Was looking through error reports for "zoho", found a bunch of reports of Zoho resources being blocked on Zoho domains.
Related to #1604.

Add Zoho domains to MDFP

---

doc/sample_cookieblocklist.txt

Added clients6.google.com to yellowlist

---

doc/sample_cookieblocklist.txt

Add taleo.net to yellowlist

---

src/data/yellowlist.txt

Add swiftype.com to yellowlist

---

src/js/tutorial.js

File seems to have been accidentally added in #766

Remove unused file.

---

src/_locales/da/messages.json

Danish translation.

---

src/_locales/da/messages.json

Danish translation: Better phrasing.

---

src/_locales/da/messages.json

Danish translation update

---

src/js/background.js
src/js/firefoxandroid.js
src/js/popup.js

Fixes #1671
Sometimes you should look first at yourself, before pointing to someone else.
Feature detection is now split between 2 variables, since it broke FF 57

Fix for Firefox Android 57

---

src/data/yellowlist.txt

Add Azure CDN to yellow list
Fixes #1643.

Add azureedge.net to yellowlist

---

src/skin/firstRun.js

Wait for images to load before calling jCarousel

---

src/_locales/da/messages.json

Danish translation update.

---

src/js/background.js
src/js/heuristicblocking.js
src/js/webrequest.js
src/tests/tests/background.js
tests/selenium/dnt_test.py

Removes an unnecessary argument from `checkForDNTPolicy`. Follows up on https://github.com/EFForg/privacybadger/pull/1642#issuecomment-327916666.

Refactor checkForDNTPolicy

---

.eslintrc.yml
package.json
src/data/surrogates.js
src/js/background.js
src/js/bootstrap.js
src/js/contentscripts/clobbercookie.js
src/js/contentscripts/clobberlocalstorage.js
src/js/contentscripts/socialwidgets.js
src/js/contentscripts/supercookie.js
src/js/firefoxandroid.js
src/js/firstparties/twitter.js
src/js/heuristicblocking.js
src/js/htmlutils.js
src/js/migrations.js
src/js/options.js
src/js/popup.js
src/js/socialwidgetloader.js
src/js/storage.js
src/js/utils.js
src/js/webrequest.js
src/skin/firstRun.js
src/tests/tests/baseDomain.js
src/tests/tests/firstparties.js
src/tests/tests/storage.js
src/tests/tests/utils.js
tests/selenium/website_testbed/first-party.js
tests/selenium/website_testbed/third-party.js

Also sets up spacing-related code style rules.

Upgrade ESLint

---

src/js/background.js
src/js/migrations.js
src/js/options.js
src/js/storage.js
src/manifest.json
src/tests/tests/yellowlist.js
tests/selenium/super_cookie_test.py

Add unlimited storage, fix unapplied yellowlist updates, increase storage syncing delay

---

doc/tests.md
scripts/setup_travis.sh

As suggested in https://github.com/mozilla/geckodriver/issues/1032#issuecomment-341337402.
Fixes #1511.

Use latest geckodriver except on Firefox ESR

---

src/js/multiDomainFirstParties.js

Lots of reports of missing CSS across Atlassian properties (because of blocked `ace-cdn.atlassian.com` resources), probably other related breakages.
Top error report counts by page domain and exact blocked resource subdomain for "atlassian" resources:
```
+--------------------------------------+----------------------------------------+-------+
| fqdn                                 | blocked_fqdn                           | count |
+--------------------------------------+----------------------------------------+-------+
| bitbucket.org                        | bitbucket-marketing-cdn.atlassian.com  |    74 |
| bitbucket.org                        | ace-cdn.atlassian.com                  |    53 |
| www.hipchat.com                      | hipchat-magnolia-cdn.atlassian.com     |    37 |
| …
```

Add Atlassian domains to MDFP list

---

src/_locales/bg/messages.json

I would also like to translate the eff.org/privacybadger webpage, but couldn't find how to?

Bulgarian translation

---

src/_locales/cs/messages.json
src/_locales/da/messages.json
src/_locales/de/messages.json
src/_locales/en_US/messages.json
src/_locales/es/messages.json
src/_locales/fr/messages.json
src/_locales/it/messages.json
src/_locales/nb_NO/messages.json
src/_locales/nl/messages.json
src/_locales/ru/messages.json
src/_locales/sr/messages.json
src/_locales/uk/messages.json
src/_locales/zh/messages.json
src/_locales/zh_TW/messages.json
src/js/options.js

Only accept URL and domain-like user inputs. 
If adding URL, automatically convert to domain. 
If not a valid URL, display alert message.
fixes #1684

Add validation to whitelist form

---

src/_locales/da/messages.json

Danish translation on 2017-11-14

---

src/_locales/nl/messages.json

Finished the translation of the messages that were in the master. I did not understand the comment of ghostwords to get something from Transifex; is there a newer version of the messages there?

Improved NL Translation of messages.JSON

---

src/js/background.js
src/js/webrequest.js
src/tests/tests/tabData.js

Fixes #1475, or at least a big part of it: not reporting any domains on whitelisted pages. Will still have the issue of reporting incomplete domain lists when Badger is used with other blockers.

Fix error reporting when disabled

---

src/_locales/es/messages.json

Changed translation from 'para' to 'detener'.

Revision for intro_hungry.

---

src/_locales/da/messages.json

Danish translation for master on 2017-12-14

---

src/js/background.js
src/js/storage.js
src/js/webrequest.js
src/tests/tests/storage.js

Fixes #1528. 
Just removes all instances of userAllow. 
Update: Added new tests to test user override of default action in domain.
This is my first contribution so please let me know if I've done anything incorrectly or if you like for me to make any changes.

Remove userAllow instances.

---

src/_locales/es/messages.json

Added updates to the Spanish translation.

Add updates to Spanish translation

---

src/js/multiDomainFirstParties.js

Fixes #704. Related to #1383.
[Debug info](https://gist.github.com/anonymous/8aebb8e48a1ce3c256b21dcfe37af84b) for `editmysite.com`:
```
**** ACTION_MAP for editmysite.com
ec.editmysite.com {
"dnt": false,
"nextUpdateTime": 0,
}
editmysite.com {
"dnt": false,
"nextUpdateTime": 0,
}
cdn2.editmysite.com {
"dnt": false,
}
**** SNITCH_MAP for editmysite.com
editmysite.com [
"dracobroadcast.com",
"martinlutherhs.com",
"qe4ferry.com",
"weebly.com"
]
```
Visiting the below URLs should teach Badger to block `editmysite.com` domains (due to a "snowplowanalytics" cookie), which will break https://www.weebly.com:
- …

Add two Weebly domains to MDFP list

---

src/_locales/es/messages.json
src/_locales/fr/messages.json

Updated translations French and Spanish

Update fr/es translations for the 'Tell us about this error' 

---

src/js/background.js
src/js/migrations.js

Fixes #1153, fixes #1236, fixes #1564, fixes #1601.

Forget more domains

---

src/_locales/tr/messages.json

Turkish translation for the project.

Adding complete Turkish translation

---

.eslintrc.yml
src/js/background.js
src/js/contentscripts/fingerprinting.js
src/js/popup.js
src/js/storage.js

See https://eslint.org/docs/rules/consistent-this. Need to code review / check tests / test a bit.

Enable consistent-this ESLint rule

---

src/_locales/bg/messages.json

Update Bulgarian translation with new messages.

Update Bulgarian translation

---

src/js/multiDomainFirstParties.js

Add firefoxusercontent.com to the mozilla group

---

src/skin/socialwidgets/GooglePlus.svg

Fixes the google plus icon to the new one.  Does nothing else.
Made to fix: https://github.com/EFForg/privacybadger/issues/1857

Add files via upload (Google Plus SVG)

---

doc/DESIGN-AND-ROADMAP.md

Propose fix a typo

---

src/data/yellowlist.txt

Add openload.co to yellowlist

---

src/_locales/cs/messages.json

Hello,
I translated new strings added to Privacy Badger and made some fixes to the already translated ones from #1590.

Updated Czech (cs_CZ) translation

---

src/data/surrogates.js

Add widgets.outbrain.com surrogate

---

src/data/yellowlist.txt

To unbreak Adobe Portfolio-powered sites for users logged into `myportfolio.com`.
Appears to be one of those cases where a website sets login/session cookies in the first-party context while also serving static resources in third-party contexts using domains that receive the previously set login cookies.
```
+------------------------------+-------------------------------------+-------+
| fqdn                         | blocked_fqdn                        | count |
+------------------------------+-------------------------------------+-------+
| adrenaline.de                | pro2-bar-s3-cdn-cf.myportfolio.com  |     1 |
| amstudio.rocks               | pro2-bar-s3-cdn-cf.myportfolio.com  |     1 |
| claudiahaon.com …
```

Add myportfolio.com to yellowlist

---

src/js/multiDomainFirstParties.js

Links to broken sites:
* https://t.me/durov/76
* https://telegram.me/durov/76

Telegram.org multidomain first parties

---

README.md
doc/tests.md

Clean up README to better focus on what matters

---

src/_locales/en_US/messages.json
src/skin/css/firstRun.css
src/skin/firstRun.html

The onboarding is missing the link to our Privacy Policy. Since this is what the user sees when clicking the question mark, it seems the right place to add a link to it.

Add link to Privacy Policy in onboarding

---

src/js/multiDomainFirstParties.js

Add S-Group domains to MDFP list

---

src/js/multiDomainFirstParties.js

Add OpenStreetMap domains to MDFP list

---

src/js/multiDomainFirstParties.js

Add neweggimages.com to newegg MDFP list

---

src/_locales/en_US/messages.json

Fixes #2045. Updated tab name, form description.

Improve wording around list of sites Badger is disabled on

---

src/data/yellowlist.txt

Add fontawesome.com to yellowlist

---

src/data/yellowlist.txt

- Recurly provides payment processing on behalf of merchants. Requests contain PII for the purpose of tokenizing payment information prior to committing a transaction on behalf of a merchant
- recurly/recurly-js#468

Adds Recurly to yellowlist

---

.github/ISSUE_TEMPLATE/broken-site-report.md

Add an issue template for broken site issues

---

src/data/yellowlist.txt

Fixes #1449.
- https://wikibuy.com/help
- https://www.xfinity.com/mobile/support/
- https://support.gog.com/hc/en-us/categories/201400969-Game-Technical-Issues
```
**** ACTION_MAP for zendesk
wikibuy.zendesk.com {
"dnt": false,
"nextUpdateTime": 1532923187909
}
zendesk.com {
"dnt": false,
}
comcast.zendesk.com {
"dnt": false,
"nextUpdateTime": 1532638835770
}
gogsupport.zendesk.com {
"dnt": false,
"nextUpdateTime": 1532630845170
}
assets.zendesk.com {
"dnt": false,
"nextUpdateTime": 1532999068158
}
**** SNITCH_MAP for zendesk
zendesk.com [ …
```

Add zendesk.com to yellowlist

---

src/data/yellowlist.txt

Add plot.ly to yellowlist

---

src/js/background.js

Follows up on https://github.com/EFForg/privacybadger/pull/1947#discussion_r210180595.

Load seed data the same way user data is imported

---

.gitignore
src/_locales/en_US/messages.json
src/js/background.js
src/js/options.js
src/js/storage.js
src/js/webrequest.js
src/skin/js/firstRun.js
src/skin/options-layout.css
src/skin/options.html

This is not remotely done, just opening this to facilitate discussion, per @ghostwords suggestion.
This PR is for issue #2110

Sync disabled sites using chrome.storage.sync

---

src/js/firstparties/facebook.js
src/js/firstparties/twitter.js
src/tests/tests/firstparties.js

Make first party scripts conditional

---

src/data/yellowlist.txt

Add prismic.io to yellowlist

---

src/js/background.js
src/js/webrequest.js
src/tests/tests/heuristic.js
src/tests/tests/tabData.js
tests/selenium/pbtest.py

Following up on https://github.com/EFForg/privacybadger/pull/2167#issuecomment-425260296

Remove parentFrameId bookkeeping

---

src/js/multiDomainFirstParties.js

Add Spotify domains to MDFP list

---

src/data/yellowlist.txt

Add bungie.net to yellowlist

---

src/js/multiDomainFirstParties.js

Add yandex.com to the Yandex MDFP

---

src/js/multiDomainFirstParties.js

Add Slashdot and SourceForge to MDFP list

---

src/js/multiDomainFirstParties.js

Add WebMD to MDFP list

---

src/js/heuristicblocking.js
src/js/webrequest.js

Restore access to all headers on Chrome 72+

---

src/_locales/cs/messages.json

Hey, 
I updated Czech translation with new strings and made some changes to old translation (typos and readability). Last changes were made also by me in #1964, so I am basically cleaning my mess.
Thanks.

Updating Czech (cs_CZ) translation

---

src/js/background.js
src/js/constants.js
src/js/htmlutils.js
src/js/popup.js
src/js/socialwidgetloader.js
src/js/webrequest.js
src/tests/tests/background.js

https://developer.chrome.com/extensions/extension#method-getURL

Replace deprecated getURL API

---

src/js/storage.js
src/tests/.eslintrc.yml
src/tests/lib/qunit_config.js
src/tests/tests/background.js
src/tests/tests/baseDomain.js
src/tests/tests/firstparties.js
src/tests/tests/heuristic.js
src/tests/tests/htmlutils.js
src/tests/tests/multiDomainFirstParties.js
src/tests/tests/options.js
src/tests/tests/storage.js
src/tests/tests/tabData.js
src/tests/tests/utils.js
src/tests/tests/yellowlist.js

Implement yellowlist removal

---

src/data/yellowlist.txt

Fixes #1128.
Error report counts by date, page domain and exact blocked "myshopify" subdomain:
```
+---------+------------------------------------------------------------+----------------------------------------+-------+
| ym      | blocked_fqdn                                               | fqdn                                   | count |
+---------+------------------------------------------------------------+----------------------------------------+-------+
| 2018-12 | a-perfect-circle.myshopify.com                             | store.aperfectcircle.com               |     1 |
| 2018-12 | eero-dev.myshopify.com                                     | eero.com                               |     1 |
| 2018-12 | meural.myshopify.com                                       | www.meural.com …
```

Add myshopify.com to yellowlist

---

src/js/multiDomainFirstParties.js

Add PriceRunner domains to MDFP list

---

src/data/yellowlist.txt

Attempting to fix https://github.com/EFForg/privacybadger/issues/1102

Add duosecurity.com to yellowlist

---

src/data/yellowlist.txt

Add Schibsted domains to yellowlist

---

src/data/yellowlist.txt

Update yellowlist.txt: please add et4.de

---

src/js/multiDomainFirstParties.js

Add two Vonage domains to MDFP list

---

src/data/yellowlist.txt

Fixes #2040.
```
**** ACTION_MAP for redcdn.pl
r-http-00.dcs.redcdn.pl {
"dnt": false,
"nextUpdateTime": 1550759179605
}
redcdn.pl {
"userAction": "user_cookieblock",
"dnt": false,
}
n-4-4.dcs.redcdn.pl {
"dnt": false,
"nextUpdateTime": 1550340948467
}
n-3-4.dcs.redcdn.pl {
"dnt": false,
"nextUpdateTime": 1550420190204
}
r-scale-df.dcs.redcdn.pl {
"dnt": false,
"nextUpdateTime": 1550572343841
}
r-scale-4d.dcs.redcdn.pl {
"dnt": false,
"nextUpdateTime": 1550708262876
}
r-scale-6f.dcs.redcdn.pl {
"dnt": false, …
```

Add redcdn.pl to yellowlist

---

src/js/multiDomainFirstParties.js

Add a couple of French government domains

---

src/data/yellowlist.txt

Add auth0.com to yellowlist

---

src/js/firstparties/facebook.js
src/manifest.json

Run facebook link unwrapping script on messenger.com

---

src/js/multiDomainFirstParties.js

Add wmflabs.org to Wikimedia MDFP list

---

src/js/multiDomainFirstParties.js

Fixes issues with balsmiq.com resources being blocked on balsamiq.cloud.

Add balsamiq.com and balsamiq.cloud to an MDFP list

---

src/data/yellowlist.txt

Add imagesrv.adition.com to yellowlist

---

src/js/multiDomainFirstParties.js

Error report counts by date, page domain and exact blocked "ctrip" subdomain:
```
+---------+---------------------------------+---------------------+-------+
| ym      | blocked_fqdn                    | fqdn                | count |
+---------+---------------------------------+---------------------+-------+
| 2019-05 | cdid.c-ctrip.com                | www.ctrip.com       |     1 |
| 2019-05 | cdid.c-ctrip.com                | www.trip.com        |     1 |
| 2019-05 | dimg02.c-ctrip.com              | www.trip.com        |     1 |
| 2019-05 | dimg04.c-ctrip.com              | www.ctrip.com       |     1 |
| 2019-05 | dimg04.c-ctrip.com              | www.trip.com        |     1 |
| 2019-05 | dimg05.c-ctrip.com              | www.ctrip.com       |     1 |
| 2019-05 | dimg06.c-ctrip.com …
```

Add Ctrip domains to MDFP list

---

src/data/yellowlist.txt

Add paddle.com to yellowlist

---

src/js/popup.js

Following up on #2001.
To help test, you could set the reporting URL in popup.js to something like `http://localhost:8080/` and run a local server that accepts and prints the contents of POST requests.
<details><summary>You could use the following Python server:</summary>
```python
#!/usr/bin/env python3
import json
from http.server import HTTPServer, BaseHTTPRequestHandler
from optparse import OptionParser
from pprint import pprint
class RequestHandler(BaseHTTPRequestHandler):
def do_GET(self):
request_path = self.path
print("\n----- Request Start ----->\n")
print("Request path:", request_path)
print("Request headers:", self.headers)
print("<----- Request End -----\n")
self.send_response(200)
self.send_header("Set-Cookie", "foo=bar")
self.end_headers()
def do_POST(self):
request_path = …
```

Fix not-yet-blocked, non-tracking and DNT domains in user error reports

---

src/data/yellowlist.txt

Please see error reports for user comments and example pages.
Error report counts by date, page domain and exact blocked "officeapps.live.com" subdomain:
```
+---------+------------------------------------+---------------------------------------------+-------+
| ym      | blocked_fqdn                       | fqdn                                        | count |
+---------+------------------------------------+---------------------------------------------+-------+
| 2019-06 | ffc-powerpoint.officeapps.live.com | microsoft.sharepoint-df.com                 |     1 |
| 2019-06 | pp2-rtc.officeapps.live.com        | microsoft.sharepoint-df.com                 |     1 |
| 2019-06 | word-edit.officeapps.live.com      | disk.yandex.com                             |     1 |
| 2019-05 | …
```

Add officeapps.live.com to yellowlist

---

src/js/multiDomainFirstParties.js

Update the MDFP list for French government mapping domains

---

src/js/webrequest.js

Fixes #1650.
Since we can't redirect requests from `onBeforeSendHeaders`, we can't provide proper support for blocking requests at this stage.
Redirection is required for script surrogation and iframe collapsing.
Should check what happens now for scripts/iframes on third strike (from headers), but if redirection doesn't work, perhaps nothing? In which case, the only difference is that before we would block non-script, non-iframe resources immediately upon the third strike from (cookie) headers, and now we will block the following time we see the newly blocked domain.

Don't block immediately upon third strike from headers

---

src/data/yellowlist.txt

Error report counts by page domain and exact blocked "tinypass" subdomain:
```
+-----------------------------------+-------------------------+-------+
| fqdn                              | blocked_fqdn            | count |
+-----------------------------------+-------------------------+-------+
| www.nbcsports.com                 | buy.tinypass.com        |    64 |
| www.nbcsports.com                 | experience.tinypass.com |    58 |
| thechive.com                      | experience.tinypass.com |    55 |
| www.washingtontimes.com           | experience.tinypass.com |    49 |
| www.theatlantic.com               | cdn.tinypass.com        |    48 |
| deadspin.com                      | cdn.tinypass.com        |    44 |
| www.businessinsider.com           | cdn.tinypass.com        |    37 | …
```

Add tinypass.com to yellowlist

---

src/js/multiDomainFirstParties.js

Update MDFP list for Enterprise Holdings

---

src/js/multiDomainFirstParties.js

> Suning.com Co., Ltd. formerly Suning Commerce Group Co., Ltd. is one of the largest non-government retailers in China, headquartered in Nanjing, Jiangsu Province.
--[Wikipedia](https://en.wikipedia.org/wiki/Suning.com)
It has three domains: `suning.com` as the main site serving mainland China, `hksuning.com` serving Hong Kong and `suning.cn` hosting static assets.
PB blocks `suning.cn` because `suning.com`, `hksuning.com` and other third-party shopping guide websites use resources hosting on it, resulting both `suning.com` and `hksuning.com` are broken.
Debugging logs:
```
**** ACTION_MAP for suning.cn
imgservice.suning.cn {
"dnt": false,
"nextUpdateTime": TIMESTAMP_REACTED
}
suning.cn {
"dnt": false,
"heuristicAction": …
```

Add Suning's domains to MDFP list

---

src/js/contentscripts/clobberlocalstorage.js
src/js/contentscripts/supercookie.js

Fix localStorage detection in Firefox

---

src/js/multiDomainFirstParties.js

> Bilibili is a video sharing website themed around animation, comic, and game based in China, where users can submit, view, and add commentary subtitles on videos. [Wikipedia](https://en.wikipedia.org/wiki/Bilibili)
Bilibili have several different domains using resources hosted on hdslb.com which is blocked by the Badger. AFAICS, only unblocking hdslb.com makes both bilibili.com and biligame.com work as expected. But to avoid future troubles, I suppose it may be more desirable to add all of known domains to the MDFP list.
The Sub Alt Name section of the TLS certificate of Bilibili.com does not give a full list of Bilibili's domains, so the domains in this commit are collected from its web pages and results of search engines. 
Debugging logs:
```
**** ACTION_MAP for hdslb.com …
```

Add Bilibili domains to MDFP list

---

src/js/utils.js
src/tests/tests/utils.js

Previously known as `rm-sep-chars-pixel-tracking` --- renamed the branch to be more clear about what it is doing: adds some unit tests to cover the different character classes in the pixel tracking heuristic. 
resolves #2436

Test char classes pixel tracking

---

src/js/background.js
src/tests/tests/tabData.js

This PR removes the tracker count when the count is zero, as discussed in #2470.

Hide tracker count when the count is zero

---

LICENSE
src/_locales/en_US/messages.json
src/js/background.js
src/js/options.js
src/js/webrequest.js
src/lib/i18n.js
src/lib/vendor/select2-4.0.11/select2-4.0.11.css
src/lib/vendor/select2-4.0.11/select2-4.0.11.js
src/skin/options-layout.css
src/skin/options.html

Fixes #2049 by adding the option to completely block some social
widgets instead of replacing them

Add UI for disabling widget replacement for particular widgets

---

src/js/options.js

Only count base domains in Tracking Domains tab

---

src/skin/popup.css

Fixes #2519.
Here is what the updated popup looks like at 360px:

Fix popup for 360dp Android displays

---

src/js/contentscripts/fingerprinting.js

Fix stack parsing in Chrome when Error is frozen

---

src/_locales/en_US/messages.json
src/skin/popup.css
src/skin/popup.html

Fixes #2562.
Relevant: https://github.com/EFForg/privacybadger/issues/2559#issuecomment-591583501, https://github.com/EFForg/privacybadger/issues/2556#issuecomment-591032111
Before:
After:
@ablanathtanalba Could you check on Firefox for Android / Firefox Preview Nightly for Android?
@brampitoyo Thoughts?

Improve usability of buttons in the popup

---

src/data/yellowlist.txt

Get Tests:
https://bbs.kafan.cn/thread-2102542-1-1.html

add some popular Chinese image sites to yellowlist

---

src/data/yellowlist.txt

Test:
https://weex.incubator.apache.org/
https://rax.js.org/
```
**** ACTION_MAP for alicdn.com
alicdn.com {
"dnt": false,
}
g.alicdn.com {
"dnt": false,
"nextUpdateTime": 1588746071969
}
img.alicdn.com {
"dnt": false,
"nextUpdateTime": 1588701751137
}
at.alicdn.com {
"dnt": false,
"nextUpdateTime": 1587658389357
}
aeu.alicdn.com {
"dnt": false,
"nextUpdateTime": 1588172819409
}
ae01.alicdn.com {
"dnt": false,
"nextUpdateTime": 1588795431326
}
alimama.alicdn.com {
"dnt": false, …
```

add alicdn.com to yellowlist

---

src/skin/popup.css

Trackers link matches theme of popup

---

src/skin/options-layout.css

Restyle options page tabs

---

src/js/background.js
src/js/migrations.js
src/js/options.js

Fixes #2632. Follows up on #1981.

Update WebRTC protection level

---

src/js/popup.js
src/js/webrequest.js
src/skin/popup.css
src/skin/popup.html
tests/selenium/popup_test.py

Improve intro reminder/critical error overlay

---

src/data/yellowlist.txt

Tests:
https://nomadlist.com/ (video to the right)
https://hytale.com/news/2020/4/progress-update-april-30-2020
https://blog.samrhea.com/post/home-movie/
```
**** ACTION_MAP for videodelivery.net
stats.videodelivery.net {
"dnt": false,
"nextUpdateTime": 1601010903364
}
embed.videodelivery.net {
"dnt": false,
}
videodelivery.net {
"dnt": false,
"nextUpdateTime": 1601213000180
}
**** SNITCH_MAP for videodelivery.net
videodelivery.net [
"padlet.com",
"nomadlist.com",
"samrhea.com"
]
```

Add videodelivery.net to yellowlist

---

src/js/background.js
src/js/migrations.js
src/js/options.js
src/js/webrequest.js

Standardize WebRTC IP protection override

---

src/js/background.js
src/js/webrequest.js

Fixes #2712, fixes https://github.com/EFForg/panopticlick/issues/52.

Block Panopticlick test domains on install/update/data reset

---

src/js/firstparties/facebook.js
src/js/firstparties/lib/utils.js

Fixes #2531, fixes #2605 (maybe, I can't reproduce the problem).
Follows the suggestion in https://github.com/EFForg/privacybadger/issues/2605#issuecomment-633139262.

Fixes for link cleaning on Facebook

---

src/js/firstparties/google-search.js

Fix settings link on Google search result pages

---

src/data/socialwidgets.json

Add replacement placeholder for Apple Music

---

src/js/background.js
src/js/popup.js
src/js/webrequest.js

To help get as many affected users as possible to see the deprecation notice.
Part of #2782.

Show error badge if any unseen deprecation notices

---

src/_locales/ja/messages.json

Added Japanese translation to this great extension :)

Add Japanese translation

---

src/js/tabdata.js
src/js/webrequest.js
tests/selenium/service_workers_test.py

Following up on #2859.
Related to #2198 and https://github.com/EFForg/privacybadger/compare/master...fix-sw-monitoring-chrome.
9afa163bb6403cceabeb6be75ccb43cc8dc527b9 is related to #2415.

Fix blocking SW-initiated requests in Chrome

---

src/js/heuristicblocking.js
src/js/webrequest.js
src/manifest.json

Replaces #2614. Previously: #2451, #2454.
Related to #2415.

Reject content script messages from special browser pages

---

src/tests/tests/storage.js

Fix typo in storage.js

---

src/js/background.js
src/js/heuristicblocking.js
src/js/webrequest.js

All chrome API listeners need to register on the first turn of the event loop in event pages/extension service workers.
Part of #2579.

Refactor chrome API listeners for event pages

---

src/js/options.js
src/js/popup.js
src/skin/popup.html

Fix opening popup and options when the event page is not running

---

.github/ISSUE_TEMPLATE/broken-site-report.md

Result can be practically seen in https://github.com/EFForg/privacybadger/issues/2912
I used JSONC (JSON with comments) as JSON itself would show ugly big errors for the `***` parts and look bad.
Cf.:
```json
**** ACTION_MAP for split.io
split.io {
"dnt": false,
}
sdk.split.io {
"dnt": false,
"heuristicAction": "cookieblock",
}
cdn.split.io {
"dnt": false,
"heuristicAction": "cookieblock",
}
events.split.io {
"dnt": false,
"nextUpdateTime": 1695640010874
}
auth.split.io {
"dnt": false,
"nextUpdateTime": 1695243547783
}
**** SNITCH_MAP for split.io
split.io [ …
```

Add syntax highlighting to broken page template

---

src/js/contentscripts/socialwidgets.js

Avoid replacing a widget that we think we already replaced

---

src/js/htmlutils.js
src/js/options.js
src/js/storage.js
src/skin/popup.css
src/tests/tests/htmlutils.js

Related to https://github.com/EFForg/privacybadger/issues/2929#issuecomment-1848426659.

Update sliders and count of blocked domains after toggling checking for EFF's DNT policy setting

---

release-utils/make-eff-zip.sh
src/js/background.js
src/js/bootstrap.js

Enable logging in development

---

src/skin/options.html

Change link to options page to fix #2956

Update Google Chrome help link in options.html

---

src/js/storage.js

To work around `chrome.storage.managed.get()` taking a wildly long time to return sometimes during browser startup.
Follows up on #2971 and https://github.com/EFForg/privacybadger/issues/2966#issuecomment-2153316523
The diff is best viewed with whitespace ignored.
To test, we are going to want to reuse a browser profile. Install the dev version of Privacy Badger in Chrome beta [^1], configure Chrome to "continue where you left off" in `chrome://settings/onStartup`, open some tabs, then restart Chrome beta and check the total time for "initialization complete" before and after this patch. Restart a few times to get a sense of timing.
We should also verify that [managed storage settings](https://github.com/EFForg/privacybadger/blob/master/doc/admin-deployment.md) still get applied.
[^1]: …

Don't wait for managed storage on startup

---

src/skin/js/firstRun.js

Following up on #2983.
This is a tweak to avoid briefly flashing the pin reminder in MV3 Chrome when the icon is already pinned.

Skip rendering pin reminder when already pinned in MV3 Chrome

---

src/data/socialwidgets.json
src/js/contentscripts/socialwidgets.js

Check out this branch and test widget replacement at the following links:
- https://amp.dev/documentation/examples/websites/components/amp-twitter/
- https://www.independent.co.uk/news/world/americas/us-politics/kamala-harris-jd-vance-childless-cat-lady-b2584852.html
- https://g1.globo.com/mundo/noticia/2024/07/13/tiros-no-comicio-de-trump-repercussao.ghtml

Fix AMP Twitter widget replacement

---

release-utils/make-eff-zip.sh
src/js/background.js
src/js/socialwidgetloader.js
src/js/storage.js
src/js/tabdata.js

Fixes #3036. Follows up on #2906.

Disable session storage reading on Firefox

---

doc/permissions.md
src/_locales/en_US/messages.json
src/skin/options.html

- Swap Privacy Sandbox links with links to the latest blog post
- Will update other locales after merging PR

Update Privacy Sandbox blog link

---

src/_locales/en_US/messages.json
src/js/constants.js
src/js/popup.js
src/skin/popup.css
src/skin/popup.html
tests/selenium/popup_test.py

- Add rotation system for link at the bottom of the popup
- For now, rotate weekly between Donate link and Review link (showing Review link 1/3 of the time)
- I realized that a random weighted selection might be better than a weekly rotation after implementing, and will change if you agree: https://docs.google.com/document/d/1OkyWnQ-bspFQuw7ebPXbGMMxb8_V4qR5SueBuGljPkA/edit?usp=sharing
- Will follow-up with modifications to the build process to set the `browser` constant

Add "Leave a review" link to the popup

---

src/_locales/en_US/messages.json
src/skin/options.html
tests/selenium/content_filtering_test.py
tests/selenium/cookie_test.py
tests/selenium/dnt_test.py
tests/selenium/fingerprinting_test.py
tests/selenium/navigation_test.py
tests/selenium/options_test.py
tests/selenium/pbtest.py
tests/selenium/popup_test.py
tests/selenium/supercookie_test.py

Clarify label for widget exceptions

---

src/_locales/en_US/messages.json
src/js/popup.js
src/skin/firstRun.html
src/skin/popup.html

- Describe what EFF is for Privacy Badger users who may not be familiar with us
- Approved by Development team

Add description of EFF to 'Donate to EFF' link in the popup

---

src/js/htmlutils.js
src/js/options.js
src/skin/options-layout.css

Hi!
This PR fixes #3108 . I'm making the pr to master since I can't see a develop branch.
Any feedback is absolutely welcome (this is my first pr to the project).

Fixed bug in Tracking Domains Tab #3108

---

src/js/popup.js
src/skin/popup.css

- Tested on Edge Android, Edge Desktop, Chrome Desktop, Firefox Desktop, and Firefox Android

Fixing missing overlays and YouTube message on Edge Android
