EFForg/privacybadger

- tests/selenium/cookie_test.py
Privacy Badger's Travis builds have been failing for a while due to Opera test suite (testsuites.opera.com) which went offline a while ago. This branch removes the tests that depend on Opera's testsuite and add one simple test to make sure the cookies can be properly set by JS. The build passes with this patch:
https://travis-ci.org/gunesacar/privacybadgerchrome/builds/47278699
It'd be nice to add more tests, of course.
> Remove cookie tests based on Opera test suite

- src/webrequest.js
Artificial scenario where we fail to get the originating script: https://jsfiddle.net/Lfrzyywq/2/.
> Ignore unattributed fingerprinting for now.

- src/socialwidgets.json
This commit should fix issue #402. The selector (`#___plusone_0`) removed in this commit caused PB to sometimes replace a Google Plus(+1) button with two replacement buttons.
At the heart of the issue is a strange race condition. Before [adding this selector](https://github.com/EFForg/privacybadgerchrome/pull/395/files#diff-a7e3669d2b1a8fab33514e1059d4cc30R77), sometimes (at least on my not-so-slow computer) +1 buttons had been rendered so quickly that PB couldn't replace them. This was because PB was looking for elements (`g:plusone` and `div.g-plusone`) that were already removed during the rendering of the +1 button.
This issue will again be visible after this commit (i.e. PB will sometimes miss +1 buttons) and I'll file a separate issue for that.
But (now I understand) it doesn't make …
> Remove Google+1 selector which causes double blocking (#402).

- lib/options.js
- setup_travis.sh
- tests/selenium/options_test.py
- tests/selenium/pbtest.py
Disable XVFB by default while running Selenium tests individually.
Switch to HTTPS URL for downloading ChromeDriver.
Upgrade ChromeDriver version to 2.12 for Selenium tests.
> Enable tooltips on PB Options page. Add selenium tests.

- tests/tests/baseDomain.js
Restore the invalid URI test lost in this commit: https://github.com/EFForg/privacybadgerchrome/commit/74e42bcff484e4f0183e9a57de016867285e106b#diff-3fa1e06eb491e6f17d04bc3bdf31ec3cL54
> Fix invalid URI test.

- tests/selenium/breakage_test.py
- tests/selenium/options_test.py
- tests/selenium/pbtest.py
We had this strange test failure ([build 66919699](https://travis-ci.org/EFForg/privacybadgerchrome/builds/66919699)) while loading the PB options page, which may be due to [mixing implicit and explicit WebDriver waits](http://www.seleniumhq.org/docs/04_webdriver_advanced.jsp#explicit-and-implicit-waits). This PR removes implicit waits and retries loading PB options page multiple times.
> Remove implicit Webdriver waits, retry loading PB options page in case of failure.

- lib/options.js
- tests/selenium/options_test.py
Fixes title of the PB Options page.
> Fix the wrong i18n key for PB's Options page title, add test.

- src/supercookie.js
To handle the exceptions thrown when the user has disabled third party cookies and site data:
See, https://github.com/EFForg/privacybadgerchrome/issues/365#issuecomment-113449886
> Handle the exception due to disabling 3rd P cookie and site data.

- src/background.js
- src/webrequest.js
To fix the setBadge function errors related to tabs used for prerendering (issue #410 )
> Don't call setBadge functions for prerendered tabs (issue #410).

- doc/sample_cookieblocklist.txt
sndcdn has a lot of subdomains.
I see the following:
**a-v2.sndcdn.com**
**wis.sndcdn.com**
**ec-media.sndcdn.com**
i1.sndcdn.com
i2.sndcdn.com
i3.sndcdn.com
i4.sndcdn.com
style.sndcdn.com
Music seems to play correctly with just the bolded ones yellow, but it seems safest to yellowlist everything?
> Yellowlist soundcloud's CDN

- tests/selenium/localstorage_test.py
This should fix the failing localStorage test after the policy key update.
https://travis-ci.org/EFForg/privacybadgerchrome/builds/72584114
https://github.com/EFForg/privacybadgerchrome/pull/490#issuecomment-124835185
Also, some PEP8 fixes.
> Update selenium test according to new policy key.

- tests/selenium/localstorage_test.py
Changes in the policy names causes some tests to fail, only check the policy hash length.
https://travis-ci.org/EFForg/privacybadgerchrome/builds/74160685
https://github.com/EFForg/privacybadgerchrome/pull/517#event-374608802
> Don't check policy key name.

- skin/popup.css
The German Translation for "The Domains below Don't seem to Track you" so
so long that the the words wrap out of the gray box
solution: set the box container height to "auto"
see Issue:  https://github.com/EFForg/privacybadgerchrome/issues/600
> [fixes: #600] "nonTrackers" Box is to small for German Translation 

- doc/sample_cookieblocklist.txt
yandex.ua, yandex.net are all synonyms of yandex.ru and used in their
services intechangably.
Fixes #646 .
> yellow-list Yandex synonyms.

- doc/sample_cookieblocklist.txt
adds bandcamp and diqus cdns to cookie block list.
> Issue 640 fixed

- _locales/de/messages.json
- _locales/en_US/messages.json
- _locales/fr/messages.json
- _locales/it/messages.json
- _locales/nl/messages.json
- _locales/sv/messages.json
- src/popup.js
PB dropdown is too short and narrow #594
Changes in UI, now entire domain-name is showed as a tooltip thus solving the first problem of "dropdown being too narrow so domain-names get needlessly truncated and it becomes impossible to determine what 1st-level domain it belongs to."
> Tooltip shows complete domain name, issue 594

- doc/sample_cookieblocklist.txt
This is the fix for issue #619. Added assets.nflxext.com domain into the yellow list.
> Issue #619

- doc/sample_cookieblocklist.txt
For some reason I was finding our new cdn for a css framework being entirely blocked.
> Add pistachio-cdn.graze.com to the yellow-list

- doc/sample_cookieblocklist.txt
> add assets-yammer.com to cookieblock list. Fixes #647

- doc/sample_cookieblocklist.txt
This is required for "Verified by Visa" and "Mastercard Securecode" in the UK.
This should fix https://github.com/EFForg/privacybadgerfirefox/issues/212.
> Add securesuite.co.uk to cookieblock list

- .travis.yml
- setup_travis.sh
Regression tests run locally, but fail on Travis CI due to flakey Chromedriver behavior. This PR updates Chromedriver from v.2.12 to v.2.20. Because that version of Chromedriver won't run with whatever version of Chromium lives in the testbed, setup_travis.py installs the latest stable version of Chrome too.
Also: apt-get could not always find python-virtualenv. I added an apt-get update before in .travis.yml, which appears to solve the issue.
> Update chrome, chromedriver for travis

- src/socialwidgets.js
- src/webrequest.js
It seems the social widget replacement code does not check if PB is enabled for the current page and if widget replacement is enabled in the PB options.
This should add a check before injecting the content script that replaces the widgets. Also checks the `response` object in the social widget callback which causes the relevant issue #726.
> Check if PB is activated and social widget replacement is enabled before replacing widgets.

- tests/selenium/breakage_test.py
- tests/selenium/cookie_test.py
- tests/selenium/localstorage_test.py
- tests/selenium/options_test.py
- tests/selenium/pbtest.py
- tests/selenium/qunit_test.py
- tests/selenium/super_cookie_test.py
Add some wait time on test pages with third-party frames to make sure they're loaded properly. Add a convenience method to load URLs.
Here's an example flaky test, failed after removing comments!
https://travis-ci.org/gunesacar/privacybadgerchrome/builds/110258308
> Reduce the test fragility by waiting some time to make sure the dynamic content is loaded.

- tests/selenium/pbtest.py
- tests/selenium/qunit_test.py
Selenium based QUnit tests timeout and fail the CI every now and then (e.g. [1](https://travis-ci.org/EFForg/privacybadgerchrome/builds/109954744), [2](https://travis-ci.org/gunesacar/privacybadgerchrome/builds/69709898), [3](https://travis-ci.org/EFForg/privacybadgerchrome/builds/109994005)).
Introduce a timeout value for the helper functions. Wait 120 seconds for the QUnit test suite to finish.
> Wait longer for the QUnit test results.

- doc/sample_cookieblocklist.txt
Add to cookieblocklist:
* tkx2-prod.anvato.net
* up.anv.bz
* mcp-media5.anvato.net
I'm not sure if these domains meet the yellowlist criteria as discussed in #756 if they don't feel free to close this PR.
Also I noticed that the entries in `doc/sample_cookieblocklist.txt` were mostly in alphabetical order, but also new entries were just appended to the list. So I just appended these.
> closes gh-756

- lib/options.js
This ports changes from the Firefox version to add a short delay before filtering tracking domains on the options page while user types.
[Pull request](https://github.com/EFForg/privacybadgerfirefox/pull/745) for the same changes to the Firefox version.
> Refactor domain search on options page

- doc/sample_cookieblocklist.txt
bcbits.com seems to be bandcamp's CDN and is getting blocked for me. I had manually overridden some of the domains it uses, but it uses random subdomains p1.bcbits.com, f1.bcbits.com, s1.bcbits.com which mean that occasionally a bandcamp site will still randomly break.
> add bandcamp cdn to cookie block list

- skin/popup.css
- skin/popup.html
This fixes some of the issues with #766. It looks like including *firstRun.js* in *popup.html* was causing issues with the tooltips and sliders. There are still other issues because the trackers link in the popup isn't fixed yet and the merge conflict in *popup.css* needs to be cleaned up.
> Fix issues with tutorial overlay changes

- doc/sample_cookieblocklist.txt
Fixing https://www.timeanddate.com/time/dst/history.html
> Yellowlist c.tadst.com

- doc/sample_cookieblocklist.txt
I found that the domain was being blocked by Privacy Badger on https://cdn.polyfill.io/v2/docs/ for example.
> Add build.origami.ft.com to the yellow-list

- lib/options.js
This fixes #799. Changes are saved as soon as they are made instead of waiting until the options page is closed. There are further improvements that can be made but I wanted to submit this now as I'll be busy the next couple weeks.
This also fixes an unrelated issue where a change is made to an origin, the list of origins are filtered, and then closing the options page doesn't save the change. This is because the changes to save are determined by checking the displayed list of origins.
> Fix crash when closing options page

- .travis.yml
- scripts/setup_travis.sh
- tests/run_selenium_tests.sh
Travis tests started to fail as Chrome doesn't support Ubuntu 12.04 anymore.
Use 14;04 machines for the Travis tests.
Install Chrome using Travis APT addon.
Read latest version of ChromeDriver from its release page.
We don't need to manually the bump the version again.
Remove redundant check about the machine architecture.
Travis machines are always 64 bit.
Do not install xvfb (already installed on Travis machines)
Run py.test with -v (verbose) switch.
> Use Ubuntu 14.04 for Travis tests

- skin/firstRun.js
- src/background.js
- src/options.js
This fixes item 5 in my comment in #819.
Some of the settings were being saved in the new storage engine as strings instead of booleans ("true"/"false" instead of true/false) which was messing up boolean checks in other areas of the extension. Whether or not the user has seen the comic was still being saved directly in the extension's local storage instead of the new storage engine so this fixes that as well.
> Save booleans instead of strings for settings in new storage engine

- src/options.js
This fixes item 6 mentioned in my comment in #819, namely the refresh of the options page causing an existing filter to be reset for the list of origins. Now an action like filtering the list of origins and setting a user override for an origin won't cause all origins to be displayed after the refresh.
> Fix options page refresh while origins filtered

- _locales/en_US/messages.json
- skin/popup.css
- src/htmlutils.js
- src/options.js
- src/popup.js
- tests/selenium/options_test.py
This fixes #589 by adding the capability of removing origins from Privacy Badger on the options page. It's set up to remove the selected origin from the *action_map*, *snitch_map*, and *supercookie_domains* storage objects. I think this should cover everything but let me know if I'm missing anything or if any of my assumptions are wrong.
> Add origin removal capability

- skin/popup.css
This fixes the positioning of the tracking icons for Firefox. On the options page scrolling through the list of trackers was causing the icons to scroll off-screen.
> Fix tracking icons (firefox-compat branch)

- src/options.js
This line was throwing an error because the *getSelected* method is unsupported in Firefox. Maybe this section of code should just be removed though? Maybe it serves some purpose but it looks like it just refreshes the tracker list again after the options page finishes loading which seems unnecessary.
> Use tab method supported by Firefox and Chrome

- src/options.js
Original discussion in #849.
This code does indeed cause an extra unnecessary refresh of the tracker list when opening the options page. What ends up happening is the tracker list refreshes twice in quick succession and the domains being displayed during both refreshes are exactly the same.
Removing this makes opening the options page a little snappier as well.
> Remove duplicate refresh while opening options (firefox-compat branch)

- skin/options.html
This string isn't defined in any of the localization files. Chrome doesn't render missing localized text while Firefox renders it as "???".
Only tangentially related, would it be worth consolidating the *Social Widget Settings* and *General Settings* tabs, similar to the current Firefox version? i.e. have the social widget setting listed as a checkbox under general settings.
> Remove missing localized string on options page (firefox-compat branch)

- src/background.js
- src/migrations.js
- src/storage.js
The commits explain them pretty well.
* Fix errors with `updateCount` for no tab requests. Internal xhrs were causing us to update pb's badge. But these don't have an associated tab, which was causing the error.
* Remove duplicate startup messages. The 'pb is ready to rock' message is kind of a lie now since the initialization funcs are asynchronous. But it is close enough.
* Fix error in migrations. This is bug was due to my refactoring. The `storage.getBadgerStorageObject` is a method on a badger instance now instead of a function. But that wasn't changed in this migrations code.
> Fix several errors.

- skin/popup.css
Turns out the scrollbar *is* showing by default (re #591); not sure what I was looking at before. However, it was getting cut off. I made a minor tweak to the CSS to set the properties for the `clickerContainer` class rather than the `blockedResources` id. `blockedResources` contains `clickerContainer` but also contains the blocked, cookieblocked and allowed icons at the top. Because of this, the scrollbar was starting from the top of the box, whereas it should have started from beneath those icons.
Here are before and after screenshots:
> Tidying up scrollbar in popup

- .travis.yml
- scripts/setup_travis.sh
- tests/run_selenium_tests.sh
- tests/selenium/breakage_test.py
- tests/selenium/cookie_test.py
- tests/selenium/localstorage_test.py
- tests/selenium/options_test.py
- tests/selenium/pbtest.py
- tests/selenium/pbtest_org_test.py
- tests/selenium/qunit_test.py
- tests/selenium/super_cookie_test.py
- tests/selenium/window_utils.py
- Fix: frequent chromedriver hangs during driver initialization (crbug.com/309093).
This prevents Travis errors where the test hangs with the following log:
`No output has been received in the last 10m0s,...The build has been terminated`.
- Wait until the alert is present after removing an origin.
Fixes infrequent selenium errors related to alert handling.
- Use travis_retry to retry failed CI tests.
- Refactor setup_travis.sh.
- Search for chromedriver in the PATH.
- Use gistcdn.githack.com instead of jsfiddle.
It loads faster and doesn't contain 3rd party clutter.
- Use pbtest.org instead of nytimes.com in the tooltip test.
- Don't start a (second) virtual display on Travis.
We already start an Xvfb instance in the .travis.yml
- Fix PEP8 warnings.
- Fix indentation and mixed tab-space …
> Improve Travis tests (#924).

- .travis.yml
- scripts/setup_travis.sh
- tests/run_selenium_tests.sh
- tests/selenium/localstorage_test.py
- tests/selenium/super_cookie_test.py
Allow failures for the beta version.
Enable fast finishing.
Run tests with Python 3.4.
Fix https://github.com/EFForg/privacybadgerchrome/issues/937 by updating the print statements in the tests.
Don't create a virtual environment for the tests. Travis already creates one.
We can't seem to use the right Python (3) version if we create the virtual env. ourselves.
Remove redundant printing of the downloaded PB policy.
> Run Travis tests for Chrome beta channel.

- src/options.js
This fixes an issue with the options page caused by a duplicate div.
**Before**:
**After**:
> Fix options page tracker list

- doc/sample_cookieblocklist.txt
- We have faced issues with privacy badger blocking razorpay, and users being unable to pay before: https://github.com/hasgeek/boxoffice/issues/39
Yellowlisting would allow our users to pay easily. (See <https://razorpay.com/demo/> for a demo.)
> Adds @razorpay to the yellowlist.

- src/webrequest.js
Until the following Chrome bugs are fixed and landed
PB can't know which tab or frame is the initiator of the ping
request. So PB will block all ping requests, even when it's
disabled on the site that sent the ping:
- https://crbug.com/522124 (landed in the Chrome unstable)
- https://crbug.com/522129
Once these bugs are landed, PB will treat the ping requests
as any other request and will block only when it's enabled for the
current tab.
This is tested with the Chrome unstable, where the fix
for bug-522124 is landed: since the tabId and frameId for the ping
requests are available, PB honors the disabled status and uses the
same blocking logic as the other requests.
Tested manually with Wireshark and debug logging from the extension.
Fixes #587
> Block ping requests sent by navigator.sendBeacon (issue #587).

- _locales/en_US/messages.json
- src/htmlutils.js
- src/options.js
- src/popup.js
- tests/selenium/options_test.py
- tests/tests/htmlutils.js
This addresses the missing localization mentioned issue #830. I also ended up doing a little refactoring with some of the related HTML code for the popup and options page. Of course there's a lot more refactoring to do but that would probably be best in a separate PR.
**Note**: issue #830 should probably be re-opened if this is merged. I wasn't thinking and my first commit closes the issue. This PR adds the ability to localize the tooltips but doesn't add the missing translations.
> Localize tracker tooltips

- src/socialwidgets.js
This is a fix for #920. When an array has length 0, its value is not `null`, so the check to exit early was not functional.
> Changing to check for length in cases where list is 'undefined'

- tests/selenium/pbtest.py
- tests/selenium/popup_test.py
This addresses #878 but it has some shortcomings. From what I can tell it's not possible to open the popup normally with Selenium because Selenium can only interact with a webpage and not the other browser elements.
This PR works around that by opening the popup page directly and testing some of its functionality. Unfortunately this means the most critical part of the popup, the tracker list, isn't being tested. Maybe there's a way around that?
Before this can be merged, either I need to rebase after [PR 959](https://github.com/EFForg/privacybadgerchrome/pull/959) is merged or I need to remove the check for opening the tracker link in a new window.
> Add tests for popup

- .travis.yml
As major ESLint updates will bring unexpected/backwards-compatibility breaking changes, we should standardize on a particular version of ESLint, specified in the [package.json](https://github.com/EFForg/privacybadgerchrome/blob/master/package.json) file.
> Have Travis install the ESLint version specified in package.json

- src/background.js
Feel free to ignore this PR or make the changes manually yourself.
This doesn't implement WebRTC protection for Firefox, but it prevents Firefox from throwing an error.
> return early if browser doesn't implement chrome.privacy

- src/background.js
@cooperq @ghostwords @pde Here's the updated implementation of WebRTC protection.
A few points of note:
1. Changing the setting to `default_public_interface_only` hides the local IP address.
2. Having this setting enabled doesn't in any way seem to effect the ability to use Google Hangouts, etc. (as per testing with Cooper)
3. In uBlock, the callback contains a call to check `chrome.runtime.lastError`, saying `lastError` needs to be checked or Chrome complains (see https://github.com/gorhill/uBlock/issues/875), but from my testing this doesn't seem to be an issue anymore.
4. There are 4 possible settings: `default`, `default_public_and_private_interface`, `default_public_interface_only` and `disable_non_proxied_udp`. I think that this last option might end up breaking some things, so the …
> Protect against WebRTC leaking private IP address

- _locales/de/messages.json
- _locales/en_US/messages.json
- _locales/es/messages.json
- _locales/fr/messages.json
- _locales/it/messages.json
- _locales/nl/messages.json
- _locales/ru/messages.json
- _locales/sv/messages.json
- _locales/zh/messages.json
- manifest.json
- skin/options.html
- skin/popup.css
- src/background.js
- src/heuristicblocking.js
- src/options.js
- src/storage.js
- src/webrequest.js
- tests/tests/storage.js
@cooperq @ghostwords 
This pull request implements the features requested in #121.
The current implementation only covers `action_map` and `snitch_map`, as `settings_map` currently only has two items, and it seemed a bit strange to me to be exporting `settings_map` data along with tracker data since "Settings" has its own tab on the Options page.
EXPORT:
Allows a user to download the data from `action_map` and `snitch_map` in JSON format, not as a binary object.
IMPORT:
Allows a user to import data from a file that is (a) in JSON format and (b) has the same structure as the file that Privacy Badger exports. Import acts as a semi-union: if a given domain *does not* exist in the current map, it will be added; if a given domain *does* exist, it will be overwritten with the object from the …
> Adding ability to import and export tracker list

- skin/options.html
Before now this was only known by reading the code of `src/background.js` or the single reference in the [Changelog](doc/Changelog) for the `v1.0.4` release. This will also require updating translations but I'm not sure what the process for that is?
> Note the support for wildcards in domain whitelists

- skin/options.html
This fixes the checkbox issue as the HTML was improperly named and disconnected from the javascript code. #1008
> Fixes issue #1008

- src/options.js
Now when you go to the options page, it loads 50 blocked resources, then dynamically loads more resources as needed. Kind of closes #1005 
I have  2751 blocked resources, this PR changes the options page load time from 6.92 seconds to 697 ms.
> Dynamically add blocked resources to the options page. 

- manifest.json
- src/options.js
This reverts the permission that was added in `81c8fbb3fcc5a48e726c91d175587b55beddac42` and adds a workaround from uBlock that allows downloading of a file without going through `chrome.downloads`.
> Removing download permission and adding workaround from uBlock

- src/options.js
@ghostwords 
As per #1063, Base64 doesn't support a wide enough character set to handle all possible URLs (e.g. URLs can now be in non-Latin alphabets). This changes the generated download URL to be in UTF-8 encoding and uses the relevant conversion function to support this set of characters.
> Changing export to use UTF-8 instead of Base64

- src/background.js
- src/options.js
This should fix crashes related to reading and writing WebRTC settings on browsers that do not support it. Fix also includes disabling Privacy Badger's WebRTC option on such browsers. See #1047 for discussion.
> Fix crashes on browsers with WebRTC disabled

- skin/popup.css
This makes the entire pop-up body width dynamic so it looks right in either pageAction pop-up context ...
or menu pop-up context ...
> fix #1120: calc width for entire pop-up body

- src/webrequest.js
This should fix #1078 and  #1101.
A concern for the code review: Do we have any places in the code where we want to do something for a main frame that could have a non-zero frame ID in Firefox? If there are, those places will break because of this patch. If there are none, great, no problem.
> Work around incorrect main frame ID in Firefox

- src/options.js
As per #1197, the sliders were broken quite a while back. I tracked this down finally to an issue with the extraction of the anonymous function in `$('.switch-toggle').each(...)` into an externally defined function. It isn't exactly clear to me what in this change actually affected the slider, so it's not at all surprising that this got overlooked. Maybe a closer look into this will yield some further information, though until then this simple reversion seems to fix the issue.
Here's an updated image to compare with that from the original issue:
> Reverting change from 4124c86 to fix issue with toggle switch (#1197)

- skin/popup.css
Undoing change to width of popup to fix issue in standard Chrome popup. The change fixed it for the popup in the Firefox menu, but resulted in the revert and 'x' icons being hidden by the slider in the default Chrome setup.
> Revert "fix #1120: calc width for entire pop-up body"

- doc/sample_cookieblocklist.txt
- doc/sample_cookieblocklist_legacy.txt
- src/multiDomainFirstParties.js
temp fix while archive.org figures out DNT. adding to cookie block list as well to fix on any other sites it may be embedded on. 
fixes #1219
> add openlibrary.org and archive.org to mdfp list. 

- tests/selenium/cookie_test.py
This fixes `tests/selenium/cookie_test.py::CookieTest.test_cookie_tracker_detection` and cleans up the test file. In theory should work on top of #1168, but should probably be re-tested with it when it is merged, or vice-versa.
The main issue seemed to be the test was not python3 compatible.
> Fix broken selenium cookie tracker tests.

- .editorconfig
[EditorConfig](http://editorconfig.org/) is a way to auto-configure compatible editors to use project-specific indentation settings. This config file declares Privacy Badger uses two spaces for `.js` files.
> Add EditorConfig settings file

- skin/popup.css
- src/background.js
- src/popup.js
The functions `activelyBLockedOriginCount`, `userConfiguredOriginCount`,
`hideNoInitialBlockingLink`, and `adjustNoInitialBlockingLink` are used to set
a `<p>` tag that was removed in d1d2494fad087e442912b606801ac2e2d3067167.
Since the element they are hiding and showing doesn't exist anymore, they
should be able to be removed.
> Remove leftover uses of noBlockingLink

- src/heuristicblocking.js
- tests/selenium/cookie_test.py
> Fix cookie tracker detection

- src/_locales/it/messages.json
I've changed some minor things in the italian translation trying to make it simpler/clearer and using expressions that are more common in the italian language.
1) "Centra" -> "Sposta l'interruttore al centro": clearer and consistent with the other two tooltip translations;
2) "pubblicità spione" -> "pubblicità che ti spiano": spione means leaker in italian and is usually referred to a person;
3) "non è determinante sul fatto che il dominio ti possa tracciare" -> "non determina con certezza che il dominio ti stia tracciando": clearer;
4) "è ritenuto sia un tracker sia necessario per il funzionamento ..." -> "è ritenuto un tracker ma è necessario per il funzionamento ...": simpler to understand;
5) "ritiene non sia un tracker" -> "ritiene che il dominio non sia un tracker": subject of the …
> Improvements to the italian translation

- src/_locales/cs/messages.json
- src/_locales/de/messages.json
- src/_locales/en_US/messages.json
- src/_locales/es/messages.json
- src/_locales/it/messages.json
- src/_locales/nb_NO/messages.json
- src/_locales/nl/messages.json
- src/_locales/ru/messages.json
- src/_locales/sr/messages.json
- src/_locales/sv/messages.json
- src/_locales/uk/messages.json
- src/_locales/zh/messages.json
- src/_locales/zh_TW/messages.json
Corrected the link from the "tracker" word in the popup UI to the Privacy Badger website. Should solve issue #1301.
> Fix tracker link in popup UI

- .travis.yml
- src/js/background.js
- src/js/constants.js
- src/js/heuristicblocking.js
- src/js/storage.js
- src/tests/index.html
- src/tests/tests/background.js
- src/tests/tests/heuristic.js
- src/tests/tests/storage.js
- tests/selenium/pbtest_org_test.py
- tests/selenium/qunit_test.py
Should fix #1303.
~~Hourly scheduled Do Not Track policy re-checking still happens, but only for domains that declared DNT compliance.~~ Checking ~~of all other third-party domains~~ is handled as you surf, via `heuristicBlockingAccounting`.
~~We need periodic DNT checking for DNT domains because DNT cascades from domains to their subdomains (when Badger decides what to block), but those second-level/higher-level domains aren't guaranteed to show up on the page in order to get re-checked.~~
~~DNT checks are now spaced at least three seconds apart (up from one second).~~
Still want to follow up on why a bunch of XHRs result in major CPU usage in Firefox (they're fine in Chrome), and why Firefox profiling tools don't seem to capture this CPU usage.
> Reduce impact of DNT rechecking

- .travis.yml
- tests/sel_requirements.txt
- tests/selenium/pbtest.py
Following up on https://github.com/EFForg/privacybadger/pull/1343.
We need to remove `marionette` from the list of Firefox capabilities to use latest Selenium bindings (3.4.0).
More info in https://github.com/SeleniumHQ/selenium/issues/3915.
> Remove Selenium bindings downgrade

- src/js/webrequest.js
- tests/selenium/cookie_test.py
- tests/selenium/options_test.py
- tests/selenium/pbtest.py
> Prevent DNT checking from setting cookies

- src/_locales/en_US/messages.json
- src/js/popup.js
- src/manifest.json
- src/skin/popup.css
- src/skin/popup.html
Fixes #1088.
I haven't really written any frontend code before, so I hope this isn't too bad.
> Adds a version number as per #1088

- src/js/heuristicblocking.js
- src/js/utils.js
- src/tests/tests/heuristic.js
- src/tests/tests/utils.js
> Refactor cookie parsing

- src/skin/options.html
Fixes #1273 
Added a meta tag to disable the translation suggestion from appearing in chrome on the settings page. Not sure if a regression test can be written for this bug since it does not look like tests would be able to determine if the translate popup appears. Additionally, it seems like the translate option is being enabled by a particular set of domains in the "User Filter Settings" tab, so in order to replicate the issue, I needed to manually add Portuguese text to the settings page. However the fix can be tested manually with the following steps:
1. In a version of privacybadger without this fix, add a Portuguese text to options.html in order to trigger the chrome translate option (I used the contents of [this page](http://www.laits.utexas.edu/orkelm/port/reading/pracpara.html)) …
> Disable google translate on settings page

- src/js/webrequest.js
- tests/selenium/cookie_test.py
- tests/selenium/pbtest.py
Fixes #1353.
Flask test server logic:
```python
from flask import Flask, request, Response
app = Flask(__name__)
COOKIE = 'foo=bar; Path=/;'
@app.route('/.well-known/dnt-policy.txt')
def route_dnt_policy_cookie_status():
response = Response(response="cookies={}".format(len(request.cookies)))
response.status = '200'
response.headers['Set-Cookie'] = COOKIE
return response
app.run('127.0.0.1', debug=True, port=443, ssl_context='adhoc')
```
> Strip DNT request cookies

- src/_locales/en_US/messages.json
- src/js/background.js
- src/js/options.js
- src/js/storage.js
- src/skin/options.html
- src/tests/tests/background.js
- src/tests/tests/storage.js
- tests/selenium/localstorage_test.py
Fixes #1389.
http://imgur.com/a/N8DqL
adds an option to disable DNT policy checks. When this option is disabled, domains fall back to heuristics and privacy badger stops asking the EFF for updated policy hashes.
I couldn't think of a better way to test these settings, and I couldn't find any of the other settings being tested, so I didn't have anything to emulate.
Let me know what needs changed here!
> added option to disable DNT policy checking

- src/js/background.js
- src/js/heuristicblocking.js
- src/js/options.js
- src/js/storage.js
- src/js/supercookie.js
- src/js/webrequest.js
- tests/selenium/cookie_test.py
- tests/selenium/super_cookie_test.py
Reloading a tab that contains localStorage tracking, such as from an embedded YouTube video, while the tab is still loading runs into a Badger bookkeeping bug which causes localStorage tracking to be attributed to all frame 0 resources (instead of the actual frame localStorage was in).
> Fix tracking misattribution bug

- src/js/background.js
- src/js/migrations.js
Following up on #1403.
I compiled the domain list from support emails and [broken site issues](https://github.com/EFForg/privacybadger/issues?q=is%3Aissue+is%3Aopen+label%3A%22broken+site%22). I looked for reports where we can't reproduce tracking by the domain but writing to localStorage by other resources on the same page as the domain is reproducible or at least seems likely. Domains that seem to be CDNs are particularly excellent candidates for forgetting.
If we are wrong about any of these domains, the good news is that Privacy Badgers will relearn to treat them as trackers soon enough.
> Add migration to forget mistakenly flagged domains

- release-utils/make-signed-xpi.sh
- src/manifest.json
Is somewhat visible with the eff.org-hosted Firefox version.
> Update author email address

- src/js/background.js
- src/js/migrations.js
- src/js/options.js
Firefox 54 (which just got promoted to stable) includes `chrome.privacy` but not `chrome.privacy.services`.
> Fix chrome.privacy.services exceptions in Firefox

- src/js/htmlutils.js
- src/js/popup.js
What this does:
* mainly the position of the sliders' when they have DNT. In `isChecked` we weren't accounting for DNT so the slider defaulted to the left.
* don't count origins with DNT in popup message "Privacy Badger detected X potential trackers"
* replace a hardcoded image path with `extension.getURL`
To test this visit https://troisiemebaobab.com/
With this PR you should see:
Before this PR you would see:
> Fix some UI issues with DNT in the popup

- .travis.yml
- scripts/setup_travis.sh
Geckodriver upgraded to v0.18.0, but this fails with ff esr. So we fallback to v0.17.0
> Fix failing firefox esr tests.

- src/js/background.js
- src/js/migrations.js
Fixes #1466, fixes #1469, fixes #1494, fixes #1495.
Follows up on #1482.
> Add migration to fix yellowlisted yet blocked domains

- doc/sample_cookieblocklist.txt
- doc/sample_cookieblocklist_legacy.txt
To unbreak weather-related images on the following websites:
* https://www.bluemts.com.au/weather-forecast/
* https://www.hawkesburyaustralia.com.au/weather-forecast/
* https://www.experiencesydneyaustralia.com/visitor-information/weather/
```
**** ACTION_MAP for weatherzone
www.weatherzone.com.au {
"dnt": false,
"nextUpdateTime": 1501904291446
}
weatherzone.com.au {
"dnt": false,
}
**** SNITCH_MAP for weatherzone
weatherzone.com.au [
"bluemts.com.au",
"hawkesburyaustralia.com.au",
"experiencesydneyaustralia.com"
]
```
The tracking that Privacy Badger sees comes from AWS "sticky sessions" load balancer cookies:
```
Name: AWSELB
Content: …
```
> Add weatherzone.com.au to yellowlist

- src/manifest.json
This should close #1483 
My theory is that there is a race condition. The supercookie detection content script is injected at "`document_start`" which means it might check for the localstorage data before the other script can write it.
> Don't check for supercookies until document_idle

- src/js/multiDomainFirstParties.js
Fixes #1293. Follows up on and closes #1570.
> Add mdfp entry for msnbc.com, newsvine.com

- src/js/background.js
- src/js/constants.js
- src/js/webrequest.js
- src/tests/tests/background.js
This PR includes two primary change sets:
1) tabData includes a new map structure that allows blocked third party origins to be tallied up.
2) Refactoring of when `updateCount()` function is called such that we only call it when the number on the badge increases. This should hopefully save some overhead, since we won't be querying any internal Chrome APIs to update the badge over and over with the same number.
I want to finish up with a test that verifies that blocked third party origins aren't double counted and the badge number reflects the actual number of blocked third party origins. The current code works, though a test will ensure this doesn't break in the future. Will get this done before the upcoming meeting on Monday.
> Refactoring how badge count is calculated and updated

- src/skin/firstRun.html
Resolves #1620.
From a ticket to change:
"I just installed Privacy Badger, a new tool from EFF to stop companies
from spying on your browsing habits - https://eff.org/privacybadger"
to
"I just installed Privacy Badger, a new tool from @EFF to stop companies
from spying on your browsing habits https://eff.org/privacybadger"
Therefor adding "@" and removing "-"
> Change twitter share message to correctly point to the EFF account

- src/js/background.js
- src/js/migrations.js
- src/js/webrequest.js
closes #1398 and closes #1397
The fix is 4819c06 I add a call to `checkForDNTPolicy` in places where we cancel requests.
Migration to unblock eff.org and its subdomains is fafbd5d.
Removed extra `nextUpdate` argument from `checkForDNTPolicy` in  ef51841 I update the tests and usage in the code to reflect this API change.
Moved the getter/setter functions from the tests into utils.js, and documented them. I use these in other currently pending pull requests, so I'd like to have them included here bb23c55
> Fix DNT checking for blocked domains

- release-utils/make-signed-xpi.sh
- src/js/contentscripts/fingerprinting.js
- tests/selenium/fingerprinting_test.py
Fixes #1158, fixes #1268.
This brings in [how we used to acquire stack traces in the legacy Firefox add-on](https://github.com/EFForg/privacybadgerfirefox-legacy/blob/00d88bbf42649d31bba181b49a7886c8381682ae/data/fingerprinting.js#L101).
[OpenWPM](https://github.com/citp/OpenWPM/blob/a6eb64afd48fe0e2b09be0b65d243f5d64a37a18/automation/Extension/firefox/data/content.js#L183), Brave (potentially), #1520, and #1524 contain ideas for future improvements.
> Fix fingerprinting detection on Firefox

- src/data/yellowlist.txt
Fixes #1244 
Fixes #1140
Also reordered some domains to alphabetical order
> Add websimages.com and webs.com to yellowlist

- src/data/yellowlist.txt
Following up on https://github.com/EFForg/privacybadger/pull/923#discussion_r135643624. Seems like we should just add all of `filepicker.io` to the yellowlist:
```
+-------+-----------------------+
| count | blocked_fqdn          |
+-------+-----------------------+
|   113 | www.filepicker.io     |
|    28 | api.filepicker.io     |
|    24 | dialog.filepicker.io  |
|     8 | assets.filepicker.io  |
|     4 | cdn.filepicker.io     |
|     2 | process.filepicker.io |
+-------+-----------------------+
```
> Add filepicker.io domains to yellowlist

- src/data/yellowlist.txt
Examples:
- http://matplotlib.org (click either Support button on the right-hand side)
- https://veinternational.org/get-involved/donate/ (embedded donation form)
- http://fcclainc.org/ (Support button on page bottom)
- http://www.opvrs.com/get-involved.html (embedded form)
> Add flipcause.com to yellowlist

- src/data/yellowlist.txt
Adds `vcas1.visa.com` (used for some Verified by Visa redirect thing in checkout flows) to the yellowlist.
(Not entirely sure if I was supposed to add this in sorted order or what so I did ¯\_(ツ)_/¯)
> Add vcas1.visa.com to the yellowlist

- src/_locales/en_US/messages.json
- src/js/options.js
- src/js/popup.js
- src/lib/i18n.js
- src/skin/firstRun.html
- src/skin/options.html
- src/skin/popup.html
Fixes #1688.
This adds support for attribute ("title", "placeholder") replacement. This also acts as a trial run for `chrome.i18n` placeholders (#1329).
> Localize a bunch of hardcoded messages

- src/js/multiDomainFirstParties.js
All belong to the same entity, [New York Public Radio](https://en.wikipedia.org/wiki/New_York_Public_Radio).
> Add New York Public Radio domains to MDFP list

- src/js/background.js
- src/js/socialwidgetloader.js
Fixes #1477 
Using the xhrRequest helper function in utils.js in order to make the asynchronous XHR request to load socialwidgets. If there is an error making the XHR request, then the error is shown in the console, but is not propagated through the callbacks (not sure if this should be changed). window.SocialWidgetList is also given an empty list as a default value.
> Load socialwidgets asynchronously

- src/js/options.js
- src/skin/options-layout.css
- src/skin/options.html
- tests/selenium/options_test.py
Follows up on #1669. This saves having to re-select the domain list tab every time you reload the options page.
> Preserve selected options tab on page reload

- src/data/yellowlist.txt
Session cookies (#1545) and localStorage from `wix.ecwid.com`.
Examples:
- https://www.csgoknives.co.uk/online-store/
- https://www.titan1918-russia.com
- https://www.titan1918.com
More examples can be found [here](https://publicwww.com/websites/"wix.ecwid.com"/).
An Ecwid representative's `action_map` also shows tracking from `app.ecwid.com` and `my.ecwid.com`, hence the base domain. Inquired in the same email thread about Ecwid adopting DNT.
> Add ecwid.com to yellowlist

- src/data/yellowlist.txt
I don't see tracking from `api-cdn.embed.ly`, but it gets blocked when its base domain gets marked for blocking.
Examples:
- https://www.reddit.com/live/zl0eib0kgh90
- https://www.hln.be/sport/time-out/nieuwe-kledingvoorschriften-voor-golfsters-daar-heeft-deze-blondine-een-wel-heel-erg-duidelijke-mening-over~a0de9ec4/
- https://www.businessoffashion.com/daily-digest/2017/08/08#marc-jacobs-on-hip-hop-and-charges-of-cultural-appropriation-maybe-ive-been-insensitive
Previously: 1480d03578ecd4c43b9bb2827c0f4bfcf086ba70, a174a14f81808ba4bf6cfd56845265b1bcd6d71c, 41095cdd27419f2017a6b0d93aacd1c18100b84e. Might have been easier to yellowlist all of `embed.ly` / `embedly.com` instead.
> Add api-cdn.embed.ly to yellowlist

- src/data/yellowlist.txt
Examples:
- http://miegakure.com
- https://www.reddit.com/r/blackmagicfuckery/comments/73u1uq/slinky_telekinesis_class_at_chinese_hogwarts/
- http://mgoblog.com
- http://marctenbosch.com/news/
Sets various cookies and localStorage.
Distinct blocked domains in error reports:
```
+-------+-------------------+
| count | blocked_fqdn      |
+-------+-------------------+
|    88 | gfycat.com        |
|    27 | zippy.gfycat.com  |
|    26 | thumbs.gfycat.com |
|    23 | fat.gfycat.com    |
|    17 | giant.gfycat.com  |
|    11 | assets.gfycat.com |
|     3 | pixel.gfycat.com  |
|     2 | test.gfycat.com   |
|     2 | upload.gfycat.com |
|     1 | www.gfycat.com    |
+-------+-------------------+
```
Previously: #532.
> Add gfycat.com to yellowlist

- src/data/yellowlist.txt
I see cookies from `ws.cnetcontent.com` (one low entropy month-long cookie and two high-entropy session cookies, #1545), and nothing from `cdn.cnetcontent.com`.
Examples:
- https://www.cdw.com/shop/products/Tripp-Lite-DVI-over-Cat5-Cat6-Video-Extender-Kit-1920x1080-TAA/2090126.aspx?pfm=srh&expand=URV#URV
- http://www.argos.co.uk/product/9269213
- http://www.bjs.com/mac-motion-oslo-collection-air-leather-recliner-with-ottoman---whisky.product.3000000000000944616
- http://www.compumail.dk/vare-oversigt.php?varenummer=992502035&type=hardware&RefId=pricerunner (broken images)
- https://www.pcworldbusiness.co.uk/catalogue/item/P231837P (broken images)
> Add cdn.cnetcontent.com to yellowlist

- src/data/yellowlist.txt
Fixes #1501. I see a "userId" cookie and localStorage use.
More examples:
- https://www.audifairfield.com/global-incentives-search/index.htm?&ddcref=nav_SpecialsFinance
- http://www.volkswagenpasadena.com
- https://www.andersondodge.net/new/Chrysler/2018-Chrysler-Pacifica-Rockford-dd3e8ae90a0e0a1748743f962438ab88.htm
- http://www.carlburger.com
Monthly counts of blocked `dealer.com` domains in error reports:
```
+---------+----------+
| ym      | count(*) |
+---------+----------+
| 2017-10 |        7 |
| 2017-09 |       23 |
| 2017-08 |       28 |
| 2017-07 |       32 |
| 2017-06 |       45 |
| 2017-05 |       49 |
| 2017-04 |       58 |
| 2017-03 |       40 |
| 2017-02 |       31 |
| 2017-01 |       27 |
| 2016-12 |       31 |
| 2016-11 |       10 |
| 2016-10 |       13 |
| 2016-09 | …
```
> Add dealer.com to yellowlist

- src/data/surrogates.js
To latest version from uBlock Origin.
See https://github.com/EFForg/privacybadger/issues/1735 for what the encoded string is and what it should be. To get the string, you can run `getSurrogateURI("https://www.google-analytics.com/analytics.js", "www.google-analytics.com")` on Badger's background page.
We might want to add an automated checker/alerter/updater (maybe part of our tests, maybe part of our release process) for surrogates we share with uBlock Origin at some point. I'm not sure it's worth doing yet since this is the first time we had an update in six months. If we keep running into conflicts and/or as we borrow more surrogates, a checker would get more and more useful.
> Update analytics.js surrogate

- src/js/contentscripts/clobberlocalstorage.js
The local storage clobbering can cause security errors when third-party cookies are being blocked. Previously, the error would leak out onto the console producing noise that makes debugging sites harder. This commit catches the error and ignores it.
> Stop errors from leaking to the console

- src/js/background.js
- src/js/popup.js
- src/js/webrequest.js
- src/skin/popup.css
- src/skin/popup.html
- tests/selenium/popup_test.py
Fixes #1625.
Fixes #1311, fixes #1492 by virtue of reloading the popup after clicking the undo arrow (as well as the enable/disable Badger buttons). This doesn't need to be in this PR; if it causes trouble, let's break it out.
Related to #1627.
Does not fix:
- Poor button placement on whitelisted sites
- Unneeded scrollbars in Firefox (#1610)
- Not recognizing `chrome://extensions` (or Chrome Web Store, or `about:debugging` in Firefox, ...) as a special browser page
- Popup showing the tutorial message when opened on the tutorial page following a new install
- Browser button not getting updated to reflect site whitelist updates in tabs outside of the active tab when enabling/disabling Badger on a site open in multiple tabs
Before:
After:
> Improve popup on special pages

- src/js/multiDomainFirstParties.js
`www.americanexpress.com` is a top site domain in error reports. Most reports seem to complain about messed up stylesheets, which seems to be caused by learning to block `aexp-static.com` resources.
Sample pages:
- https://faq.amextravel.com/
- https://www.americanexpressfhr.com/featured-hotel-searches
- https://www.americanexpress.com/
- https://www.bluebird.com/ (didn't add to MDFP list since it's not clear this is entirely American Express and not AmEx + Walmart, and it's not clear anything is broken (nothing yet in error reports; see below))
- http://catalogue.membershiprewards.com.au/
- https://travel.americanexpress.com.au/
- https://insurance.americanexpress.co.uk/
Example [debugging info](https://gist.github.com/anonymous/8aebb8e48a1ce3c256b21dcfe37af84b):
```
**** ACTION_MAP for …
```
> Add American Express domains to MDFP list

- src/js/multiDomainFirstParties.js
`www.audible.com` shows up as a top source domain for error reports. It seems that Badger somehow learns to block `media-amazon.com` assets there. I don't know how ... I don't see tracking by any `media-amazon.com` subdomains, it's not Cloudflare this time. Maybe the result of a (possibly already fixed) attribution bug? Regardless, we get lots of reports and the fix is easy.
```
+------------------------------+--------------------+-------+
| fqdn                         | blocked_fqdn       | count |
+------------------------------+--------------------+-------+
| www.audible.com              | m.media-amazon.com |    20 |
| www.zappos.com               | m.media-amazon.com |    19 |
| www.twitch.tv                | …
```
> Add more Amazon domains to MDFP

- src/data/yellowlist.txt
Hello,
as reported by @RaoOfPhysics, some users at CERN are using privacybadger and it's blocking content coming from [cds.cern.ch](https://cds.cern.ch) and [mediaarchive.cern.ch](mediaarchive.cern.ch), which is a bit inconvenient for users as it simply blocks images (from CDS) and videos (from mediarchive).
cds.cern.ch (CERN Document Server) is using Piwik (an instance that is hosted at CERN) for gathering usage statistics and mediaarchive.cern.ch is a streaming server for videos, so it doesn't have any scripts.
Would it be possible to add those 2 websites to the yellowlist?
If not, is there anything we should do on our side.
cc @ludmilamarian and @jbenito3 as service managers of CDS.
> Add cds.cern.ch and mediarchive.cern.ch to yellowlist

- src/manifest.json
Fixes #1774
Available for Firefox for Android since 57, see https://github.com/gorhill/uBlock/wiki/Firefox-WebExtensions#firefox-for-android. Tested in 57.0b15
Available for Firefox since 52, see https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/options_ui, Tested in 57.0
> Change options_page to options_ui

- src/js/background.js
- src/js/webrequest.js
This hides "Requests to the server have been blocked by an extension" messages in Chrome and Opera.
Fixes part of #1754 and #907, but not #442, as the extra space is still there.
Collapsing seems to be more involved ... Probably requires a content script modifying pages to hide or remove elements associated with blocked requests (for example, [`domCollapser` in uBlock Origin](https://github.com/gorhill/uBlock/blob/2db377f577a01943c6e3759465c147ec3b596d78/src/js/contentscript.js#L40), [`checkCollapse` in Adblock Plus](https://github.com/adblockplus/adblockpluschrome/blob/ddb764dff1047b5671deb58158930051b2e19052/include.preload.js#L514-L524)).
Only replaces iframes and not images.
Before:
After:
@andresbase @PinkLouie @Werwa In your opinion, is this change an overall improvement, or is it …
> Redirect blocked iframes to 'about:blank'

- src/data/surrogates.js
- src/js/heuristicblocking.js
- src/js/surrogates.js
- src/tests/tests/utils.js
Fixes #1359.
This adds a new surrogate script token type that can be used to match all paths for a given hostname.
I noticed `krxd.net` setting cookies with the content of "DNT". We already ignore various versions of "OPTOUT", so we should also ignore "DNT". Privacy Badger still seems to learn to block `krdx.net` thanks to `cdn.krxd.net` setting non-trivial localStorage data.
[Debug info](gist.github.com/anonymous/8aebb8e48a1ce3c256b21dcfe37af84b) for `krxd.net`:
```
**** ACTION_MAP for krxd.net
beacon.krxd.net {
"dnt": false,
"nextUpdateTime": 0,
}
cdn.krxd.net {
"dnt": false,
"nextUpdateTime": 0,
}
krxd.net {
"dnt": false,
"nextUpdateTime": 0,
}
**** …
```
> Fix Fox News video

- src/js/multiDomainFirstParties.js
Fixes #1502.
Badger learns to block `macysassets.com` after visiting the following pages (without this patch):
- http://www.dealsofamerica.com
- http://area51buy.com
- https://www.macys.com/shop/product/gourmet-basics-by-mikasa-metropolitan-16-pc.-set-service-for-4?ID=1533893
This results in the following [debug data](https://gist.github.com/anonymous/8aebb8e48a1ce3c256b21dcfe37af84b):
```
**** ACTION_MAP for macysassets.com
assets.macysassets.com {
"dnt": false,
"nextUpdateTime": 1513419243394,
}
macysassets.com {
"dnt": false,
"nextUpdateTime": 0,
}
slimages.macysassets.com {
"dnt": false,
"nextUpdateTime": 1513015815833,
}
**** SNITCH_MAP for macysassets.com …
```
> Add Macy's to MDFP list

- src/js/options.js
I was able to fix #1674 on my mac firefox 57.0.1 by doing this.  I ran the unit tests and it pasts but I wasn't able to get the functional tests working on my computer so I don't know if those will pass or not.  Can you let me know if you think this is a good fix or if you have suggestions on modifying it?
> When using Firefox, add an iframe to put the export settings link in

- src/data/yellowlist.txt
Fixes #263. Fixes half of #1815.
Follows up on 68ed094c2ae98317086612262590783458d8fc3e and 346914dde5d270993f65ff833b38800291424dce.
"Facebook Comments Plugin" should eventually be handled by widget replacement (#1467) instead.
Some example pages with Facebook-powered comment sections:
- https://www.huffingtonpost.com/entry/donald-trump-steve-bannon_us_5a4d200ce4b0b0e5a7aa6f15 (click on the speech balloon on the left)
- http://newsok.com/oklahoma-city-pilot-and-anesthesiologist-missing-thursday-search-for-airplane-continues-over-gulf-of-mexico/article/5578224 (similar to above)
- http://www.news9.com/story/37193153/oklahoma-utility-regulators-consider-request-for-rate-cut
- https://fivethirtyeight.com/features/chesss-new-best-player-is-a-fearless-swashbuckling-algorithm/
Yellowlisting …
> Add staticxx.facebook.com to yellowlist

- src/data/yellowlist.txt
[Klarna](https://en.wikipedia.org/wiki/Klarna) seems to power store checkouts across many Scandinavian domains. I haven't actually confirmed that yellowlisting fixes the breakage, but it seems worth a shot.
```
+--------------------------------+----------------------------+-------+
| fqdn                           | blocked_fqdn               | count |
+--------------------------------+----------------------------+-------+
| www.adlibris.com               | evt.klarna.com             |    11 |
| www.adlibris.com               | checkout.klarna.com        |     9 |
| www.adlibris.com               | checkout-client.klarna.com |     6 |
| www.apotea.se                  | checkout.klarna.com        |     6 |
| www.apotea.se …
```
> Add Klarna domains to yellowlist

- src/js/multiDomainFirstParties.js
From a support email:
>cdn01.boxcdn.net was used by buffalo.app.box.com (box.com using buffalo.edu credentials). Moving the slider from blocked to cookies did the trick for that site.
```
+----------------------------+------------------+-------+
| fqdn                       | blocked_fqdn     | count |
+----------------------------+------------------+-------+
| app.box.com                | cdn01.boxcdn.net |     2 |
| cisco.account.box.com      | cdn01.boxcdn.net |     1 |
| downstream.account.box.com | cdn01.boxcdn.net |     1 |
| geant.app.box.com          | cdn01.boxcdn.net |     1 |
| icscreative.app.box.com    | cdn01.boxcdn.net |     1 |
| lendup.account.box.com     | cdn01.boxcdn.net |     1 |
| lion.app.box.com …
```
> Add box.com and boxcdn.net to MDFP list

- src/_locales/en_US/messages.json
- src/js/background.js
- src/js/options.js
- src/skin/options.html
- tests/selenium/options_test.py
Follows up on #1669. Related to #1374, #1675.
This uses an already-translated message from the currently unused slideshow translation set. The checkbox message is new and will need to be translated.
We should focus on what we want to say here the most; this may be good enough for now though.
> Hide tracking domains list on options page behind an acknowledgement

- src/js/multiDomainFirstParties.js
`www.bloomberg.com` is a top error reports site domain this week. Blocking `assets.bwbx.io` breaks the layout, but I can't reproduce tracking. Perhaps this is caused by another mis-attribution bug, maybe what I describe in https://github.com/EFForg/privacybadger/pull/1642#issuecomment-328681731?
Error report counts by page domain and exact blocked subdomain for `bwbx.io`:
```
+-----------------------+----------------+-------+
| fqdn                  | blocked_fqdn   | count |
+-----------------------+----------------+-------+
| www.bloomberg.com     | assets.bwbx.io |   135 |
| www.bloombergview.com | assets.bwbx.io |     2 |
| bloombergview.com     | assets.bwbx.io |     1 |
+-----------------------+----------------+-------+
```
Error report counts by date and exact blocked subdomain for …
> Add some Bloomberg domains to MDFP list

- src/js/background.js
- src/js/heuristicblocking.js
- src/js/migrations.js
- src/js/options.js
- src/js/storage.js
- src/js/surrogates.js
- src/js/webrequest.js
- tests/selenium/dnt_test.py
Fixes #1446. Fixes #1405 by virtue of no longer checking DNT for non-tracking domains.
Follows up on #1642 in terms of continuing to evolve our DNT checking approach.
> Stop recording non-tracking domains

- src/_locales/en_US/messages.json
- src/js/background.js
- src/js/popup.js
- src/js/storage.js
- src/manifest.json
- src/skin/popup.html
Closes #1745, closes #1747.
This removes `unlimitedStorage` from the manifest.
I also changed the "trackers ~~detected~~ blocked" badge color from red to (Badger) orange. Less yelling at the user on basically every page, more on-brand.
Finally, to follow up on https://github.com/EFForg/privacybadger/pull/1795#issuecomment-360631265, when we fail writing to `chrome.storage.local`, we change badge color to red, badge contents to "!", and (reusing the intro reminder widget) show a message in the popup asking the user to let us know about this issue.
What the new badge looks like:
What failing to write to storage looks like on the background page:
What it looks like in the popup:
> Remove unlimited storage

- src/_locales/en_US/messages.json
- src/js/options.js
- src/skin/options-layout.css
- src/skin/options.html
Fixes #1422.
No mass controls yet (or #971, a way to reset settings), just new domain list filters. Is this good enough for now? Screenshots follow.
<details><summary>No filtering</summary>
</details>
<details><summary>Show DNT-compliant only (disables status filter)</summary>
</details>
<details><summary>Show user-controlled, partially-blocked only</summary>
</details>
> Add type/status filters to tracking domains list

- src/js/background.js
- src/js/contentscripts/socialwidgets.js
- src/js/socialwidgetloader.js
- src/js/utils.js
- src/js/webrequest.js
- src/manifest.json
> Remove web_accessible_resources

- src/js/contentscripts/fingerprinting.js
Fixes #1854.
When the site being visited is whitelisted, the fingerprinting detection content script will no longer be injected.
> Changing fingerprinting script to load conditionally

- src/data/yellowlist.txt
This follows up on #1824. Looks like we successfully fixed Klarna problems because we haven't gotten any more Klarna-related complaints. We are getting similar complaints regarding Textalk Webshop though.
Example pages:
- http://gripenbro.se/artiklar/watches/
- http://islina.se/
- http://www.vio.se/vara-produkter/kyrkljus/julgransljus-1-2x11cm-storpack
```
+---------+----------------------+-------+
| ym      | blocked_fqdn         | count |
+---------+----------------------+-------+
| 2018-02 | shopcdn.textalk.se   |     1 |
| 2018-02 | themesorg.textalk.se |     1 |
| 2018-01 | shopcdn.textalk.se   |     1 |
| 2017-12 | shop.textalk.se      |     1 |
| 2017-12 | themesorg.textalk.se |     1 |
| 2017-09 | shop.textalk.se      | …
```
> Add textalk.se to yellowlist

- src/data/yellowlist.txt
I've been in touch with KeyCDN regarding customer reports of Privacy Badger learning to block `kxcdn.com` resources. We think what happened was a customer's Google Analytics cookie was scoped for the entire `.kxcdn.com` domain (instead of their specific subdomain), which means browsing several KeyCDN-powered sites would teach Badger to block `kxcdn.com`. We weren't able to find where exactly this happens, however.
It seems like this is a potential issue with any CDN that uses the same base domain across multiple customer accounts.
There is history of us adding CDNs to the yellowlist (f35b16dc773e86289fb51aec884aa9322d98e207, cfe3cf95e141f161071bfb0930692ca37e3fd32c).
> Add kxcdn.com to yellowlist

- src/data/yellowlist.txt
Fixes #1498.
More sample pages:
- https://www.thefryecompany.com/sale/womens/sacha-zip-shootie-d-77983
- https://www.marksandspencer.com/nl/katoenrijke-jegging/p/P22468863.html
- https://www.eastbay.com/product/model:277664/sku:80839004/nike-free-rn-2017-mens/grey/light-green/
- http://www.dell.com/en-us/shop/dell-24-ultrasharp-monitor-u2417h/apd/210-ahgf/monitors-monitor-accessories
<details><summary>Error report counts by page domain and exact blocked subdomain:</summary>
```
+----------------------------------+-----------------------------------------+-------+
| fqdn                             | blocked_fqdn                            | count |
+----------------------------------+-----------------------------------------+-------+
| www.target.com                   | …
```
> Add bazaarvoice.com to yellowlist

- src/js/multiDomainFirstParties.js
```
+-------------------------------+---------------------------+-------+
| fqdn                          | blocked_fqdn              | count |
+-------------------------------+---------------------------+-------+
| www.gettyimages.com.au        | media.gettyimages.com     |     2 |
| www.gettyimages.nl            | media.gettyimages.com     |     2 |
| www.thinkstockphotos.com      | media.gettyimages.com     |     2 |
| www.gettyimages.ca            | metrics.gettyimages.com   |     2 |
| www.gettyimages.co.uk         | spectrum.gettyimages.com  |     2 |
| www.gettyimages.com.au        | spectrum.gettyimages.com  |     2 |
| www.gettyimages.dk            | spectrum.gettyimages.com  |     2 |
| www.gettyimages.nl …
```
> Add Getty Images to MDFP list

- src/js/multiDomainFirstParties.js
```
+------------------------------+--------------------------+-------+
| fqdn                         | blocked_fqdn             | count |
+------------------------------+--------------------------+-------+
| www.espncricinfo.com         | cdn.espn.com             |    12 |
| www.espnfc.us                | w88.espn.com             |    10 |
| www.espnfc.us                | api-app.espn.com         |     9 |
| www.espncricinfo.com         | w88.espn.com             |     9 |
| www.espncricinfo.com         | fan.api.espn.com         |     6 |
| fivethirtyeight.com          | secure.espn.com          |     6 |
| www.espncricinfo.com         | tredir.espn.com          |     6 |
| www.espncricinfo.com         | …
```
> Add more ESPN domains to MDFP

- src/js/multiDomainFirstParties.js
Another mystery.
```
+------------------+--------------------------+-------+
| fqdn             | blocked_fqdn             | count |
+------------------+--------------------------+-------+
| www.walmart.com  | i5.walmartimages.com     |    23 |
| help.walmart.com | i5.walmartimages.com     |     3 |
| outlook.live.com | i.walmartimages.com      |     1 |
| help.walmart.com | i2.walmartimages.com     |     1 |
| www.walmart.ca   | i5.walmartimages.com     |     1 |
| www.walmart.com  | secure.walmartimages.com |     1 |
+------------------+--------------------------+-------+
```
```
+---------+--------------------------+-------+
| ym      | blocked_fqdn             | …
```
> Add two more Walmart domains to MDFP list

- src/js/multiDomainFirstParties.js
Also not clear how Badger learns to block `newegg.com` but it does. Logging in is probably part of it, which I tried, but I don't know what the third domain for Badger to learn from is.
My [debug info](gist.github.com/anonymous/8aebb8e48a1ce3c256b21dcfe37af84b):
```
**** ACTION_MAP for newegg.com
secure.newegg.com {
"dnt": false,
"nextUpdateTime": 1519787876865
}
newegg.com {
"dnt": false,
}
ssl-images.newegg.com {
"dnt": false,
"nextUpdateTime": 1519470707776
}
**** SNITCH_MAP for newegg
newegg.com [
"newegg.ca",
"neweggbusiness.com"
]
```
``` …
```
> Add Newegg to MDFP list

- src/js/multiDomainFirstParties.js
I don't know why Privacy Badger learns to block `slickdealscdn.com`, but it does, and we consistently get a few reports about it every month.
Error report counts by page domain and exact blocked subdomain (or, where and how many times were the different `slickdealscdn.com` subdomains reported as blocked in user error reports):
```
+----------------+--------------------------+-------+
| fqdn           | blocked_fqdn             | count |
+----------------+--------------------------+-------+
| slickdeals.net | css.slickdealscdn.com    |   102 |
| slickdeals.net | static.slickdealscdn.com |    99 |
| slickdeals.net | js.slickdealscdn.com     |    53 |
+----------------+--------------------------+-------+
```
Error report counts by date and exact blocked subdomain (or, how often do we get …
> Add Slickdeals to MDFP list

- tests/selenium/pbtest.py
Occasionally, a request for a web page during a functional test will time out and fail, for some reason not related to Privacy Badger's correctness. e.g. https://travis-ci.org/EFForg/privacybadger/jobs/344463078.
This change would retry requests that time out up to 5 times before giving up. This should reduce the amount of false-negative test failures.
> Retry on timeout errors when loading a URL

- src/data/yellowlist.txt
Fixes #1153. See https://github.com/EFForg/privacybadger/issues/1153#issuecomment-368580638 for more information.
> Add Cloudinary (CDN) to yellowlist

- scripts/setup_travis.sh
- src/js/background.js
- src/js/htmlutils.js
- src/js/popup.js
- src/js/webrequest.js
- src/skin/popup.html
- src/tests/tests/htmlutils.js
- tests/selenium/cookie_test.py
- tests/selenium/dnt_test.py
- tests/selenium/popup_test.py
Fixes #1060.
Fixes #1634 by properly calling `init()` in places where we test the popup. We'll probably always need to use workarounds to test the popup as there doesn't seem to be a way to open extension popups with Selenium.
> Fix popup in Private Browsing windows

- src/data/surrogates.js
Fixes #1904. Should check to see if any other uAssets-based surrogates need updating.
Previously: #1738.
> Update googletagservices.com surrogate

- src/data/yellowlist.txt
Fixes #1910.
To reproduce Privacy Badger learning to block `pandacommerce.net` resources, visit a PandaCommerce-powered shop, add an item to your cart and proceed to checkout to get tracking cookies (looks like Google Analytics: `_ga` and `_gid`) on the `pandacommerce.net` domain. (There are also some cookies and localStorage on `checkout.pandacommerce.net`.) Visiting any other PandaCommerce shops at this point will send those cookies, so visiting two more shops should teach Privacy Badger to start blocking `pandacommerce.net` domains.
Example shops:
- http://www.marelimedical.com/
- https://www.sexleksakeroutlet.se/
- https://www.andromedaslust.se/
> Add pandacommerce.net to yellowlist

- src/data/yellowlist.txt
Follows up on #1730.
Sample pages:
- http://www.argos.co.uk/product/4136774
- http://www.compumail.dk/vare-oversigt.php?varenummer=990144106
- https://www.newegg.ca/Product/Product.aspx?Item=N82E16820233970&cm_sp=Homepage_FDD-_-P1_20-233-970-_-03232018
The "Overview" tab becomes missing in that last link.
> Add more cnetcontent.com domains to yellowlist

- src/data/yellowlist.txt
```
+----------------------------------+------------------------------+-------+
| fqdn                             | blocked_fqdn                 | count |
+----------------------------------+------------------------------+-------+
| www.chevynorthridge.com          | fo-static.assets-cdk.com     |     1 |
| www.cornerstonechevrolet.com     | fo-static.assets-cdk.com     |     1 |
| www.covertcadillac.com           | fo-static.assets-cdk.com     |     1 |
| www.foxgm.com                    | fo-static.assets-cdk.com     |     1 |
| www.grossingerchevycadillac.com  | fo-static.assets-cdk.com     |     1 |
| www.hilltopchevy.com             | fo-static.assets-cdk.com     |     1 |
| www.jimkerasmemphis.com          | …
```
> Add assets-cdk.com to yellowlist

- src/data/yellowlist.txt
Fixes display of various chart/price quote widgets from TradingView.
Besides cookies and localStorage, I see "database storage" (#1557):
Examples:
- https://seekingalpha.com/symbol/AAPL/chart
- https://cryptoking.org
- https://cryptosignals.trade/markets-live/
- https://prices.org/ethereum/
- http://www.pmbull.com/gold-price/
> Add tradingview.com to yellowlist

- src/js/multiDomainFirstParties.js
We are (and have been) getting a lot of error reports for Facebook, most of them with NULL entries for blocked domains. Sometimes `fbsbx.com` is listed as blocked. Seems like it should join Facebook's other domains in the MDFP list. Let's see if this helps cut down on Facebook reports.
I haven't investigated the reports beyond this point.
```
+-------------------+-------------------------------------+-------+
| fqdn              | blocked_fqdn                        | count |
+-------------------+-------------------------------------+-------+
| www.facebook.com  | fbsbx.com                           |    16 |
| www.facebook.com  | cdn.fbsbx.com                       |     4 |
| www.facebook.com  | …
```
> Add fbsbx.com to Facebook's MDFP list

- src/js/multiDomainFirstParties.js
You might have to log in first in order to reproduce Privacy Badger learning to block `glassdoor.com`. 
Sample regional pages:
- https://www.glassdoor.ca/Job/vancouver-embedded-software-developer-jobs-SRCH_IL.0,9_IC2278756_KO10,37.htm
- https://www.glassdoor.com.au/Job/rockdale-jobs-SRCH_IL.0,8_IC2243547.htm
- https://www.glassdoor.ie/Salary/FireEye-Dublin-Salaries-EI_IE235161.0,7_IL.8,14_IM1052.htm
```
+----------------------+-----------------------+-------+
| fqdn                 | blocked_fqdn          | count |
+----------------------+-----------------------+-------+
| www.glassdoor.ca     | static.glassdoor.com  |    15 |
| www.glassdoor.ca     | media.glassdoor.com   |    10 |
| www.glassdoor.ca     | www.glassdoor.com …
```
> Add Glassdoor to MDFP

- src/js/options.js
Fixes #1918.
src/options.js, line 100. move window back to top of page
> fix for "clicking tabs makes window scroll down"

- src/js/multiDomainFirstParties.js
To fix recent breakages such as:
```
url: https://experiencecloud.adobeexchange.com/
block: app-cdn.adobe.com,wwwimages2.adobe.com,static.adobelogin.com,adobeid-na1.services.adobe.com
noaction: assets.adobedtm.com,use.typekit.com,p.typekit.net,cc-collab.adobe.io,dc5tqsrhldvnl.cloudfront.net,l.betrad.com,mir-s3-cdn-cf.behance.net
message: css not loading
```
```
url: https://typekit.com/fonts/omnes
block: bam.nr-data.net,commerce.adobe.com,wwwimages2.adobe.com,adobeid-na1.services.adobe.com
noaction: use.typekit.net,assets.adobedtm.com,ssl.google-analytics.com,p.typekit.net,s3.amazonaws.com,cc-collab.adobe.io,js-agent.newrelic.com,a5.behance.net
message: Pressing sync for one of the fonts on typekit.com results in an endless loop and no synchronising of the chosen font.
```
```
url: …
```
> Add some Adobe properties to MDFP list

- src/js/multiDomainFirstParties.js
TechMedia operates two a few websites, the most prominent being habahabr.ru and geektimes.ru (think slashdot with some local quirks).
Both sites use dr.habracdn.net to serve CSS&JS and hsto.org to serve images.  habrastorage.org seems to only ever return 302 302 Moved Temporarily and redirect to hsto.org.
Currently, Privacy Badger blocks dr.habracdn.net and hsto.org, requiring manual yellowlisting.
> MDFP for TechMedia sites

- src/js/multiDomainFirstParties.js
Fixes #1931. I noticed `pardot.com` as another Salesforce-owned domain from error reports.
> Add Salesforce domains to MDFP

- src/js/webrequest.js
Fixes #1929 (and follows up on #1642).
One way to reproduce the bug is to import an older Privacy Badger data file that knows to block a good number of domains that are ready to have their DNT policies rechecked (old-enough `nextUpdateTime` timestamps in `action_map`), and visit some news site (lots of tracking domains) in Private Browsing or Incognito. Since DNT requests contact remote servers and modify local data, you should not see any DNT requests go out, but you will see some for domains on the page that Privacy Badger previously learned to block.
> Fix DNT checking in Private Browsing/Incognito

- src/data/yellowlist.txt
Fixes #1180.
More examples:
- https://www.stitcher.com/podcast/rncn/financial-gravity-with-john-pollock/e/53853435
- https://usa.streetsblog.org/2018/03/23/talking-headways-podcast-mobility-is-like-a-heavy-metal-band/
- https://overcast.fm/+HOFj9gH3g
I see session and day-long cookies (#1545):
```
+---------+---------------------------+-------+
| ym      | blocked_fqdn              | count |
+---------+---------------------------+-------+
| 2018-03 | assets.libsyn.com         |     3 |
| 2018-03 | fightsgoneby.libsyn.com   |     1 |
| 2018-03 | html5-player.libsyn.com   |     2 |
| 2018-03 | hwcdn.libsyn.com          |     1 |
| 2018-03 | secure-hwcdn.libsyn.com   |     6 |
| 2018-03 | ssl-static.libsyn.com     |     1 |
| 2018-03 | …
```
> Add libsyn.com to yellowlist

- src/data/yellowlist.txt
Example sites:
- https://www.onet.pl
- https://www.blic.rs
- https://businessinsider.com.pl
- http://www.auto-swiat.pl
- http://www.fakt.pl
- https://www.skapiec.pl
- https://vod.pl
- https://www.forbes.pl
See two long-lived cookies set on `events.ocdn.eu`.
```
+---------+------------------------------+-------+
| ym      | blocked_fqdn                 | count |
+---------+------------------------------+-------+
| 2018-04 | events.ocdn.eu               |     5 |
| 2018-04 | mastt.ocdn.eu                |     2 |
| 2018-04 | ocdn.eu                      |     9 |
| 2018-03 | events.ocdn.eu               |    21 |
| 2018-03 | m.ocdn.eu                    |     2 |
| 2018-03 | mastt.ocdn.eu                |     3 |
| 2018-03 | ocdn.eu …
```
> Add ocdn.eu to yellowlist

- src/data/yellowlist.txt
Fixes #1950.
I see a session cookie (#1545) and a `rs_lang=en_US` cookie (Privacy Badger doesn't recognize "en_US" as a language code yet).
> Add rewardstyle.com to yellowlist

- src/data/yellowlist.txt
Fixes #1933.
More examples:
- https://pages.ubuntu.com/container-whitepaper.html
- https://apply.surveymonkey.com/apply-demo/
```
+---------+------------------------+-------+
| ym      | blocked_fqdn           | count |
+---------+------------------------+-------+
| 2018-04 | abrtp1-cdn.marketo.com |     1 |
| 2018-04 | abrtp1.marketo.com     |     1 |
| 2018-04 | app-ab04.marketo.com   |     1 |
| 2018-04 | app-ab13.marketo.com   |     1 |
| 2018-04 | app-ab20.marketo.com   |     1 |
| 2018-04 | app-ab25.marketo.com   |     2 |
| 2018-04 | app-aba.marketo.com    |     1 |
| 2018-04 | app-lon03.marketo.com  |     1 |
| 2018-04 | app-sj02.marketo.com   |     1 |
| 2018-04 | app-sj23.marketo.com   |     1 |
| 2018-04 | …
```
> Add marketo.com to yellowlist

- src/js/contentscripts/clobbercookie.js
- src/js/contentscripts/clobberlocalstorage.js
- src/js/contentscripts/dnt.js
- src/js/contentscripts/fingerprinting.js
- src/js/contentscripts/socialwidgets.js
- src/js/contentscripts/supercookie.js
Fixes #1949.
This only seems to happen in Firefox. Does Chrome handle the checks we add in this PR internally?
Sample XML document: https://sourceforge.net/sitemap.xml
Sample XHTML document: http://tieba.baidu.com/mo/q---2799060AC2198378C599200012D229ED%3AFG%3D1--1-3-0--2--wapp_1440757687244_809/m?kw=%E9%9A%90%E6%9D%80&lp=1030
This seems like a good thing to have automated tests for, but I haven't yet figured out how to detect the difference between a pretty-rendered XML document in Firefox and a non-pretty-thanks-to-an-injected-script-tag version of the same with Selenium. The problem seems to be that Firefox handles its pretty rendering HTML specially; it's not part of the document (doesn't seem to be even inspectable by dev tools).
<details><summary>Here is my (non-working) test …
> Fix XML document rendering in Firefox

- src/js/multiDomainFirstParties.js
Fixes #1971.
Not sure what causes blocking, but the solution seems straightforward. This is a combination of the report in #1971 and noticing consistent complaints about `pmo.ee` resources being blocked across `postimees.ee` subdomains in error reports.
Error report counts by page domain and exact blocked `pmo.ee` subdomain:
```
+-----------------------------+---------------+-------+
| fqdn                        | blocked_fqdn  | count |
+-----------------------------+---------------+-------+
| www.postimees.ee            | f.pmo.ee      |    19 |
| www.postimees.ee            | f2.pmo.ee     |    16 |
| www.postimees.ee            | f4.pmo.ee     |    16 |
| www.postimees.ee            | f6.pmo.ee     |    16 |
| www.postimees.ee            | i.pmo.ee      |    15 |
| www.postimees.ee …
```
> Add postimees.ee-related domains to MDFP

- src/data/yellowlist.txt
See a bunch of GA cookies on `greenhouse.io`.
Examples:
- https://www.fwd.us/careers
- http://www.boingo.com/corporate/careers/#positions
- https://nextdoor.com/jobs/
- https://www.voxmedia.com/pages/careers-jobs#jobs-list
- https://www.mapbox.com/careers/#careers
- https://sproutsocial.com/careers/open-positions/#/
```
+---------+-------------------------------+-------+
| ym      | blocked_fqdn                  | count |
+---------+-------------------------------+-------+
| 2018-04 | api.greenhouse.io             |     2 |
| 2018-04 | boards-use1-cdn.greenhouse.io |     1 |
| 2018-04 | boards-usw2-cdn.greenhouse.io |     1 |
| 2018-04 | boards.greenhouse.io          |     1 |
| 2018-04 | cdn.greenhouse.io             |     2 |
| …
```
> Add greenhouse.io to yellowlist

- src/data/yellowlist.txt
- src/js/multiDomainFirstParties.js
Fixes #1970.
The MDFP entries are to eliminate breakage on Wix itself; the yellowlist update is to fix Wix-powered sites.
Not clear how `parastorage.com` ends up blocked. Might need to be a Wix user to have this happen.
Error report counts by page domain and exact blocked `parastorage.com` subdomain:
```
+-------------------------------------------+------------------------------+-------+
| fqdn                                      | blocked_fqdn                 | count |
+-------------------------------------------+------------------------------+-------+
| www.wix.com                               | static.parastorage.com       |    48 |
| users.wix.com                             | static.parastorage.com       |    30 |
| editor.wix.com                            | static.parastorage.com …
```
> Add Wix domains to MDFP and yellowlist

- src/data/yellowlist.txt
Fixes #1539.
Error report counts by date and exact blocked `mailchimp.com` subdomain:
```
+---------+--------------------------+-------+
| ym      | blocked_fqdn             | count |
+---------+--------------------------+-------+
| 2018-04 | cdn-images.mailchimp.com |     6 |
| 2018-04 | downloads.mailchimp.com  |     1 |
| 2018-04 | gallery.mailchimp.com    |     1 |
| 2018-03 | cdn-images.mailchimp.com |     6 |
| 2018-03 | gallery.mailchimp.com    |     4 |
| 2018-02 | cdn-images.mailchimp.com |     9 |
| 2018-02 | downloads.mailchimp.com  |     1 |
| 2018-02 | gallery.mailchimp.com    |     4 |
| 2018-01 | cdn-images.mailchimp.com |     7 |
| 2018-01 | gallery.mailchimp.com    |     3 |
| 2018-01 | us6.admin.mailchimp.com  |     1 |
...
```
Error report counts by date and exact …
> Add two MailChimp domains to the yellowlist

- tests/selenium/dnt_test.py
- tests/selenium/pbtest.py
This follows up on this failed job: https://travis-ci.org/EFForg/privacybadger/jobs/359621950.
It's not clear why we got what doesn't appear to be JSON from the httpbin page (see below), but this PR should handle invalid JSON scenarios and retry the test where it happened.
```python
'JSON\nRaw Data\nHeaders\nSave\nCopy\nargs {}\nheaders\nAccept "text/html,application/xhtml+xml,application/xml;q=0.9,.../5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0"\norigin "35.184.226.236"\nurl "https://httpbin.org/get"'
```
> Add JSON error handling and retrying to DNT header tests

- src/js/multiDomainFirstParties.js
`wnycstudios.org` and `newsounds.org`.
Follows up on #1694 and https://github.com/EFForg/privacybadger/pull/1987#discussion_r184552450.
Error report counts by date and exact blocked `wnyc.org` subdomain:
```
+---------+----------------------+------------------------+-------+
| ym      | blocked_fqdn         | fqdn                   | count |
+---------+----------------------+------------------------+-------+
| 2018-04 | api.wnyc.org         | www.wnycstudios.org    |     7 |
| 2018-04 | media.wnyc.org       | www.wnycstudios.org    |     7 |
| 2018-03 | api.wnyc.org         | www.newsounds.org      |     1 |
| 2018-03 | api.wnyc.org         | www.propublica.org     |     1 |
| 2018-03 | api.wnyc.org         | www.wnycstudios.org    |     7 |
| 2018-03 | audio.wnyc.org       | …
```
> Add a couple of domains to NYPR's MDFP list

- src/js/storage.js
Fixes #1866. Supersedes #1913.
Here are the errors we've seen so far:
- `QUOTA_BYTES` #1717
- `FILE_ERROR_NO_SPACE` #1866 
- "Could not perform read" #1952
- "Corruption: block checksum mismatch" #1963
Looks like there are many different corruption scenarios: https://chromium.googlesource.com/chromium/src/+/2a9a8201b8c0b213aa41b6a390e9324113176f15/third_party/leveldatabase/env_chromium.cc#658
> Ignore storage update errors unrelated to Privacy Badger

- src/_locales/en_US/messages.json
- src/js/background.js
- src/js/migrations.js
- src/js/options.js
Fixes #1099 by changing what happens when "Prevent WebRTC from leaking local IP address" is unchecked.
For descriptions of modes, see https://tools.ietf.org/html/draft-ietf-rtcweb-ip-handling-01#page-5.
Before:
- Unchecked (Badger default): Mode 3
- Checked: Mode 4
After:
- Unchecked (Badger default): Mode 1
- Checked: Mode 4
The problem with defaulting to Mode 3 is that it noticeably degrades video conferencing, causes unexpected breakage for less-robust WebRTC applications, and breaks user expectations with regard to unchecked settings.
This should match uBlock Origin's logic.
> Reset default WebRTC protection to browser setting

- src/data/yellowlist.txt
We're still getting quite a few error reports where Privacy Badger learned to block `akamaized.net` domains. We should try to reproduce tracking and generally figure out how this happens. Regardless, blocking `akamaized.net` breaks lots of sites.
Error report counts with blocked `akamaized.net` resources by date and site domain:
```
+---------+--------------------------+-------+
| ym      | fqdn                     | count |
+---------+--------------------------+-------+
| 2018-04 | www.msn.com              |    30 |
| 2018-04 | support.microsoft.com    |    18 |
| 2018-04 | www.microsoft.com        |    18 |
| 2018-04 | account.microsoft.com    |    15 |
| 2018-04 | answers.microsoft.com    |    15 |
| 2018-04 | support.office.com       |    14 |
| 2018-04 | products.office.com      | …
```
> Add akamaized.net to yellowlist

- LICENSE
- src/js/firstparties/facebook.js
- src/manifest.json
Add a first-party script to unwrap and remove click handlers from outgoing links on facebook.com. Addresses part of #85.
This has been tested in Chrome and Firefox desktop browsers. For the most part, it seems to prevent Facebook from learning about which non-sponsored links you click in your newsfeed. 
It's not perfect. For some reason, in Firefox, middle-clicking (with the mouse wheel) on a link still triggers an XHR to https://www.facebook.com/ajax/bz with a tracking payload (with data like `click_ref:[..."https://url-you-clicked.com"]`). I'm not sure where this is happening, since the script should block all bubbling event handlers attached to each `<a>` element and I've checked all the capturing onclick handlers on a typical link's parent elements. I've decided to stop pursuing it …
> Unwrap links on facebook.com

- src/js/popup.js
Broken somewhere in the following range: https://github.com/EFForg/privacybadger/compare/chrome-2016.4.13...chrome-2016.5.16, when we switched from `"userblock"`, etc. to `constants.USER_BLOCK` / `"user_block"` action names. `2016.4.13` is the last version in error reports to have non-NULL "user" field values.
> Fix user-set domains in error reports

- src/skin/popup.css
By reverting the CSS padding change from bc231ec1d24afbba97d07cf898266e51b406b337.
Fixes #1977.
Could you please check Android is still OK?
> Work around broken Italian locale popup in Chrome

- src/js/firstparties/twitter.js
Fixes https://github.com/EFForg/privacybadger/issues/1426
Some things I noticed as for the current implementation:
* I don't understand why you need two loops
* Also why is the selector query so specific if you filter out the elements later anyway?
* The above combined, this could easily be simplified into only one loop for all t.co elements
* Why does the query include **http**://t.co links? Does Twitter use them anywhere, anyway? AFAIK they are HTTPS-only for some time already, are not they?
**Edit:** Saw https://github.com/EFForg/privacybadger/pull/1392#issuecomment-304400706, but don't know whether that is valid for profile links. Anyway, who cares… 
I read https://github.com/EFForg/privacybadger/pull/1392#issuecomment-307234848 and saw that you want to avoid `title` due to XSS …
> Add title as full URL atttribute for Twitter profile links

- src/js/multiDomainFirstParties.js
Another session cookies issue (#1545).
Error report counts by date, exact blocked `reastatic.net` subdomain, and site domain:
```
+---------+----------------------+---------------------------+-------+
| ym      | blocked_fqdn         | fqdn                      | count |
+---------+----------------------+---------------------------+-------+
| 2018-05 | s1.rea.reastatic.net | www.realestate.com.au     |     4 |
| 2018-04 | s1.rea.reastatic.net | www.realestate.com.au     |    13 |
| 2018-03 | s2.rea.reastatic.net | www.realestate.com.au     |     8 |
| 2018-02 | s2.rea.reastatic.net | www.realestate.com.au     |     7 |
| 2018-01 | s2.rea.reastatic.net | www.realestate.com.au     |     1 |
...
```
> Add realestate.com.au domains to MDFP

- tests/selenium/dnt_test.py
- tests/selenium/fingerprinting_test.py
- tests/selenium/localstorage_test.py
- tests/selenium/options_test.py
- tests/selenium/pbtest.py
- tests/selenium/popup_test.py
- tests/selenium/qunit_test.py
- tests/selenium/super_cookie_test.py
- tests/selenium/surrogates_test.py
Should be replaced as necessary with conditional, poll-based waits for specific requirements (an element is visible, a JavaScript statement evals to true, ...).
Closes #2073.
> Remove unconditional waiting support from load_url

- src/_locales/en_US/messages.json
- src/js/background.js
- src/js/contentscripts/dnt.js
- src/js/options.js
- src/js/webrequest.js
- src/skin/options-layout.css
- src/skin/options.html
This creates an option to disable sending the DNT header per issue https://github.com/EFForg/privacybadger/issues/2038
The default setting is set to enabled.
> Add option to disable sending the Do Not Track (DNT) signal

- src/data/yellowlist.txt
Prompted by https://github.com/EFForg/privacybadger/issues/2065#issuecomment-397050689.
Fixes #2090.
Error report counts by date and exact blocked "openstreetmap" subdomain:
```
+---------+-------------------------+-------------------------+-------+
| ym      | blocked_fqdn            | fqdn                    | count |
+---------+-------------------------+-------------------------+-------+
| 2018-06 | www.openstreetmap.org   | cccfr.de                |     1 |
| 2018-05 | www.openstreetmap.org   | garmin.openstreetmap.nl |     1 |
| 2018-04 | www.openstreetmap.org   | hdyc.neis-one.org       |     1 |
| 2018-03 | www.openstreetmap.org   | garmin.openstreetmap.nl |     1 |
| 2018-03 | www.openstreetmap.org   | www.openstreetcam.org   |     1 |
| 2018-02 | www.openstreetmap.org   | …
```
> Add all of openstreetmap.org to yellowlist

- src/data/yellowlist.txt
Webflow is a popular web page builder. Currently, Privacy Badger prevents loading JS, HTML, and CSS from Webflow breaking all Webflow sites.
Example sites broken: https://www.carlybruce.com/ and https://www.finsweet.com/
Privacy Badger debugging info
```js
**** ACTION_MAP for webflow.com
forum.webflow.com {
"dnt": true,
"nextUpdateTime": 1531422582159,
}
global-uploads.webflow.com {
"dnt": false,
"nextUpdateTime": 1519509940293,
}
uploads-ssl.webflow.com {
"dnt": false,
"nextUpdateTime": 1531264596178,
"userAction": "user_cookieblock"
}
uploads.webflow.com {
"dnt": false,
"nextUpdateTime": 1516885150018,
"userAction": "user_allow"
}
webflow.com …
```
> Add webflow.com to yellowlist

- src/_locales/en_US/messages.json
- src/skin/options.html
Follows up on #2089.
Replaces "sites" with "external domains" for clarity.
Removes the "learn more" link and links the words directly for consistency.
Current text:
Proposed update:
> Update DNT policy checking checkbox label text

- Makefile
- scripts/fix_placeholders.py
- src/_locales/bg/messages.json
- src/_locales/cs/messages.json
- src/_locales/da/messages.json
- src/_locales/de/messages.json
- src/_locales/en_US/messages.json
- src/_locales/eo/messages.json
- src/_locales/es/messages.json
- src/_locales/fr/messages.json
- src/_locales/it/messages.json
- src/_locales/nb_NO/messages.json
- src/_locales/nl/messages.json
- src/_locales/pl/messages.json
- src/_locales/ru/messages.json
- src/_locales/sr/messages.json
- src/_locales/sv/messages.json
- src/_locales/tr/messages.json
- src/_locales/uk/messages.json
- src/_locales/zh/messages.json
- src/_locales/zh_TW/messages.json
- src/js/contentscripts/socialwidgets.js
- src/js/htmlutils.js
- src/js/options.js
- src/js/popup.js
- src/skin/options.html
- src/skin/popup.html
- src/tests/tests/htmlutils.js
- tests/selenium/options_test.py
Fixes #1329.
We are about to get a Persian locale, which is a right-to-left script (support added in f0f4f53245446305e8ee8bfb1071b6189ef40150). Some of our messages are formed by concatenating multiple locale strings in the code, which I think tips the scales in favor of using placeholders.
> Use i18n placeholders

- src/js/firstparties/facebook.js
- src/manifest.json
This is exactly the same as #2033, which was closed after being merged into #2016. This set of changes is simpler and more urgent.
This addresses a few issues that have come up since we merged the feature. Some of the issues are pulled from https://github.com/mgziminsky/FacebookTrackingRemoval.
- StopPropagation calls are replaced by StopImmediatePropagation
- Only nodes of type ELEMENT_NODE are "cleaned"
- The unwrapping script now runs on Facebook's .onion domain as well
Closes #2012, closes #2014, closes #2018.
> Improve Facebook link unwrapping

- src/data/socialwidgets.json
- src/js/contentscripts/socialwidgets.js
Only match soundcloud script tags which begin with https://w.soundcloud.com, which will prevent javascript injection via widget replacement. Ensure that the node being replaced is a script.
> Make Soundcloud contentscript match more specific

- src/tests/tests/firstparties.js
Add qunit test for facebook first-party script for basic functionality and for the XSS exploit fixed in 2018.7.18. Factor out common test functions from twitter unittest.
> Add unittest for Facebook first-party script

- src/data/yellowlist.txt
Privacybadger is blocking access to `api.guildwars2.com` which is the [official public API for the MMORPG Guild Wars 2](https://api.guildwars2.com/v2). It can only be used to read personal data off an account if the user previously generated and provided a valid API key (see "Authentication" section at the bottom), which makes this opt-in.
(Probably?) since all sites making use of that API are hosted on different domains, and most of the sites access the API from the client side, Privacybadger blocks the access to this API, regularly causing questions like [this](https://www.reddit.com/r/Guildwars2/comments/53zunu/gw2efficiency_account_values_statistics_update/d7xvuzk/?context=3) or [this](https://www.reddit.com/r/Guildwars2/comments/91j9lh/best_conversion_rates_for_zephyrite_supply_boxes/ …
> Add "guildwars2.com" to yellowlist

- src/js/contentscripts/socialwidgets.js
Not needed for SoundCloud; a carryover from copying the AddThis button code path.
Follows up on #2113 and #749.
> Avoid replacing scripts for SoundCloud widgets

- .eslintignore
On my machine, running "make lint" always prints a list of errors from javascript files in the Selenium directory in my virtualenv. This PR will ignore those files.
> Add selenium files to .eslintignore

- src/js/multiDomainFirstParties.js
Error report counts by page domain and exact blocked "assets-gap" subdomain:
```
+---------------------------------------------+----------------------+-------+
| fqdn                                        | blocked_fqdn         | count |
+---------------------------------------------+----------------------+-------+
| www.gap.com                                 | www1.assets-gap.com  |    20 |
| www.gap.com                                 | www3.assets-gap.com  |    20 |
| www.gap.com                                 | www4.assets-gap.com  |    19 |
| www.gap.com                                 | www2.assets-gap.com  |    18 |
| bananarepublic.gap.com                      | www3.assets-gap.com  |    18 |
| bananarepublic.gap.com                      | www1.assets-gap.com  |    17 |
| …
```
> Update Gap's MDFP list

- src/js/multiDomainFirstParties.js
Not yet clear (from error reports) how `avito.st` subdomains end up blocked. Maybe from being [sourced on third-party sites](https://publicwww.com/websites/"avito.st"/)?
Error report counts by page domain and exact blocked "avito" subdomain:
```
+--------------+--------------------------------+-------+
| fqdn         | blocked_fqdn                   | count |
+--------------+--------------------------------+-------+
| www.avito.ru | www.avito.st                   |     7 |
| www.avito.ru | 36.img.avito.st                |     5 |
| www.avito.ru | 78.img.avito.st                |     5 |
| www.avito.ru | 12.img.avito.st                |     4 |
| www.avito.ru | 30.img.avito.st                |     4 |
| www.avito.ru | 39.img.avito.st                |     4 |
| www.avito.ru | …
```
> Add Avito to MDFP list

- src/js/multiDomainFirstParties.js
Got a few user error reports. Not clear why Badger learns to block it. Maybe people embed things from `dropboxusercontent.com` on their sites? Anyway, Dropbox is a big site and this domain belongs to it.
> Add dropboxusercontent.com to Dropbox's MDFP list

- .github/ISSUE_TEMPLATE/broken-site-report.md
Remove most of the instructions body from the template and replace with a link to the [new wiki page](https://github.com/EFForg/privacybadger/wiki/Find-out-why-Privacy-Badger-is-blocking-a-domain).
> Revise broken site report template to include wiki link

- src/js/multiDomainFirstParties.js
I don't see any reports outside of `wetter.com`, but I think Privacy Badger learns to block `wettercomassets.com` when Wetter.com-powered widgets are used on third-party websites. You can get examples from https://publicwww.com/websites/"wettercomassets.com"/.
Error report counts by page domain and exact blocked "wetter" subdomain:
```
+---------------------+----------------------------------+-------+
| fqdn                | blocked_fqdn                     | count |
+---------------------+----------------------------------+-------+
| www.wetter.com      | ls1.wettercomassets.com          |    24 |
| www.wetter.com      | m1.wettercomassets.com           |    21 |
| www.wetter.com      | ls2.wettercomassets.com          |    20 |
| www.wetter.com      | m2.wettercomassets.com           | …
```
> Add wetter.com to MDFP list

- src/js/multiDomainFirstParties.js
Error report counts by page domain and exact blocked "reuters" subdomain:
```
+-------------------------------------+-----------------------------+-------+
| fqdn                                | blocked_fqdn                | count |
+-------------------------------------+-----------------------------+-------+
| www.reuters.com                     | reuters-d.openx.net         |    16 |
| www.reuters.com                     | s2.reutersmedia.net         |    12 |
| www.reuters.com                     | s3.reutersmedia.net         |    12 |
| www.reuters.com                     | s4.reutersmedia.net         |    12 |
| www.reuters.com                     | s1.reutersmedia.net         |     8 |
| www.reuters.com                     | reuters.demdex.net          |     6 |
| www.reuters.com …
```
> Add Reuters domains to MDFP list

- src/data/yellowlist.txt
Fixes #2059.
Blocking `img.purch.com` breaks images on several prominent sites. `purch.com` is blocked in latest pre-trained data. I see cookie tracking from `privacy.purch.com` and canvas fingerprinting from `assets.purch.com`.
```
+--------------------------+-----------------------------------------+-------+
| fqdn                     | blocked_fqdn                            | count |
+--------------------------+-----------------------------------------+-------+
| www.tomshardware.com     | assets.purch.com                        |   130 |
| www.tomshardware.com     | img.purch.com                           |   117 |
| www.space.com            | syndicate.purch.com                     |    61 |
| www.space.com            | …
```
> Add img.purch.com to yellowlist

- .gitignore
- doc/tests.md
- scripts/setup_travis.sh
Fixes #1896.
Per the comments on the thread, after my fix, and after manually calling the functions in setup_travis.sh from the command line in Terminal, I was able to run the selenium test suite using the command line: 
`BROWSER=/Applications/Firefox.app/Contents/MacOS/firefox pytest -v .`
and was able to complete the test run. Pytest Configuration:
platform darwin -- Python 3.6.4, pytest-3.7.2, py-1.5.4, pluggy-0.7.1
I did not see the second issue reported in the thread, but Python version (3.4 vs 3.6) may be a factor.
> Fix for Issue #1896: script and docs for functional tests locally on MacOS.

- src/_locales/en_US/messages.json
- src/skin/options-layout.css
- src/skin/options.html
Fixes #1662.
The text:
>Importing:
>- Overwrites general settings
>- Combines the lists of sites where your Badger should be disabled
>- Teaches your Badger about the trackers in the import
> Add an explanation of what happens on data import

- src/skin/popup.css
Fix #1120 by setting ad-hoc styles for the popup shown from the overflow menu.
One odd thing I've noticed, and maybe you can check if it happens to you as well: the *first* time the popup is opened from the overflow menu, the popup is wider than it should be and there is a blank space on the right. Screenshot:
From then on the popup is shown correctly.
Also, the problem is not present if the option "disable popup auto hide" is set. It looks like firefox is not updating the width of the popup fast enough.
> Fix popup layout for overflow menu in Firefox

- src/js/multiDomainFirstParties.js
Domain list taken from https://www.nettix.fi/in-english/ and error reports (below).
Another set of broken sites caused by Badger not auto-learning to block Google Analytics (#367). GA sets a first-party cookie on `nettix.fi`; NettiX uses `nettix.fi` subdomains scoped to the GA cookie to serve static resources on NettiX sites.
> Add NettiX domains to MDFP list

- src/data/yellowlist.txt
To reproduce, first visit rentcafe.com to get a Google Analytics (#367) cookie set on `cdngeneral.rentcafe.com` and then visit three of the sites below.
Sample debug info:
```
**** ACTION_MAP for rentcafe.com debugger eval code:3:3
t.rentcafe.com {
"dnt": false,
"nextUpdateTime": 1535522741860
}
cdngeneral.rentcafe.com {
"dnt": false,
"nextUpdateTime": 1535427264771
}
rentcafe.com {
"dnt": false,
}
**** SNITCH_MAP for rentcafe.com
rentcafe.com [
"beaconviewapts.com",
"shorehamapartments.com",
"apertureon5th.com"
]
```
``` …
```
> Add cdngeneral.rentcafe.com to yellowlist

- src/data/yellowlist.txt
Fixes #1917.
See https://www.intercom.com/help/pricing-privacy-and-terms/intercom-messenger-cookies and the following quote from our communications with an Intercom representative:
>We do not expose cookie data to our contractees and are working towards adopting DNT.
>
>The "_mkra_ctxt" cookie is not used for tracking, we use it to segment database requests. Based on your concerns we'll disable the makara cookie from next week.  We believe improved aurora performance will mean we don't need to rely on it anymore.
> Add intercom.io to yellowlist

- src/data/yellowlist.txt
> ... the domain `applet.danid.dk` is not a tracker, but the universal government login system in Denmark called NemID. The reason I write to you is because when you enable Privacy Badger and you're not aware of it later on, it can get frustrating to find out what was blocking access to ones online bank, government mail and so on.
Error report counts by page domain and exact blocked `danid.dk` subdomain:
```
+-----------------------------------+----------------------------+-------+
| fqdn                              | blocked_fqdn               | count |
+-----------------------------------+----------------------------+-------+
| nemlog-in.dk                      | applet.danid.dk            |    48 |
| www.nemadgang.dk                  | applet.danid.dk            |    31 |
| …
```
> Add danid.dk to yellowlist

- src/js/firstparties/google-search.js
- src/js/firstparties/google-static.js
When cleaning links, don't remove 'about', 'class', or 'aria-*' attributes. Fixes #2181.
> Fix issues with google link unwrapping

- src/skin/options-layout.css
- src/skin/options.html
Fixes #2166 
I went through all options pages, and made adjustments so that they display better on small screens. Here are some screenshots with my modifications:
> Options page layout fixes for small screens

- src/data/yellowlist.txt
Twisto.cz is payment method like a Klarna, privacybadger currently block the JavaScript and completely break the payment functionality
> add www.twisto.cz to yellowlist

- tests/selenium/dnt_test.py
- tests/selenium/fingerprinting_test.py
- tests/selenium/super_cookie_test.py
> RawGit is now in a sunset phase and will soon shut down. It's been a fun five years, but all things must end.
> 
> GitHub repositories that served content through RawGit within the last month will continue to be served until at least October of 2019. URLs for other repositories are no longer being served.
> 
> If you're currently using RawGit, please stop using it as soon as you can.
-- https://rawgit.com/
> Migrate off Rawgit

- src/data/socialwidgets.json
Fixes #2206.
As the AddThis widget we mean to replace contains one or more child anchor elements.
The ":has()" selector would be better but it's not yet supported.
> Make AddThis selector exclude empty divs

- src/js/multiDomainFirstParties.js
Follows up on #573.
Error report counts by page domain and exact blocked ".bbc" subdomain:
```
+-------------------------+-------------------------+-------+
| fqdn                    | blocked_fqdn            | count |
+-------------------------+-------------------------+-------+
| www.bbc.com             | static.bbci.co.uk       |    48 |
| www.bbc.com             | ichef.bbci.co.uk        |    39 |
| www.bbc.com             | mybbc.files.bbci.co.uk  |    25 |
| www.bbc.com             | nav.files.bbci.co.uk    |    25 |
| www.bbc.com             | ichef-1.bbci.co.uk      |    19 |
| www.bbc.co.uk           | ichef.bbci.co.uk        |    17 |
| www.bbc.co.uk           | static.bbci.co.uk       |    17 |
| www.bbc.co.uk           | nav.files.bbci.co.uk    |    12 |
| www.bbc.co.uk …
```
> Add BBC domains to MDFP list

- src/js/multiDomainFirstParties.js
Fixes #2213.
Error report counts by date, page domain and exact blocked "mtv.fi" subdomain:
```
+---------+----------------+-------------------+-------+
| ym      | blocked_fqdn   | fqdn              | count |
+---------+----------------+-------------------+-------+
| 2018-11 | im.mtv.fi      | www.mtvuutiset.fi |    13 |
| 2018-11 | st.mtv.fi      | www.mtvuutiset.fi |    13 |
| 2018-11 | admp-tc.mtv.fi | www.mtvuutiset.fi |     5 |
| 2018-11 | extra.mtv.fi   | www.mtvuutiset.fi |     2 |
| 2018-11 | st.mtv.fi      | www.cmore.fi      |     1 |
| 2018-10 | im.mtv.fi      | www.mtvuutiset.fi |     3 |
| 2018-10 | admp-tc.mtv.fi | www.mtvuutiset.fi |     2 |
| 2018-10 | st.mtv.fi      | www.mtvuutiset.fi |     2 |
| 2018-10 | st.mtv.fi      | www.cmore.fi      |     1 |
| 2018-05 | …
```
> Add MTV Oy and C More domains to MDFP

- src/data/yellowlist.txt
Fixes #2209.
Error report counts by date, page domain and exact blocked "squareup.com" subdomain:
```
+---------+--------------------------+-----------------------------+-------+
| ym      | blocked_fqdn             | fqdn                        | count |
+---------+--------------------------+-----------------------------+-------+
| 2018-09 | api.squareup.com         | www.trycaviar.com           |     1 |
| 2018-09 | js.squareup.com          | www.trycaviar.com           |     1 |
| 2018-09 | pci-connect.squareup.com | www.trycaviar.com           |     1 |
| 2018-08 | api.squareup.com         | www.studio51-50.com         |     1 |
| 2018-08 | squareup.com             | www.studio51-50.com         |     1 |
| 2018-06 | js.squareup.com          | secure.acuityscheduling.com |     1 |
| …
```
> Add squareup.com to yellowlist

- src/js/multiDomainFirstParties.js
Lots of reports, not clear how to reproduce, easy fix though.
Error report counts by page domain and exact blocked "s-nbcnews.com" subdomain:
```
+----------------------------+------------------------+-------+
| fqdn                       | blocked_fqdn           | count |
+----------------------------+------------------------+-------+
| www.nbcnews.com            | media1.s-nbcnews.com   |    50 |
| www.nbcnews.com            | media2.s-nbcnews.com   |    49 |
| www.msnbc.com              | media1.s-nbcnews.com   |    44 |
| www.nbcnews.com            | media4.s-nbcnews.com   |    44 |
| www.nbcnews.com            | media3.s-nbcnews.com   |    43 |
| www.msnbc.com              | media2.s-nbcnews.com   |    40 |
| www.today.com              | media1.s-nbcnews.com   |    14 |
| …
```
> Update MDFP list for NBC News

- src/js/contentscripts/clobbercookie.js
- src/js/contentscripts/clobberlocalstorage.js
- src/js/contentscripts/dnt.js
- src/js/contentscripts/fingerprinting.js
- src/js/contentscripts/supercookie.js
- src/js/contentscripts/utils.js
- src/js/webrequest.js
- src/manifest.json
- tests/selenium/clobbering_test.py
- tests/selenium/pbtest.py
- tests/selenium/surrogates_test.py
> Improve localStorage clobbering

- src/data/yellowlist.txt
Error report counts by date and exact blocked "amazonpay" subdomain:
```
+---------+-----------------------+-------+
| ym      | blocked_fqdn          | count |
+---------+-----------------------+-------+
| 2018-12 | coin.amazonpay.com    |    10 |
| 2018-12 | coin-eu.amazonpay.com |     2 |
| 2018-11 | coin.amazonpay.com    |    36 |
| 2018-11 | coin-eu.amazonpay.com |     3 |
| 2018-10 | coin.amazonpay.com    |    27 |
| 2018-09 | coin.amazonpay.com    |    19 |
| 2018-08 | coin.amazonpay.com    |    16 |
| 2018-07 | coin.amazonpay.com    |     7 |
+---------+-----------------------+-------+
```
It's on our pre-trained list ... https://github.com/EFForg/privacybadger/blob/master/src/data/seed.json#L7894-L7898
Will add to the MDFP for Amazon next. [Edit: #2239]
I don't know if …
> Add two amazonpay.com domains to yellowlist

- src/js/multiDomainFirstParties.js
As its snitch map entry in the current pre-trained list is entirely other Amazon domains: https://github.com/EFForg/privacybadger/blob/master/src/data/seed.json#L7894-L7898
> Add amazonpay.com to Amazon's MDFP

- src/data/surrogates.js
Fixes dynamic image loading on https://www.motorcyclenews.com/.
Did you know Firefox's Network Inspector doesn't show cancelled requests? Crazy!
> Add sb subdomain to Comscore surrogate

- src/js/popup.js
Including when there are sliders for other third-party domains.
Fixes #2268.
> Always show "no trackers" in the popup when there are no trackers

- src/data/yellowlist.txt
Seems to power GDPR consent forms.
Blocking it breaks article links on https://www.bristolpost.co.uk/news/.
> Add consensu.org to yellowlist

- src/js/multiDomainFirstParties.js
Fixes #1366. Not clear how to reproduce blocking, but I do see some reports:
Error report counts by date, page domain and exact blocked "vinted" subdomain:
```
+---------+--------------------------+-----------------------+-------+
| ym      | blocked_fqdn             | fqdn                  | count |
+---------+--------------------------+-----------------------+-------+
| 2018-07 | vinted-de-d.openx.net    | www.kleiderkreisel.de |     2 |
| 2017-08 | images.vinted.net        | www.mamikreisel.de    |     1 |
| 2017-08 | s20-de-babies.vinted.net | www.mamikreisel.de    |     1 |
| 2017-08 | s21-de-babies.vinted.net | www.mamikreisel.de    |     1 |
| 2017-08 | s22-de-babies.vinted.net | www.mamikreisel.de    |     1 |
| 2017-04 | s21-uk.vinted.net        | www.vinted.co.uk      |     1 | …
```
> Add Vinted domains to MDFP list

- src/data/yellowlist.txt
Fixes #1497.
Not clear how to reproduce, but we get a lot of reports:
Error report counts by date, page domain and exact blocked "bigcommerce" subdomain:
```
+---------+--------------------------------+----------------------------------------------+-------+
| ym      | blocked_fqdn                   | fqdn                                         | count |
+---------+--------------------------------+----------------------------------------------+-------+
| 2019-01 | cdn1.bigcommerce.com           | www.carbideprocessors.com                    |     1 |
| 2019-01 | cdn1.bigcommerce.com           | www.innermountainoutfitters.com              |     1 |
| 2019-01 | cdn10.bigcommerce.com          | www.carbideprocessors.com                    |     1 |
| 2019-01 | cdn10.bigcommerce.com …
```
> Add bigcommerce.com to yellowlist

- src/data/yellowlist.txt
Fixes #2108.
Error report counts by date, page domain and exact blocked "epoq.de" subdomain:
```
+---------+--------------------------+--------------------------+-------+
| ym      | blocked_fqdn             | fqdn                     | count |
+---------+--------------------------+--------------------------+-------+
| 2019-02 | rs.epoq.de               | www.notebooksbilliger.de |     1 |
| 2019-02 | search.epoq.de           | www.notebooksbilliger.de |     1 |
| 2019-02 | search.epoq.de           | www.villeroy-boch.de     |     1 |
| 2019-02 | searchstandby.epoq.de    | www.notebooksbilliger.de |     1 |
| 2019-02 | searchstandby.epoq.de    | www.villeroy-boch.de     |     1 |
| 2019-02 | vub-tk-de-de.arc.epoq.de | www.villeroy-boch.de     |     1 |
| 2018-11 | cdn.epoq.de …
```
> Add epoq.de to yellowlist

- src/js/multiDomainFirstParties.js
Error report counts by date, page domain and exact blocked "woopic" subdomain:
```
+---------+-----------------------------------------+--------------------------+-------+
| ym      | blocked_fqdn                            | fqdn                     | count |
+---------+-----------------------------------------+--------------------------+-------+
| 2019-02 | c.woopic.com                            | www.sosh.fr              |     1 |
| 2019-02 | cdn.woopic.com                          | www.sosh.fr              |     1 |
| 2019-02 | mp.woopic.com                           | www.sosh.fr              |     1 |
| 2019-01 | c.woopic.com                            | www.orange.fr            |     2 |
| 2019-01 | hp5.a.woopic.com                        | www.orange.fr            |     2 |
| …
```
> Add a few Orange S.A. domains to MDFP list

- src/data/yellowlist.txt
Fixes #1440.
Let's see if yellowlisting will help.
> Add geetest.com to yellowlist

- src/data/yellowlist.txt
Fixes #1383.
Error report counts by date, page domain and exact blocked "editmysite" subdomain:
```
+---------+------------------------------+--------------------------------------+-------+
| ym      | blocked_fqdn                 | fqdn                                 | count |
+---------+------------------------------+--------------------------------------+-------+
| 2019-02 | cdn2.editmysite.com          | www.2bkmc.com                        |     1 |
| 2019-02 | cdn2.editmysite.com          | www.josiahsoils.com                  |     1 |
| 2019-02 | cdn2.editmysite.com          | www.kylespens.com                    |     1 |
| 2019-02 | cdn2.editmysite.com          | www.sfmanscaping.com                 |     1 |
| 2019-02 | cdn2.editmysite.com          | www.skinnykittyfarms.com …
```
> Add editmysite.com to yellowlist

- src/_locales/en_US/messages.json
- src/data/socialwidgets.json
- src/js/background.js
- src/js/contentscripts/socialwidgets.js
- src/js/options.js
- src/js/socialwidgetloader.js
- src/js/webrequest.js
- src/skin/options.html
Before:
After:
No longer relying on the icon alone to convey meaning:
- Should make it more clear that the widgets are interactive. Some of the error reports just say that Privacy Badger replaced or blocked Vimeo, which suggests some users don't know what to do with the replacement.
- Improves accessibility (meaningful text, responds to <kbd>Tab</kbd> and <kbd>Enter</kbd>).
- Provides a workaround in cases like https://www.kontakthub.com/product/Resona/ where the page's CSP disallows our data URI-based icon.
Specifying minimum dimensions fixes cases like https://write.as/jesusinbooks/what-utterly-destroy-actually-means-in-the-old-testament and https://www.sophos.com/en-us/products/intercept-x.aspx / https://turo.com/c/garyg593 (click the "Play Video" button)
Having all widgets of the same …
> Replacement widget improvements

- src/js/firstparties/facebook.js
Closes #2214. In order to keep the feature broken by #2214, we need to avoid overriding the click handler on images. I think the modification to the selector should be enough, and I haven't found any false positives that it matches yet.
> Ignore messenger images when instrumenting Facebook links.

- src/data/yellowlist.txt
Getting lots of reports that blocking `smartlock.google.com` breaks www.redfin.com.
> Site no longer functions when the smartlock.google.com tracker is completely blocked. When it's set to the no cookies setting, it works again.
Report counts where "smartlock.google.com" was blocked/user-allowed/user-cookieblocked grouped by site and month (partial data for 2019-02):
```
+---------+-------------------------------+-------+
| ym      | fqdn                          | count |
+---------+-------------------------------+-------+
| 2019-02 | www.redfin.com                |    33 |
| 2019-02 | id.atlassian.com              |     2 |
| 2019-02 | www.pinterest.co.uk           |     1 |
| 2019-02 | www.nerdwallet.com            |     1 |
| 2019-02 | www.paypal.com                |     1 |
| 2019-02 …
```
> Add smartlock.google.com to yellowlist

- src/data/yellowlist.txt
Fixes #1383. Follows up on #2303.
Seems to be yet another case of getting first-party GA cookies and then seeing them in third-party contexts (#367).
> Add weebly.com to yellowlist

- src/data/yellowlist.txt
Fixes #2169. Related to #2238. Yellowlisting may not actually fix the payment flow, but let's see.
> Add payments-amazon.com to yellowlist

- src/js/multiDomainFirstParties.js
Fixed linting, and removed mediacommons.org because we have yet to see an issues with Privacy Badger and Media Commons. This PR replaces #2333.
> Add NYU domains to MDFP list

- src/js/multiDomainFirstParties.js
Added ehi.com and other Enterprise Holdings domains to the MDFP list,
based on CSAN domains from www.nationalcar.com. Closes #2330.
> Update Enterprise Holdings MDFP list

- src/js/multiDomainFirstParties.js
Adding vsassets.io and vsallin.net (from CSAN list) to fix breakage on Visual Studio Marketplace. 
Closes #2347.
> add Visual Studio domains to Microsoft MDFP list

- src/js/multiDomainFirstParties.js
Privacy Badger was blocking `phab.wmfusercontent.org`, which was making the website at `phabricator.wikimedia.org` render without the appropriate styling.
```
**** ACTION_MAP for wmfusercontent.org
phab.wmfusercontent.org {
"dnt": false,
"nextUpdateTime": 1555600002198
}
wmfusercontent.org {
"dnt": false,
}
**** SNITCH_MAP for wmfusercontent.org
wmfusercontent.org [
"wikimedia.org",
"stackexchange.com",
"wikipedia.org"
]
> Add wmfusercontent.org to Wikimedia MDFP

- src/data/yellowlist.txt
Privacy Badger sees tracking from "ss.id" localStorage UUIDs (?); the localStorage seems to belong to `https://statcollector.sidearmsports.com/services/pixel.html?page_template=home&sport_name=0&sport_name_custom=0&site=umichigan&cbs_site_code=mich&content_id=null&sect=frontpage&sid=...` frames.
Error report counts by date, page domain and exact blocked "sidearmsports" subdomain:
```
+---------+---------------------------------+-----------------------+-------+
| ym      | blocked_fqdn                    | fqdn                  | count |
+---------+---------------------------------+-----------------------+-------+
| 2019-05 | fonts.sidearmsports.com         | mgoblue.com           |     1 |
| 2019-05 | fonts.sidearmsports.com         | umterps.com           |     1 |
| 2019-05 | …
```
> Add sidearmsports.com to yellowlist

- src/data/yellowlist.txt
Fixes #2332.
Leaving `secure5.arcot.com` removal for #1593.
> Add arcot.com to yellowlist

- src/_locales/en_US/messages.json
- src/js/background.js
- src/js/migrations.js
- src/js/options.js
- src/js/popup.js
- src/js/webrequest.js
- src/skin/options-layout.css
- src/skin/options.html
- src/tests/tests/tabData.js
- tests/selenium/cookie_test.py
This hides the non-tracking domains section in the popup (screenshot below) to help with #2021.
This is meant to be low-hanging fruit to help users avoid breaking the Web for themselves. Top user-blocked domains like `ajax.googleapis.com`, `cdnjs.cloudflare.com` and `maxcdn.bootstrapcdn.com` are almost certainly non-tracking and break much of the Web when blocked.
Users (Privacy Badger developers ...) who wish to continue to see all third-party domains in the popup can enable the new "Show domains that don't appear to be tracking you setting" setting (the name is meant to mirror existing non-tracking domains section header text in the popup):
> Hide non-tracking domains by default

- src/data/yellowlist.txt
Examples:
- https://hotels.ctrip.com/hotel/shanghai2/map
- https://bw.bilibili.com/2018/index.html#/
- https://sz.zu.anjuke.com/ditu/?from=58_zf_list_top_wzl
- http://www.monph.com/maplist/
Error report counts by date and exact blocked "api.map.baidu.com" subdomain:
```
+---------+--------------------+-------+
| ym      | blocked_fqdn       | count |
+---------+--------------------+-------+
| 2019-03 | api.map.baidu.com  |     1 |
| 2019-03 | sapi.map.baidu.com |     1 |
| 2018-11 | api.map.baidu.com  |     1 |
| 2018-10 | api.map.baidu.com  |     2 |
| 2018-08 | api.map.baidu.com  |     1 |
| 2018-07 | api.map.baidu.com  |     3 |
| 2018-07 | sapi.map.baidu.com |     3 |
| 2018-06 | api.map.baidu.com  |     2 |
| 2018-05 | api.map.baidu.com  |     2 |
| 2018-04 | api.map.baidu.com  | …
```
> Add api.map.baidu.com to yellowlist

- src/js/storage.js
Fixes https://github.com/EFForg/privacybadger/issues/2156 by ignoring Firefox error messages relevant to IndexedDB. 
I filed an issue in Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1555491
Here are the Firefox errors we’ve seen so far:
* `InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.`
* `AbortError: A request was aborted, for example through a call to IDBTransaction.abort.`
> ignores error messages related to Firefox IndexedDB issues

- src/js/multiDomainFirstParties.js
Was looking for quick fixes for our upcoming release by examining the top site domains in error reports over the last few months; `id.atlassian.com` was high up in the list and looks like a quick fix.
(To answer whether we have any first-party domains blocked on the primary affected site:)
Error report counts for the 'atlassian.com' site domain grouped by exact blocked subdomain:
```
+------------------------------------+-----------------------------------------------------------------+-------+
| fqdn                               | blocked_fqdn                                                    | count |
+------------------------------------+-----------------------------------------------------------------+-------+
| id.atlassian.com                   | aid-frontend.prod.atl-paas.net …
```
> Add atl-paas.net to Atlassian's MDFP domain list

- src/js/multiDomainFirstParties.js
Some assets on the CB2 site are loaded from the crateandbarrel.com domain and are getting blocked. CB2 is a brand of Crate and Barrel.
> Add Crate and Barrel domains to MDFP list

- src/data/yellowlist.txt
Seems to break all sorts of store functionality (on `www.lowes.com`, `www.monoprice.com`, ...) across the Web.
- [EasyList whitelists it across a range of websites](https://github.com/easylist/easylist/blob/56f94f4ea68861d408c5eeafc8df8703d0d1b57b/easyprivacy/easyprivacy_whitelist.txt#L37).
- [whotracks.me (Ghostery) entry for `adobedtm.com`](https://whotracks.me/trackers/adobe_dynamic_tag_management.html)
Examples:
- Store selector buttons on https://www.lowes.com/store/
- Adding products to cart on https://www.monoprice.com/
- Loading https://shop.pbs.org/product/NOVA6338
Error report counts by date and exact blocked "assets.adobedtm.com" subdomain:
```
+---------+---------------------+-------+
| ym      | blocked_fqdn        | count |
+---------+---------------------+-------+
| 2019-06 …
```
> Add assets.adobedtm.com to yellowlist

- src/data/yellowlist.txt
Used for [various bits of shopping functionality](https://www.turntonetworks.com/).
Please see error reports for specific examples of pages and breakages.
Error report counts by date, page domain and exact blocked "turnto" subdomain:
```
+---------+-----------------------+-------------------------------+-------+
| ym      | blocked_fqdn          | fqdn                          | count |
+---------+-----------------------+-------------------------------+-------+
| 2019-06 | static.www.turnto.com | palmettostatearmory.com       |     1 |
| 2019-06 | static.www.turnto.com | www.monoprice.com             |     1 |
| 2019-06 | static.www.turnto.com | www.nike.com                  |     1 |
| 2019-06 | www.turnto.com        | palmettostatearmory.com       |     1 |
| 2019-06 | www.turnto.com …
```
> Add turnto.com to yellowlist

- src/data/yellowlist.txt
Follows up on #2382.
Examples:
- https://xoofx.com/blog/2019/03/28/behind-the-burst-compiler/
- https://www.shadesguide.com/index.html
- https://portfoliocharts.com/portfolio/portfolio-finder/
> Add onedrive.live.com to yellowlist

- src/data/yellowlist.txt
This PR yellowlists verify.monzo.com and fixes #2175 
Unfortunately we don't have the debug information as the issue was appearing in our customer's browsers. We couldn't reproduce it ourselves.
> Add verify.monzo.com to the yellowlist

- src/data/yellowlist.txt
Error report counts by date, page domain and exact blocked "pwc.chase.com" subdomain:
```
+---------+-----------------------+-------------------------+-------+
| ym      | blocked_fqdn          | fqdn                    | count |
+---------+-----------------------+-------------------------+-------+
| 2019-06 | pwc.chase.com         | www.atomtickets.com     |     1 |
| 2019-03 | pwc.chase.com         | www.atomtickets.com     |     1 |
| 2019-02 | pwc.chase.com         | www.united.com          |     5 |
| 2019-01 | pwc.chase.com         | www.united.com          |     8 |
..
```
> Add pwc.chase.com to yellowlist

- src/data/yellowlist.txt
Please see error reports for examples.
Error report counts by date and exact blocked "salesforceliveagent" subdomain:
```
+---------+------------------------------------------+-------+
| ym      | blocked_fqdn                             | count |
+---------+------------------------------------------+-------+
| 2019-06 | c.la3-c1-phx.salesforceliveagent.com     |     4 |
| 2019-06 | d.la1-c2-frf.salesforceliveagent.com     |     4 |
| 2019-06 | d.la4-c2-dfw.salesforceliveagent.com     |     4 |
| 2019-06 | c.la1-c1-lon.salesforceliveagent.com     |     3 |
| 2019-06 | d.la1-c1-lon.salesforceliveagent.com     |     3 |
| 2019-06 | d.la1-c2-dfw.salesforceliveagent.com     |     3 |
| 2019-06 | c.la2-c1-phx.salesforceliveagent.com     |     2 |
| 2019-06 | c.la2w1.salesforceliveagent.com …
```
> Add salesforceliveagent.com to yellowlist

- src/js/multiDomainFirstParties.js
Error report counts by page domain and exact blocked "ffx.io" subdomain:
```
+--------------------------+---------------------+-------+
| fqdn                     | blocked_fqdn        | count |
+--------------------------+---------------------+-------+
| www.smh.com.au           | api.ffx.io          |   159 |
| www.smh.com.au           | static.ffx.io       |   149 |
| www.smh.com.au           | l.ffx.io            |   132 |
| www.smh.com.au           | i.ffx.io            |   127 |
| www.theage.com.au        | api.ffx.io          |   115 |
| www.theage.com.au        | static.ffx.io       |   111 |
| www.theage.com.au        | l.ffx.io            |    96 |
| www.theage.com.au        | i.ffx.io            |    71 |
| www.brisbanetimes.com.au | static.ffx.io       |    32 |
| …
```
> Add Nine Entertainment Co. news domains to MDFP

- src/data/yellowlist.txt
Blocking `dsw.tt.omtrdc.net` is responsible for breaking product pages on `www.dsw.com`. Please see error reports for more information.
Previously: #565, #873.
> Add dsw.tt.omtrdc.net to yellowlist

- src/js/options.js
This fixes a [warning from lgtm](https://lgtm.com/projects/g/EFForg/privacybadger/snapshot/7c5e2ead339e92d4700858d308977e6cb9212cb8/files/src/js/options.js?sort=name&dir=ASC&mode=heatmap).
> Removed Repeated Colon from RegEx

- src/js/background.js
- src/js/heuristicblocking.js
Fixes #2426.
Tested learning to block `google-analytics.com` in Chrome, and then both with and without first-party isolation in Firefox 58 and also Firefox 69 (beta). Reviewed background console for any related exceptions.
> Fix cookie sharing detection in Firefox when first-party isolation is enabled

- src/data/yellowlist.txt
Following #2434, to unbreak some sites of blizzard.cn, such as:
- http://hs.blizzard.cn/
- http://heroes.blizzard.cn/
Domains blocked on the above pages and their functions based on guessing:
- nosdn.127.net // NetEase Object Storage Delivery Network
- bnet.163.com // NetEase's domain for BattleNet (China) related assets
- nos.netease.com // NetEase Object Storage
- gad.netease.com // NetEase's game advertisement related assets (seemingly unrelated to normal functions; see also its unprotected internal document [here](http://res.nie.netease.com/comm/doc/tools/%E6%B8%A0%E9%81%93%E9%A1%B5%E5%8A%9F%E8%83%BD%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.html) shown me by Google)
- hubble.netease.com // NetEase's big data collector (suspected tracker) 
- res.wx.qq.com // Tencent's WeChat-related assets …
> Add some of NetEase's CDN domains to yellowlist

- src/data/yellowlist.txt
Error report counts by date, page domain and exact blocked "ehc.com" subdomain:
```
+---------+-------------------------------+---------------------------+-------+
| ym      | blocked_fqdn                  | fqdn                      | count |
+---------+-------------------------------+---------------------------+-------+
| 2019-08 | core.secure.ehc.com           | hcahealthcare.com         |     1 |
| 2019-07 | core.secure.ehc.com           | fwbmc.com                 |     1 |
| 2019-07 | core.secure.ehc.com           | hcahealthcare.com         |     1 |
| 2019-07 | core.secure.ehc.com           | stdavids.com              |     1 |
| 2019-07 | core.secure.ehc.com           | tristarsouthernhills.com  |     1 |
| 2019-07 | web-q-hospital.secure.ehc.com | fwbmc.com                 | …
```
> Add ehc.com to yellowlist

- src/data/yellowlist.txt
Fixes #2440.
Error report counts by date, page domain and exact blocked "hometogo" subdomain:
```
+---------+------------------+------------------+-------+
| ym      | blocked_fqdn     | fqdn             | count |
+---------+------------------+------------------+-------+
| 2019-07 | cdn.hometogo.net | www.hometogo.com |     1 |
| 2019-07 | cdn.hometogo.net | www.hometogo.de  |     1 |
| 2019-07 | cdn.hometogo.net | www.wimdu.nl     |     1 |
| 2019-07 | tc.hometogo.net  | www.hometogo.com |     1 |
| 2019-07 | tc.hometogo.net  | www.hometogo.de  |     1 |
| 2019-07 | tc.hometogo.net  | www.wimdu.nl     |     1 |
| 2019-05 | cdn.hometogo.net | www.wimdu.es     |     1 |
| 2019-05 | tc.hometogo.net  | www.wimdu.es     |     1 |
...
```
> Add cdn.hometogo.net to yellowlist

- src/js/multiDomainFirstParties.js
...because it is a TV channel owned by kurier.at and uses `apa.at` servers for its videos:
- `kf-kurier.sf.apa.at` (thumbnails)
- `uvp-kurier.sf.apa.at` (player)
- `kurier.sf.apa.at` (video)
hopefully it is ok, that i tried to "extend" #2342 and fix this myself?
or are their debug output still needed as in #2321?
> added schautv.at to "apa.at"

- src/data/surrogates.js
- src/data/yellowlist.txt
Fixes #2368.
Getting lots of reports across the Web where Gigya powers various forms including login forms (on `nfl.com`, etc.). Seems very frustrating for our users as you need to allow multiple Gigya domains to load.
> Add gigya.com to yellowlist

- src/_locales/en_US/messages.json
- src/js/background.js
- src/js/popup.js
- src/js/utils.js
- src/manifest.json
- src/skin/popup.css
- src/skin/popup.html
Before:
After:
Prompted by the following AMO review:
>Literally all I saw when I installed it and clicked on the toolbar icon was a pop-up was a badger's head and button to donate. The controls at the top (eg. settings) didn't give me any more info, even when I selected absolutely everything. So it's worth nothing to me... uninstalled it.
Follows up on #1737.
> Add helpful text to popup on special browser pages

- src/js/heuristicblocking.js
- src/js/webrequest.js
- src/manifest.json
Fixes #2423, fixes #2335, fixes #1144.
Use cases:
**Update**:  Listening to `webNavigation.onBeforeNavigate()` events instead of `onCommitted()` fixes this case as `onBeforeNavigate` callbacks seem to come before the initial Service Worker.
Does not do anything about #1997.
> Improve tab data bookkeeping with webNavigation

- doc/develop.md
Per recent discussions about naming conventions, I figured this is worth adding into the docs. Low hanging fruit, not what's currently reflected in the codebase, but worth adding as an aspirational note and for reference for future development.
> added naming convention section in develop docs

- src/js/storage.js
Fixes #2417 .
Since this is probably another Firefox IndexedDB storage error, for now going with a solution for Privacy Badger to ignore error messages that begin with this particular `QuotaExceededError` string. Next step is filing another bug with Mozilla, similar to [this one](https://bugzilla.mozilla.org/show_bug.cgi?id=1555491)
> ignore error messages beginning with QuotaExceededError

- src/data/yellowlist.txt
Fixes #2472, fixes #1218.
Dynamic Yield is used to power shopping all over the Web.
- All of [`dynamicyield.com` is classified as "essential" by Ghostery](https://whotracks.me/trackers/dynamic_yield.html).
- Disconnect blocks (and Firefox cookie-blocks) [just the two "px" subdomains](https://github.com/disconnectme/disconnect-tracking-protection/blob/b75f0d3bd94eb13d4180aff120dfbb86829b3219/services.json#L2650-L2657).
> Add a few Dynamic Yield domains to the yellowlist

- src/js/firstparties/google-search.js
- src/js/firstparties/google-static.js
By ignoring "style" attributes on links.
Previously: #2182.
> Fix Google search result image/video thumbnails

- src/_locales/en_US/messages.json
- tests/selenium/options_test.py
This removes the various versions of the "sliders let you control" text from popup and options pages, as we want to keep de-emphasizing slider use (#1675, https://github.com/EFForg/privacybadger/issues/1422#issuecomment-348229277). Might help with #2021. Follows up on #1804.
Should help with #1077/#1113/#2463 as there is now less text taking up space in the popup.
> Remove "sliders let you control" text

- .eslintrc.yml
- src/js/contentscripts/clobbercookie.js
- src/js/contentscripts/clobberlocalstorage.js
- src/js/contentscripts/dnt.js
- src/js/contentscripts/fingerprinting.js
- src/js/contentscripts/socialwidgets.js
- src/js/contentscripts/supercookie.js
- src/js/firstparties/facebook.js
- src/js/firstparties/google-search.js
- src/js/firstparties/google-static.js
- src/js/firstparties/twitter.js
- src/js/storage.js
- src/js/webrequest.js
- src/tests/tests/firstparties.js
This is a response to a [post on chromium-extensions](https://groups.google.com/a/chromium.org/d/msg/chromium-extensions/0ei-UCHNm34/lDaXwQhzBAAJ) that asks developers to protect their extensions against compromised renderer processes.
The ~~two~~three significant changes:
- There is now a whitelist of known and allowed content script messages. This makes a distinction between "privileged" messages that come from extension pages like the popup, and "unprivileged" messages that come from content scripts.
- All messages are now expected to contain a `type` property, which is a string containing the name of the message. If all messages use `type`, a compromised content script won't be able to trigger a privileged message handler that happens to come before an unprivileged message handler in …
> Enumerate permitted content script messages

- src/js/multiDomainFirstParties.js
We've received reports from players visiting the page for our newly announced game, playruneterra.com, that Privacy Badger is flagging our beta sign-up flow as cross-site tracking.
This adds MDFP rules for Riot Games domains.
> Add Riot Games domains

- src/data/socialwidgets.json
- src/js/webrequest.js
Fixes #788, fixes #1860. Related to #2266.
Widgets that have replacements should not have their domains on the yellowlist. The value of replacement widgets is full blocking (best privacy) combined with a clear way to restore potentially useful blocked content (convenience). Mixing yellowlisting and replacement widgets gets us less privacy w/o any benefit (as well as timing-related bugs).
This should be followed up by adding any missing widgets (Facebook Comments, Facebook Video, #1467) and removing Facebook, Twitter, etc. from the yellowlist (#1474, #1593) so that their widgets will work by default again.
~~As this changes `unblockDomains` in the widgets JSON, will need to fix them for any outstanding widget PRs (#2265, #2279, #2280).~~
> Stop replacing yellowlisted widgets

- src/js/multiDomainFirstParties.js
Currently, 'vgcontent.info' gets flagged as a potential tracker, and after visiting pages from the 3 other domains it gets blocked, thoroughly breaking the site.
> Added The Vanguard Group domains to MDFP

- src/data/socialwidgets.json
Fixes #2337.
In preparation for removing `www.youtube.com` from the yellowlist (#1593). (What other kinds of embeds is it required by?)
Should be useful right away though because users often intentionally block www.youtube.com (#2021).
Examples:
- https://www.mortenhansen.com/discover-passion-purpose/
- https://uncrate.com/video/beatles-rooftop-concert-50th-anniversary/ (requires `www.youtube.com` to be blocked to work)
- https://pamela-vosseller.squarespace.com/subscriber-love
- https://blog.frontiersin.org/2018/10/02/cellular-neuroscience-brain-neurons-memory/
- https://boingboing.net/2018/11/01/lose-yourself-in-a-new-track-f.html
- https://www.diyphotography.net/secret-filming-fast-moving-objects-25-million-frames-per-second-mirrors/
- https://itsfoss.com/linuxboot-uefi/
- …
> Add replacement widget for YouTube

- src/js/firstparties/facebook.js
Fixes #2214. Follows up on #2307.
Can't rely on classes like `_3m31` as I'm already seeing a different random class.
Are there any `l.php` links that have an ARIA label attribute that should still be cleaned but will now be ignored?
> Fix Messenger photos in non-English locales

- doc/DESIGN-AND-ROADMAP.md
- src/js/contentscripts/clobbercookie.js
- src/js/webrequest.js
- tests/selenium/clobbering_test.py
Instead of removing the referrers entirely. This should fix yellowlisted third-party content that gates itself behind a referrer check. Non-"GET" request referrers are still removed to reduce change scope (no known non-GET breakages, no known benefit).
Fixes #188, fixes #2305, fixes #2405, Vidible videos on various sites (no GH issue, lots of error reports though, [for example](https://www.aol.com/article/news/2019/11/05/diplomat-told-that-ukraine-aid-held-up-for-corruption-probe/23853842/)).
If this goes over well, we could try expanding origin-only referrers to all third-party requests (related to #855).
* [2018 Firefox breakage study](https://blog.mozilla.org/data/2018/01/26/improving-privacy-without-breaking-the-web/)
* [Referrer …
> Use origin-only referrers with cookieblocked requests

- src/_locales/en_US/messages.json
- src/js/options.js
- src/js/popup.js
- src/lib/options.js
- src/skin/options-layout.css
- src/skin/options.html
- src/skin/popup.css
- src/tests/tests/options.js
- tests/selenium/options_test.py
Fixes #2477, helps with #2021.
Helps with "how do I block all domains?" (https://github.com/EFForg/privacybadger/issues/1422#issuecomment-348229277, https://github.com/EFForg/privacybadger/issues/2248#issuecomment-448274011).
Follows up on #1804, #2359.
Popup (not-yet-blocked domains in own section):
Options (not-yet-blocked domains hidden by default):
> De-emphasize not-yet-blocked domains

- src/_locales/en_US/messages.json
- src/js/popup.js
- src/skin/popup.css
- src/skin/popup.html
Currently the popup on disabled pages has no clear messaging about what's going on on that page, as well as some messed up spacing with the footer options buttons. These changes add some clear messaging to the popup when the user is on a domain they've disabled PB for, in the style of the messaging that's displayed on special pages.
Here's what the popup currently looks like on disabled pages:
And here's what it looks like with these proposed changes:
> Add clear message in popup on disabled pages

- src/js/popup.js
- src/skin/popup.css
- src/skin/popup.html
Before:
After:
Follows up on #2510 and #2451.
> Improve display of "no trackers detected" in popup

- src/js/firstparties/facebook.js
Resolves: #2513
Updated wrapped link discovery (similar to [FacebookTrackingRemoval](https://github.com/mgziminsky/FacebookTrackingRemoval/commit/36eefd76a457864c580b8d63157b90c54f3935d2#diff-bd9c9dcd314f2d7df52935b3a6a4d504))
> Fix link cleaning on messenger.com

- src/js/utils.js
- src/tests/tests/heuristic.js
- src/tests/tests/utils.js
- tests/selenium/super_cookie_test.py
This fixes cookies that would otherwise be low entropy getting flagged solely due to SameSite being present.
> Add "samesite" to cookie attributes

- src/js/multiDomainFirstParties.js
Related to #1499
We've received reports from merchants/Shopify employees visiting different sections of our application that Privacy Badger blocks some domains we used.
I added the list of our domains used in the administration section of our app.
Let me know if you think I need to add those domains to the yellow list. Some of those domains are used inside an iFrame to load Shopify apps.
> Update MDFP list for Shopify

- src/js/background.js
- src/js/migrations.js
Fixes #1538, fixes #2530.
Follows up on 775ff3e69eb952e83b3da54cdfa2a851ed4cc7cf.
This migration gets all "__cfduid" cookies and collects their site (first-party) domains. It then goes through each tracking domain in `snitch_map` and throws away any site domain entries that are found in the "__cfduid" site domains list. It then rebuilds action and snitch maps.
Since we only seem to have site domains for the "__cfduid" cookies, we can't differentiate between Cloudflare and non-Cloudflare tracking domains, so this may end up removing non-Cloudflare tracking domains (that were seen on the same site domains as Cloudflare tracking domains). This should be OK as there shouldn't be too many, and Privacy Badgers will automatically relearn to block them.
> Add migration to forget __cfduid-linked domains

- src/js/migrations.js
This bug results in inadvertently removing pre-trained data for some new users.
Follows up on #2536. Related to #2438.
> Fix timing issue in Cloudflare migration

- src/js/contentscripts/dnt.js
- src/js/contentscripts/fingerprinting.js
> Preserve name and length when overwriting JavaScript methods

- src/js/options.js
Related to #2528. If the user is already protected against webrtc ip leakage, then the options page will reflect that. What it doesn't handle is notifying the user that they're protected via some other means than Privacy Badger (which can be misleading if they try to uncheck the box, not knowing it's controlled by some other extension or addon). Handling that would involve translations and may be beyond the scope of this pull request.
> Detects and displays on options page if user is already protected against webrtc ip leak

- src/js/background.js
- src/js/heuristicblocking.js
- src/js/migrations.js
- src/js/storage.js
Following up on https://github.com/EFForg/privacybadger/pull/2245#issuecomment-545545717
This is meant to be a medium-term solution to work around major site breakages (see error reports).
You can teach Privacy Badger to block `consensu.org` from scratch by visiting:
- https://www.buzzfeed.com/
- https://www.independent.co.uk/us
- http://www.spiegel.de/ (`consensu.org` only loads when you click the initial consent Accept button; you need to erase site data to see the consent again on subsequent loads)
The migration is to resolve breakages for existing Badger users. The short-circuit in `_recordPrevalence()` takes care of (seed) data imports.
> Ignore consensu.org (GDPR consent provider)

- src/js/multiDomainFirstParties.js
this is just an additional domain resp. TLD which was missed at #2572.
> added the missing prosiebenmaxx.at

- src/js/storage.js
- src/tests/tests/storage.js
Now that we increased the number of sites visited during pretraining to 5,000, unpacked seed data size grew past a MB. (Packaged CRX size doesn't seem much affected thanks to compression.)
We can significantly reduce unpacked seed data size by dropping unnecessary properties. We don't need to store `userAction` as it is always unset. We also don't need to store `dnt`~~/`nextUpdateTime`~~ unless an EFF DNT policy was found.
This PR is to support loading such [streamlined seed data](https://github.com/EFForg/badger-sett/commit/4fc72609d7959dfd0fb5ba747f98a2088e98fd93).
> Support loading streamlined seed data

- src/js/contentscripts/socialwidgets.js
- src/js/webrequest.js
- src/lib/i18n.js
This adds RTL support to the "rich" replacement widget (some examples in #2262).
Before:
After:
Unfortunately, we can't simply set the text direction for the HTML title attribute we use to provide our tooltip for social button replacements ([ShareMeNot test page](https://sharemenot.cs.washington.edu/Test%20Installation.shtml)). RTL locale (`ar`, `he`, `fa`) translators can work around this bug for now by manually adjusting text order.
> Add RTL locale support to replacement widgets

- src/data/socialwidgets.json
- src/js/webrequest.js
Instead of hypothetically blocked (which doesn't account for page context, for instance).
Fixes pointless first-party replacement ([for example](https://soundcloud.com/pages/embed)).
Should follow #2267.
> Only replace widgets that were actually blocked

- src/js/heuristicblocking.js
- src/js/storage.js
Low-hanging fruit mitigation for #2548.
The downside of only checking DNT policies after we start blocking a domain is that we will break DNT-compliant domain resources after we first learn to block them, at least on the initial page load.
If this becomes a persistent issue, we should integrate our [DNT preload list](https://www.eff.org/files/effdntlist.txt) into Privacy Badger, and make it easy for compliant sites to get on the list (#1124).
> Do not check DNT policies while still learning to block

- src/lib/i18n.js
- src/skin/popup.css
Domain list headers before:
Domain list headers after:
Intro page headers/paragraphs before:
Intro page headers/paragraphs after:
As far as remaining known RTL locale bugs, all popup/options page tooltips in Firefox display incorrectly for RTL locales. This will be fixed when we restore custom tooltips to Firefox (#1814).
Follows up on #2592.
> More right-to-left (RTL) locale fixes

- src/js/multiDomainFirstParties.js
Discord has recently moved its parts of its website from `discordapp.com` to `discord.com`.
We've received reports that our CDN (which remains at `cdn.discordapp.com`), among other things, may be blocked by Privacy Badger on `discord.com`. (https://www.reddit.com/r/discordapp/comments/gdhc83/discord_has_changed_its_domain_to_discordcom/fpherje?utm_source=share&utm_medium=web2x)
Let me know if you need to change something else as well.
> Update MDFP list for Discord

- src/data/socialwidgets.json
- src/js/contentscripts/socialwidgets.js
- src/js/socialwidgetloader.js
- src/js/webrequest.js
- tests/selenium/clobbering_test.py
- tests/selenium/dnt_test.py
- tests/selenium/pbtest.py
- tests/selenium/popup_test.py
- tests/selenium/surrogates_test.py
- tests/selenium/widgets_test.py
Fixes #1542.
~~Should be rebased on #2484 to avoid replacing reCAPTCHA when it's only been cookieblocked. (Right now we ask, "would we block `google.com`?" and the answer is yes, but what we want to ask is, "did we block `google.com`?" (as opposed to `www.google.com`)~~
Parts borrowed from #2271. Should redo that PR from master after this is merged.
`www.google.com` reCAPTCHA examples (currently yellowlisted, so you have to tell your Privacy Badger to block `www.google.com` first):
- https://www.dailykos.com/users/signup
- https://2-harvest.org/contact/
- https://www.burpee.com/contactus
`google.com` reCAPTCHA examples:
- https://en.islcollective.com/create-an-account
- https://apps.nextcloud.com/signup/
Dynamically inserted (https://github.com/EFForg/privacybadger/pull/2512/commits/024fff …
> Add replacement widget for Google reCAPTCHA

- src/data/yellowlist.txt
- src/js/multiDomainFirstParties.js
The page immobilienscout24.de relys on static assets served by the
related static hosts. Because of this I would like to request adding
these domains to the yellowlist.
> Add immobilienscout24.de domains to MDFP

- src/skin/popup.css
I noticed that #2600 had a change originally proposed in the PR to make the trackers link change to the PB signature orange when hovered, but that change got lost in one of the later commits when the css selectors got changed. 
What do the badgers want? Orange tracker links. When do they want them? When the links are hovered.
> color change when hover on trackers link in popup

- src/_locales/en_US/messages.json
- src/js/contentscripts/socialwidgets.js
- src/js/webrequest.js
- tests/selenium/widgets_test.py
This updates the message used inside widget placeholders:
```diff
-Privacy Badger has replaced this $BUTTON$ button.
+Privacy Badger has replaced this $WIDGET$ widget
```
Where `$WIDGET$` is one of "Google reCAPTCHA", "SoundCloud", "Spotify Player", "Streamable Player", "Vimeo", "YouTube".
> Improve message used in widget placeholders

- src/js/multiDomainFirstParties.js
added domains of austrian channels from prosiebensat1.com as you can [see at wikipedia](https://en.wikipedia.org/wiki/ProSiebenSat.1_Media#Divisions), additionally to #2572 & #2573.
similar to #2570 `component.player.p7s1.io` & `config.player.p7s1.io` is needed for the player on...
- https://www.atv.at/livestream
- https://www.atv2.at/livestream
- https://news.puls24.at/
- https://www.puls4.com/live-551
> [MDFP] added domains of austrian channels from prosiebensat1.com

- src/data/socialwidgets.json
In preparation for removing `www.facebook.com` from the yellowlist (#1593). Should be useful right away though because users often intentionally block `www.facebook.com` (#2021).
Interestingly, does not fix the [broken page](https://insider.foxnews.com/amp/article/59322) in #1815 because that uses a different API (needs more investigation) for producing the video player.
Examples follow.
Facebook Video:
- https://petapixel.com/2018/11/30/tricks-food-photographers-use-to-make-food-look-delicious/
- https://videosift.com/video/This-is-why-women-love-him
- https://www.getup.org.au/campaigns/aboriginal-and-torres-strait-islander/origin-reportback/traditional-owners-stood-their-ground
- http://www.napolitoday.it/attualita/paolantoni-risposta-gottardo-zanzara.html
Facebook Comments:
- …
> Add Facebook Comments/Video, Twitch Player and YouTube (Privacy-Enhanced Mode) replacements

- src/data/socialwidgets.json
Fixes #2004.
Examples:
- https://444.hu/2018/12/18/a-belga-kormanyfo-beadja-a-lemondasat
- https://index.hu/belfold/2017/06/11/egy_csanadpalotai_no_kemenyen_kiosztotta_lazar_janost/ (lazy loading implementation, doesn't yet work); [another lazy loading example](https://vc.ru/marketing/29992-big-data-blokcheyn-mashinlening-sberbank-obygral-lyubov-grefa-k-trendam-v-reklame-studencheskoy-olimpiady) that doesn't work
- https://geektimes.com/post/300631/
- http://www.yaplakal.com/forum28/topic2009258.html
Follows up on #2262.
> Add replacement widget for Coub

- src/js/multiDomainFirstParties.js
Blocking of `gw.alipayobjects.com` prevents me from [searching on 1688.com](https://s.1688.com/). Based on the naming convention and the `Sub Alt Name` section of the [TLS cert](https://crt.sh/?id=2808014058) of [gw.alipayobjects.com](https://gw.alipayobjects.com/404.json), it is associated with Alipay and also used on some other websites of Alibaba.
Debugging output:
```
**** ACTION_MAP for alipayobjects.com
alipayobjects.com {
"dnt": false,
}
gw.alipayobjects.com {
"userAction": "user_cookieblock",
"dnt": false,
"nextUpdateTime": /* REDACTED */
}
a.alipayobjects.com {
"dnt": false,
"nextUpdateTime":  /* REDACTED */
}
i.alipayobjects.com {
"userAction": …
```
> Add alipayobjects.com to the MDFP list of Alibaba

- src/data/socialwidgets.json
- src/js/contentscripts/socialwidgets.js
- src/js/webrequest.js
This replaces the previous PR #2271 with one that's more up-to-date from master's current state.
> Disqus Comment Widget Replacement

- src/js/options.js
- src/js/popup.js
Fixes #1814.
Following up on https://github.com/EFForg/privacybadger/pull/2629#issuecomment-646095710.
> Re-enable Tooltipster tooltips on Firefox

- src/js/multiDomainFirstParties.js
The index page of [jdwl.com](https://www.jdwl.com/) (京东物流 or JD Logistics) is broken as it is referring to resources on jd.com.
JD Logistics is a subsidiary of JD.com. Their [CT logs](https://crt.sh/?q=jdwl.com) have no intersection, but the two
domains share the same authoritative DNS server (jdcache.com):
https://dns.google/resolve?name=jdwl.com&type=NS
https://dns.google/resolve?name=jd.com&type=NS
.
Debugging output for jdwl.com:
```
**** ACTION_MAP for jdwl.com
jdwl.com {
"dnt": false,
}
**** SNITCH_MAP for jdwl.com
jdwl.com [
"jd.com"
]
```
Debugging output for jd.com:
```
**** ACTION_MAP for jd.com
jd.com {
"dnt": false,
}
jkcsjd.com {
"userAction": …
```
> Update MDFP list for JD.com (jdwl.com)

- src/js/popup.js
- src/skin/popup.css
- src/skin/popup.html
- tests/selenium/popup_test.py
- tests/selenium/window_utils.py
Styled:
- "Submit Error" / "Cancel" buttons on the "Did Privacy Badger break this site?" (broken site report) overlay
- "Copy to clipboard" button on the Share overlay
Updated to inherit from standard Badger button styles:
- Welcome page link on the reminder overlay
- "Tell us" link on the critical error overlay
Overlay close links (in the upper right) are now keyboard-navigable:
- The SVG "X" on the new user welcome page reminder overlay
- The "[X] close" links on the Share/broken site report overlays
This does not fix keyboard navigation issues described in https://github.com/EFForg/privacybadger/pull/2629#issuecomment-646101693.
> Style remaining popup buttons

- src/skin/popup.html
Fixes #2624. Follows up on https://github.com/EFForg/privacybadger/pull/2627#issuecomment-654467536.
This PR changes the `href` of the help button in the popup to now direct the user to the FAQ page.
> help button in popup now links to FAQ page

- src/js/popup.js
- src/skin/popup.css
In recent conversation it was brought up that the popup UI could be improved on sites that Privacy Badger is disabled on. Specifically that the popup could better reflect the state of PB being "turned off."
There are a couple of proposed changes here. One is greying out just the color of the EFF logo when PB is turned off on a site:
And the other option greys out both the EFF logo and the little heart on the donate button:
I'm of no hard opinion either way, but figured I'd present both options here. What's not considered in either of these options is whether or not to also remove the hover effect that changes the border color on the buttons to orange. Is that worth adding as well?
@ghostwords @andresbase
> Improve disabled site popup ui

- src/js/multiDomainFirstParties.js
additional to #2615 added `zappn.tv`, because it is the streaming platform/app of the austrian "ProSiebenSat.1 PULS 4 GmbH" (as already somehow mentioned at https://github.com/EFForg/privacybadger/pull/2572#issuecomment-606556905).
e.g. https://zappn.tv/livestream/ loads the player from `p7s1.io`.
> [MDFP] added zappn.tv to the p7s1.io MDFP

- src/js/options.js
- src/skin/options-layout.css
- src/skin/options.html
- tests/selenium/options_test.py
Fixes #2422.
~~Ideally we would cancel in-progress rendering in response to anything that triggers a rerender (such as updating the search term), to remove the potential for rendering the second half of the list from the previous render mixed into the list from the current render. We could also disable things that cause a rerender (just the domains list filters?) while a render is in progress. But ... is this a problem in practice? Let's do some QA to find out.~~ A spinner is shown while domains are being rendered, to prevent partial renders.
This also disables fancy tooltips for the list for performance reasons. Perhaps we could restore them by adding them in a separate asynchronous chunked loop, one that doesn't cause the browser window to hang or add seconds (!!) in some cases to list …
> Render tracking domains list in chunks instead of on scroll

- src/js/multiDomainFirstParties.js
`codingcompetitions.withgoogle.com` needs to access cookies on `google.com` so that to sign in Google accounts.
> Add a new domain to the MDFP list for Google

- src/_locales/en_US/messages.json
- src/js/background.js
- src/js/options.js
- src/js/webrequest.js
- src/lib/i18n.js
- src/skin/options-layout.css
- src/skin/options.html
Fixes #740. 
It exposes an option in the UI for users to control the `alternateErrorPagesEnabled` and `hyperlinkAuditingEnabled` options that PB currently overrides.
> Expose privacy overrides in options

- src/data/yellowlist.txt
`maponline{0,1,2,3}.bdimg.com` hosts tile images of [Baidu Map](https://en.wikipedia.org/wiki/Baidu_Maps), which is an online map service like Google Maps.
Sample site: https://www.huodongxing.com/go/9560081822600#map.
Sample tile image: http://maponline2.bdimg.com/tile/?qt=vtile&x=3260&y=859&z=14&styles=pl&scaler=1.
Debugging output:
```
**** ACTION_MAP for bdimg.com
api0.map.bdimg.com {
"userAction": "user_cookieblock",
"dnt": false,
"nextUpdateTime": /* redacted */
}
bdimg.com {
"dnt": false,
}
maponline3.bdimg.com {
"dnt": false,
"nextUpdateTime": /* redacted */
}
maponline2.bdimg.com {
"userAction": "user_cookieblock",
"dnt": false,
"heuristicAction": …
```
> Add maponline{0,1,2,3}.bdimg.com to yellowlist

- src/js/multiDomainFirstParties.js
[Zaobao](https://en.wikipedia.org/wiki/Lianhe_Zaobao) is a Chinese newspaper published in Singapore. 
Zaobao.com.sg uses some assets hosted on project.zaobao.com which is blocked by the PB, resulting some images failing to load.
Debugging output:
```
**** ACTION_MAP for zaobao.com
www.zaobao.com {
"dnt": false,
}
zaobao.com {
"dnt": false,
}
www.zaobao.com.sg {
"dnt": false,
"nextUpdateTime": /* redacted */
}
zaobao.com.sg {
"dnt": false,
}
project.zaobao.com {
"dnt": false,
"nextUpdateTime": /* redacted */
} …
```
> Add Singapore Press Holdings domains to MDFP list

- src/_locales/en_US/messages.json
- src/js/contentscripts/dnt.js
- src/js/webrequest.js
- tests/selenium/dnt_test.py
This is a quick, simple implementation of sec-gpc, the upcoming do-not-sell-or-share standard for CCPA/nevada privacy/GDPR purposes. The signal looks an awful lot like DNT. 
With this PR, Sec-GPC will be sent whenever DNT is: the global checkbox in the options page that enabled DNT now enables both signals, and Privacy Badger will not send Sec-GPC to sites on the disabled list.
Like DNT, there are two ways the signal is conveyed: through a browser header ("Sec-GPC: 1"), and through a navigator property (`navigator.globalPrivacyControl = 1`). This PR sets GPC to 1 by default in both of those channels. Both are controlled by the `badger.sendDNTSignal` setting.
In the future, it might make sense to separate out DNT and GPC, but this is the simplest way I could think to implement. Most of the …
> Implement global privacy control

- src/js/multiDomainFirstParties.js
Following #2434 #2639.
According to the WHOIS record of `jdl.cn`
> Registrant: 北京京东乾石科技有限公司
> Registrant Contact Email: jdym@jd.com
> Registration Time: 2020-05-12 09:34:05
, it is a new domain of JD.com, for its subsidiary [JD logistics](https://google.com/search?q=JD+logistics). 
`jdl.cn` relies on many resources on `jd.com` and `360buyimage.com` and hence its [package tracking page](https://www.jdl.cn/order/search?waybillCodes=VC43228561891) is broken.
> Add jdl.cn to MDFP list for JD.com

- src/js/firstparties/google-search.js
- tests/selenium/google_test.py
- tests/selenium/pbtest.py
Fixes #2184 
Turns out that Google search results links are structured a bit differently in Firefox for Android, so they weren't getting unwrapped/deinstrumented properly. This change adds a couple of logical switches into the Google first party script we run so that links on Firefox Android get scrubbed and the href gets properly reassigned.
> Add Google Link Tracking Protection for Firefox Android

- src/js/background.js
- src/js/heuristicblocking.js
- src/js/migrations.js
As the proxying makes all proxied domains seem third-party.
Two pieces:
- A check that skips updating `snitch_map` for domains that end in `.id.opendns.com`.
- A migration to remove any existing `opendns.com` domains from the database
We could instead strip the `.id.opendns.com` postfix before anything else is done with a request/response domain. Simply ignoring OpenDNS domains seems good enough for now though.
> Ignore Cisco OpenDNS/Umbrella proxy domains

- src/_locales/en_US/messages.json
- src/js/contentscripts/socialwidgets.js
- src/js/webrequest.js
Fixes #2384 
This adds a link to the text that overlays on the widget replacement notification that users get. It provides a click through (new tab, no referer) link so that users can get to the embedded media directly without having to interact with it on the given frame.
Here's how it looks:
> Show Frame URL on Widget Replacement Divs

- src/js/contentscripts/dnt.js
- tests/selenium/dnt_test.py
Related discussion: https://github.com/globalprivacycontrol/gpc-spec/issues/11
> Tweaks to navigator.globalPrivacyControl

- src/js/background.js
- src/js/heuristicblocking.js
- src/tests/tests/background.js
From the [blog post](https://www.eff.org/deeplinks/2020/10/privacy-badger-changing-protect-you-better):
>... [I]n future updates to Privacy Badger we plan to replace [tracker lists of users with default settings] with new data compiled by Badger Sett. That means users who do not opt in to local learning will share the same block list and will continue receiving information about new trackers we discover, keeping their Badgers up-to-date.
This replacement should preserve user-customized sliders.
Follows up on #2679.
> Switch to latest tracker data on extension updates when local learning is disabled

- doc/permissions.md
- src/_locales/en_US/messages.json
- src/js/background.js
- src/js/options.js
- src/skin/options.html
Fixes #1897.
As per https://developer.chrome.com/docs/extensions/reference/privacy/, disables "pre-resolving DNS entries and preemptively opening TCP and SSL connections to servers". In Chrome, "only affects actions taken by Chrome's internal prediction service" and [unfortunately](https://bugs.chromium.org/p/chromium/issues/detail?id=785125) "does not affect webpage-initiated prefectches [sic] or preconnects."
See also: https://www.google.com/intl/en/chrome/privacy/whitepaper.html#netpredict
----
As far as remaining `chrome.privacy` settings, we may want to disable search suggestions (using `chrome.privacy.services.searchSuggestEnabled`) in the future. This would "prevent Chrome from using a prediction service to help complete web addresses or search terms, when users type in the address …
> Add privacy override to disable network prediction

- src/js/contentscripts/socialwidgets.js
- src/skin/popup.css
By using a ["system font stack"](https://systemfontstack.com/).
The font stack we use now is inconsistent across OS's. Take a look below: on one platform (in the default locale) a single word ("site") occupies a line all by itself, while the same button appears more balanced on other platforms.
:x: Chrome on macOS:
:x: Firefox on Windows (?):
:heavy_check_mark: Chrome on Ubuntu Linux:
:heavy_check_mark: Chrome on macOS:
:heavy_check_mark: Chrome on Ubuntu Linux:
> Fix inconsistent button font display

- src/skin/css/firstRun.css
- src/skin/options-layout.css
- src/skin/options.html
- src/skin/popup.css
This adds a dark theme for the popup, settings page and
first run page.
Fixes: #2630, closes #2648
A few elements, like on the light theme, aren't themed (e.g checkboxes) because they need `appearance: none` and to redo the widget. So I think we could if needed do this in a different patch. Any thought?
> add a dark theme

- src/_locales/en_US/messages.json
- src/js/background.js
- src/js/options.js
- src/js/webrequest.js
- src/lib/i18n.js
- src/skin/options-layout.css
- src/skin/options.html
- tests/selenium/widgets_test.py
Fixes #2705. Follows up on #2653.
This adds a section in the widgets tab of the options page where a user can manage which sites are always exempted from having widgets replaced on them. Aside from testing in the options page itself, I've been using this [soundcloud widget demo site](https://demo.mekshq.com/voice/?p=303) to add to the exempts list from an outside source.
Mostly this undoes the gripe that a few users have come forward with that they can't undo the "always allow" button on the widget replacement modal after it's been clicked on a page. From there, I figured I might as well add the capability to add sites to this list directly from the same section in the options page.
When a user exempts a site from the replacement modal, it adds the widget type as well as the domain to the …
> Expose sites exemption list for widget tab in options UI

- src/skin/popup.css
- Fixes the behavior in the dark mode where revert control arrows aren't visible.
- Invert the arrows when in dark mode with `filter: invert(100%)`
- Resolves #2738
> Fix dark control arrows

- src/_locales/en_US/messages.json
- src/js/background.js
- src/js/popup.js
- src/js/utils.js
- src/js/webrequest.js
- src/skin/popup.css
- src/skin/popup.html
- src/tests/tests/utils.js
- tests/selenium/popup_test.py
Fixes #2482.
Should help with #2021, and with the problem of users not noticing the "Disable for this site" button.
adds the following sections to the popup:
* firstparty notifications for when the current site has any unique firstparty protections protections scripts happening on it
* blocked resources container hidden by default behind the current ’n potential trackers blocked’ message
each of the sections have the option to drop down expand into a more detailed informational or control panel for each: 
* The firstparty section just drops down into a message that describes the type of protection that is taking place, and links to reading more about link tracking and how privacy badger protects against it. 
* The blocked resources hidden under the ’n potential trackers blocked’ message …
> Organize sliders into expandable summary, add first party protections section

- src/_locales/en_US/messages.json
- src/js/background.js
- src/js/contentscripts/floc.js
- src/js/options.js
- src/js/webrequest.js
- src/manifest.json
- src/skin/options.html
Fixes #2760.
Add a new checkbox to the options page, checked by default, that will disable FLoC from all pages where Privacy Badger is enabled.
Based on the DDG pull request here: https://github.com/duckduckgo/duckduckgo-privacy-extension/pull/591/files
How to test:
1. Run chrome from the command line [with the following flags](https://web.dev/floc/?s=03#as-a-web-developer-how-can-i-try-out-floc) (do NOT install privacy badger yet):
` --enable-blink-features=InterestCohortAPI --enable-features="FederatedLearningOfCohorts:update_interval/10s/minimum_history_domain_size_required/1,FlocIdSortingLshBasedComputation,InterestCohortFeaturePolicy"`
(this will recompute your FLoC every 10 seconds, and will work with a minimum history length of 1 domain)
2. Visit at least one website that serves …
> Add option to disable FLoC

- src/_locales/en_US/messages.json
- src/js/background.js
- src/js/options.js
- src/skin/options.html
- tests/selenium/options_test.py
- tests/selenium/popup_test.py
Removes the acknowledgement overlay that gates the list of domains on the Tracking Domains tab for new users (#1804).
This overlay should no longer be necessary following #2478 (not-yet-blocked domains gated by default-off not-yet-blocked filter) and #2679 (not-yet-blocked filter itself is hidden unless learning is enabled).
In addition, it's not clear how effective this feature is at clearing up confusion in the first place. What is known though is that some users were bothered that there was no way to restore the overlay once dismissed.
> Remove domain list acknowledgement

- src/_locales/en_US/messages.json
- src/js/htmlutils.js
- src/skin/popup.css
Closes #2764 by adding some ARIA label descriptions to the html that's generated for every slider in the popup. 
Tested with VoiceOver screen reader tool on MacOS.
This adds a brief description for the purpose of each slider state (radio button under the hood) and the tracker domain it's associated with.
> Add ARIA labels to popup sliders

- src/_locales/en_US/messages.json
- src/js/background.js
- src/js/options.js
- src/js/popup.js
- src/js/storage.js
- src/js/webrequest.js
- src/lib/i18n.js
- src/skin/popup.css
- src/skin/popup.html
Implements the first part of https://github.com/EFForg/privacybadger/issues/2782#issuecomment-874987177.
Since we reuse #2782 as the "learn more" page, need to add a short and clear summary of what's happening and what you could install instead to the top of that page prior to release.
Deprecation notice:
> Deprecate WebRTC IP leak protection

- src/_locales/en_US/messages.json
- src/js/popup.js
- src/lib/i18n.js
- src/skin/popup.css
- src/skin/popup.html
Related to #2781, #2021. Supersedes #2660.
This makes some more cosmetic changes to the popup to make the disable and enable buttons more prominent.
* adds a colored "power" icon to make it more visually clear what the button does
* simplifies the language on the button by removing "Privacy Badger" from the message (it's obvious that the control is for Privacy Badger)
* changes the disable and enable buttons to be stacked at 100% width with the other two buttons below sharing a single row.
> Make disable on site more prominent

- doc/permissions.md
- src/js/heuristicblocking.js
- src/js/migrations.js
- src/tests/tests/heuristic.js
This cookie is no longer set for any requests proxied via Cloudflare and
thus the configs that were added for it can be removed.
Further context from Cloudflare's blog:
https://blog.cloudflare.com/deprecating-cfduid-cookie/
The last `__cfduid` cookies will expire on June 10th.
> Remove Cloudflare __cfduid cookie configs

- src/js/background.js
- src/js/migrations.js
- src/js/webrequest.js
- src/tests/tests/background.js
This replaces the migration to clean tracker data; older Badgers will get data cleaned on extension update.
Following up on #2377.
> Apply current MDFP data to tracker data on data import and extension updates/installation

- src/js/background.js
This is meant to help Firefox users not lose the welcome page when it gets inadvertently closed when the user chooses to first interact with the post-install Private browsing permission hanger (a reasonable choice) and allows Privacy Badger to run in Private windows.
Related to #2781.
To test:
1. Get Firefox Nightly
2. Toggle `xpinstall.signatures.required` to `false` in `about:config`
3. Create an XPI:  `cd src` and then `zip -r badger.xpi *`
4. Drag and drop the XPI into `about:addons`, switch to the Firefox window, click "Add" in the unverified extension prompt 
5. Check "Allow this extension to run in Private Windows", click "Okay"
If you interact with the welcome page first, finish reading it, and respond to the Private browsing permission hanger in under a minute, we are going to …
> Work around welcome page disappearing post install

- release-utils/make-signed-xpi.sh
- src/data/surrogates.js
- src/data/web_accessible_resources/.eslintrc.yml
- src/data/web_accessible_resources/README.md
- src/data/web_accessible_resources/amazon_apstag.js
- src/data/web_accessible_resources/comscore_beacon.js
- src/data/web_accessible_resources/google_analytics.js
- src/data/web_accessible_resources/google_ga.js
- src/data/web_accessible_resources/googletagservices_gpt.js
- src/data/web_accessible_resources/outbrain.js
- src/data/web_accessible_resources/youneeq.js
- src/js/background.js
- src/js/constants.js
- src/js/surrogates.js
- src/js/webrequest.js
- src/manifest.json
- src/tests/index.html
- src/tests/tests/utils.js
- Adds a surrogate for Amazon Publisher Services Tag as an extension URL, not a data URI string, to work around data URIs getting blocked by website CSPs
- Converts all other surrogates to extension URLs
To be followed up by undoing 9869b706037f17ae1c1527d64a69c4ae6adfcb81 once the update containing this PR gets widely distributed.
To test:
1. Manually block `c.amazon-adsystem.com`
2. Visit one of the affected CNN videos ([example 1](https://www.cnn.com/videos/business/2021/09/14/zero-gravity-flight-inspiration4-mc-jg-sb-scn-orig.cnn-business/video/playlists/stories-worth-watching/), [example 2](https://www.cnn.com/videos/politics/2021/09/13/melania-trump-insurrection-reaction-revealed-former-aide-book-bennett-hunt-newday-vpx.cnn))
3. Verify video works
4. Comment out the surrogate …
> Add Amazon Publisher Services Tag surrogate; switch to extension URL-based surrogates

- src/data/yellowlist.txt
Google's Map Tile servers `mt0.google.com` and `mt1.google.com` are in the yellow list, but sometimes `mt2.google.com` and `mt3.google.com` are also used to server map tiles, and should therefore also be in the yellow list. Example of a failing site: <https://map.treetracker.org/>. Thanks.
> Update yellowlist.txt for additional Google map tile servers

- src/js/firstparties/google-search.js
- tests/selenium/google_test.py
Apparently Google rolled out a new version of search result link tracking for desktop Firefox a couple of days ago. Is this change discussed or documented anywhere?
Keeping the old desktop Firefox link selector because maybe it'll return and maybe it still gets used under some circumstances.
> Fix Google Search link unwrapping in desktop Firefox

- src/js/storage.js
- src/tests/tests/storage.js
Non-tracking domains are always reported as tracking-but-not-yet-blocked. This got broken ever since we recorded the `"undefined"` domain in pre-trained action map (1bd52e5e62e3d4e72c23de09a071545e52317604).
A separate off-by-one bug causes us to always do a lookup for `undefined` when looking up the action to take for a domain. Since we do in fact have an `"undefined"` domain, the lookup always returns true and so we have a floor of whatever action the `"undefined"` domain has; non-tracking domains will never be reported as non-tracking.
This PR fixes the off-by-one bug.
To be followed by finding and fixing where we record tracking by `undefined`. (Start by looking through something like `git lg -G 'in snitch_map:.*undefined' -- log.txt` in Badger Sett.)
> Fix action for non-tracking domains

- doc/permissions.md
- src/_locales/en_US/messages.json
- src/js/background.js
- src/js/migrations.js
- src/js/options.js
- src/js/popup.js
- src/js/webrequest.js
- src/skin/options.html
- src/skin/popup.css
- src/skin/popup.html
Fixes #2782 following the plan in https://github.com/EFForg/privacybadger/issues/2782#issuecomment-874987177.
TODO: test
> Remove WebRTC toggle

- src/js/background.js
- src/js/heuristicblocking.js
- src/js/options.js
- src/js/storage.js
- src/js/webrequest.js
- tests/selenium/cookie_sharing_test.py
- tests/selenium/fingerprinting_test.py
This adds `tracking_map`, a new Badger storage area. It is similar to [`snitch_map`](https://github.com/EFForg/privacybadger/blob/master/doc/DESIGN-AND-ROADMAP.md#data-structures), but instead of tracker base domains pointing to arrays of site base domains, tracker base domains point to objects keyed by site base domains with arrays of detected tracking types for values. For example:
```json
"arkoselabs.com": {
"cheaptickets.com": [
"canvas"
],
"expedia.ca": [
"canvas"
],
"expedia.co.uk": [
"canvas"
]
},
```
For now, just two tracking types are being tracked: `"canvas"` (fingerprinting) and `"pixelcookieshare"`.
Here is a recent 20K site Chrome run: [results.zip](https://github.com/EFForg/privacybadger/files/8557896/results.zip). Let's compare this/bigger scans to [Disconnect's …
> Store some additional tracker data in tracking_map

- src/data/socialwidgets.json
- src/data/surrogates.js
- src/data/web_accessible_resources/youtube.js
- src/js/contentscripts/socialwidgets.js
- src/js/webrequest.js
Fixes #2849. Follows up on #2805 and #2280.
To be followed up with another round of reviewing error reports and fixing the major remaining issues so that we can remove YouTube from the yellowlist (#1593). Should also look into handling `youtube-nocookie.com`.
Working YT JS API examples:
- https://www.aljazeera.com/program/talk-to-al-jazeera/2022/9/16/iran-raisi-no-benefit-in-direct-nuclear-negotiations-with-us
- https://www.huffpost.com/entry/trevor-noah-scheme-voter-suppression_n_5bc99e6fe4b0d38b5876e1c6
- https://www.milieucentraal.nl/minder-afval/afval-scheiden/tips-voor-een-schone-gft-bak/ (scroll to bottom, video uses a custom play/pause control that calls `YT.Player` API methods)
- https://theprovince.com/category/hot-topics/ ("LATEST VIDEOS" on the right)
- …
> Add surrogate-based replacement for YouTube JS API

- src/js/webrequest.js
- tests/selenium/service_workers_test.py
Fixes #2706, fixes #2737 as it appears that `chrome.webNavigation.onCommitted`, unlike `onBeforeNavigate`, does get triggered on service worker-initiated navigation.
Follows up on #2454. We went with `onBeforeNavigate` rather than `onCommitted` there because
>Listening to webNavigation.onBeforeNavigate() events instead of onCommitted() fixes [the "you are offline" scenario]
However, I am now unable to reproduce "you are offline" in Firefox, even when I remove our `chrome.webNavigation` listener entirely.
There should be no change in behavior in Firefox.
> Fix detection of service worker-initiated navigation in Chrome

- src/_locales/en_US/messages.json
- src/js/popup.js
- src/skin/options-layout.css
- src/skin/popup.css
Related to #2750 and #2804
This adds a line into the block of error text that users get in the popup, and creates another link to direct users to the FAQ entry on the website where we describe how to fix the common memory error they see and otherwise get an unhelpful "UNEXPECTED ERROR OCCURRED" message.
Hopefully we can remove this and the other related minor fixes in the future when this is no longer an issue for Firefox users with low disk space.
> Create a special error message for Firefox users

- src/_locales/en_US/messages.json
- src/js/background.js
- src/js/htmlutils.js
- src/js/popup.js
- src/js/webrequest.js
- src/skin/popup.css
Should help with #137.
The tooltip is shown once, when you first open the popup for a page where Privacy Badger (cookie)blocked `accounts.google.com` by default.
The sliders section will then be open, same as when there are any breakage warnings. The slider for `accounts.google.com` will get shown at the top, before any other sliders. Same as breakage warning sliders, but above them too.
The tooltip stays open while you click (or tap) to move the slider.
You can dismiss the tooltip by clicking on it. There is currently no way to show it again.
We don't do any of this for sliders on the options page.
This could be followed up by adding other breakage notes, perhaps for Twitch (#2540 / #2785).
> Show Google Sign-In "breakage note" tooltip for accounts.google.com

- src/_locales/en_US/messages.json
- src/js/htmlutils.js
- src/js/options.js
- src/js/popup.js
- src/js/webrequest.js
- src/skin/options-layout.css
- src/skin/options.html
- src/skin/popup.html
- src/tests/tests/htmlutils.js
- tests/selenium/options_test.py
Fixes #1289.
This follows up on #2839 by querying `tracking_map` for canvas fingerprinting.
This also follows up on #2664 by restoring fancy tooltips for the list of tracking domains on the options page.
> Add tooltips that show where a domain was seen tracking to the list of domains in options

- src/js/background.js
This changes [static asset update](https://privacybadger.org/#Why-does-my-browser-connect-to-fastly.com-IP-addresses-on-startup-after-installing-Privacy-Badger) behavior on extension startup. Instead of happening on every startup, an asset update will take place only if enough time elapsed since last update.
The very first startup following extension installation is a special case where asset updates will happen just as they do now.
When the extension stays continuously active, asset update behavior should also remain the same as now.
Part of #2579.
> Conditional static asset updating

- src/data/yellowlist.txt
m.stripe.com, q.stripe.com, and r.stripe.com are tracking domains in their entirety, according to uBlock Origin. The only breaking domain is js.stripe.com.
> stripe.com -> js.stripe.com in yellowlist

- src/data/yellowlist.txt
Blocked on publictestwiki.com as a tracker for some reason.
> Add meta.miraheze.org to the yellowlist

- src/js/background.js
- src/js/migrations.js
- src/js/storage.js
- src/tests/tests/yellowlist.js
Follows up on #2438.
Replaces #2604. Unlike that PR this does not add handling for async migrations; that can come later, as needed.
> Clean up migrations

- src/_locales/en_US/messages.json
- src/js/background.js
- src/js/options.js
- src/js/webrequest.js
- src/skin/options.html
By opting out the user from topics generation on all websites.
Related:
- https://github.com/w3ctag/design-reviews/issues/726#issuecomment-1379908459
- https://techcrunch.com/2023/01/17/privacy-sandbox-topics-api-criticism/
Testing: https://developer.chrome.com/docs/privacy-sandbox/topics/#view-topics-api-information
Follows up on #2762 and ac332574b43b401f7a3c6b7d56a0beb65927d51b.
> Disable Google's Topics API by default

- src/data/yellowlist.txt
Discord users often (ab)use the CDN for free image hosting on various websites, and both Discord CDNs are currently detected by my Privacy Badger and blocked due to the number of cookies used by Discord, so I'm adding this here to fix the breakage of various images.
> Add Discord CDNs to the yellowlist

- src/js/webrequest.js
- src/tests/tests/background.js
Fixes a part of #1793.
Although this blocks all `source-file: "moz-extension"` CSP reports, we still have the issue of some of our scripts being blocked by page CSPs in Firefox.
Note that script surrogates are no longer subject to page CSPs (#2801).
DDG's test page: https://privacy-test-pages.glitch.me/security/csp-report/index.html
Anything [injected into page-level contexts](https://github.com/EFForg/privacybadger/blob/463894198affe6d136a1c14c1e16429442efeaa8/src/js/contentscripts/utils.js#L29-L44) ("main world"). So, `navigator.doNotTrack`, canvas fp. detection, `document.cookie`/localStorage blocking, ...
>if your extension injects a (dynamically generated or static) inline script
&mdash; https://bugzilla.mozilla.org/show_bug.cgi?id=1588957#c13
Yes, inject page scripts from …
> Block moz-extension CSP reports

- src/js/heuristicblocking.js
- src/js/webrequest.js
- src/lib/webrequestUtils.js
- tests/selenium/navigation_test.py
Fixes #1997 (partial fix in Chrome where we're unable to correct out-of-order [requests from nested frames](https://crbug.com/838242#c17)).
Fixes #2692.
Fixes #2198.
Related to https://github.com/EFForg/privacybadger/compare/master...fix-sw-monitoring-chrome. ~~We don't yet handle requests from just-closed tabs (2be5ed12e80a02540fdd9a3329f368dc6191b8e2~~, nor have we consolidated webRequest listeners (1059d34f7894db301acf146b58e3ce11c36ed07f).
Should help with #2234.
Follows up on #2860.
To be followed by #2024.
> Fix navigation-related request attribution

- doc/DESIGN-AND-ROADMAP.md
- src/js/heuristicblocking.js
- src/js/storage.js
- src/js/webrequest.js
- tests/selenium/navigation_test.py
New heuristic: all third-party uses of the [Beacon API](https://developer.mozilla.org/en-US/docs/Web/API/Beacon_API) are counted as tracking.
Fixes #2024.
This may let us entirely drop pixel cookie sharing detection.
> Record third-party beacons as tracking

- src/data/yellowlist.txt
Hi!
Stonly's domain (stonly.com) is currently blocked by Privacy Badger.
Stonly helps companies provide personalised guidance to their customers, in the form of guided tours, banners, knowledge bases.
A few example websites where the experience is broken with Privacy Badger:
- [French Post Office help center](https://aide.lidentitenumerique.laposte.fr/kb/fr/) (images are not loading)
- [Online Boat Store Jeanneau](https://www.jeanneau.com/) (the pill at the bottom right is not loading)
- [Canadian Telecom company Telus email setup guide](https://www.telus.com/en/support/article/set-up-email-on-devices) (the embedded guide is not loading)
> Add stonly.com to yellowlist

- src/js/heuristicblocking.js
- src/js/tabdata.js
- src/js/webrequest.js
- src/lib/basedomain.js
Important state consists of tab and activated widget data.
No-op for now; meant for event pages (Firefox with background.persistent set to `false` in the manifest), or Manifest V3.
Part of https://github.com/EFForg/privacybadger/pull/2579.
> Persist important state in session storage

- doc/permissions.md
- src/js/background.js
- src/manifest.json
- src/skin/js/firstRun.js
Part of #2579.
Follows up on #2798.
Confirmed that adding the `"alarms"` permission does not disable the extension on update pending new permission approval in Chrome using https://github.com/GoogleChromeLabs/extension-update-testing-tool.
> Avoid unnecessarily reopening the welcome page because of idle background process termination

- src/js/options.js
- src/js/popup.js
- src/js/webrequest.js
Part of #2579.
Follows up on #2883 by expanding the fix to all messages handled by `dispatcher()` (rather than only `"getPopupData"` and `"getOptionsData"`).
> Handle messages received before (event page or service worker) background is ready

- src/js/surrogates.js
- src/tests/tests/utils.js
For example, `https://securepubads.g.doubleclick.net/tag/js/gpt.js#?v=...` on https://www.cbsnews.com/philadelphia/live/.
> Fix suffix surrogate lookups for script URLs that contain a hash component

- src/data/yellowlist.txt
- src/js/multiDomainFirstParties.js
This is the domain used by some Shopify to host services to provide features like address autocomplete, validation, etc.
After reading https://github.com/EFForg/privacybadger/blob/master/doc/yellowlist-criteria.md, I think that we should also add to https://github.com/EFForg/privacybadger/blob/master/src/data/yellowlist.txt#L587-L589 together with the other domains, given that this domain is crucial for the features.
Related https://github.com/EFForg/privacybadger/pull/2533
> Add Shopify's missing domain

- src/data/socialwidgets.json
- src/data/surrogates.js
- src/data/web_accessible_resources/twitter.js
- src/js/webrequest.js
Following up on #2805 and 4cf05333257536ae0fb93ba7cd1799cc23b02b0c.
https://developer.twitter.com/en/docs/twitter-for-websites/javascript-api/overview
- https://www.theverge.com/2020/9/11/21433228/microsoft-xbox-series-x-hidden-video-phil-spencer-july-2020
- https://en.defence-ua.com/news/become_known_that_ukrainian_military_has_to_master_american_patriot_ads_in_a_record_time-5471.html
- https://www.srf.ch/news/international/krieg-in-der-ukraine-stoltenberg-fordert-bei-nato-treffen-standhaftigkeit
- https://www.thedrive.com/the-war-zone/ukraine-situation-report-new-ground-based-air-defense-coalition-announced
- https://www.comicsands.com/semicircle-corners-divides-irish-parents-2666363460.html
- https://www.dw.com/en/brazil-bolsonaro-supporters-storm-national-congress/a-64320440?protocol-f …
> Upgrade Tweet replacement with surrogate JS API

- doc/permissions.md
- src/js/heuristicblocking.js
- src/js/webrequest.js
- src/manifest.json
This updates the manifest to use `"<all_urls>"` instead of wildcard http(s).
This should be a no-op for now, as this updates all `"<all_urls>"` listeners to use wildcard http(s) instead.
To be followed by updating appropriate listeners to also process wildcard ws(s) requests, or perhaps to use `"<all_urls>"` instead. We may also want to add WebSockets request tests. This will resolve PR #2415 and issue #1010.
> Switch to the "<all_urls>" permission in the manifest

- src/js/webrequest.js
Following up on #2927.
Fixes #1010, fixes #2137. Closes #2415.
> Block WebSocket connections to blocked domains

- src/js/background.js
- src/js/bootstrap.js
- src/js/heuristicblocking.js
- src/js/storage.js
This prepends `log()` output with total time elapsed since the first `log()` call as well as with time elapsed since the previous `log()` call, to help with debugging and general development.
Unfortunately, it seems that we can have correct caller line numbers[*], or we can decorate output with arbitrary logic at run time, but we can't have both.
[*] using [`.bind()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Function/bind); something like:
```javascript
let log = (function () {
return Function.prototype.bind.call(console.log, console);
}());
```
> Add timing info to log() output

- src/data/yellowlist.txt
This is a Discord CDN that some websites will embed for free file storage
Example: https://images-ext-1.discordapp.net/external/2pFyjiHFbEIogQ1qJYy1F2vuIHIlDdZsbzFCn7xGQHU/https/share.redd.it/preview/comment/h0ix4xs, https://images-ext-2.discordapp.net/external/2pFyjiHFbEIogQ1qJYy1F2vuIHIlDdZsbzFCn7xGQHU/https/share.redd.it/preview/comment/h0ix4xs
It's gotten blocked my Privacy Badger, probably because of cookies:
> Add images-ext-1.discordapp.net and images-ext-2.discordapp.net

- src/_locales/en_US/messages.json
- src/js/background.js
- src/js/constants.js
- src/js/options.js
- src/js/webrequest.js
- src/lib/options.js
- src/skin/options.html
- src/tests/tests/options.js
Fixes #2929.
Hiding domains found in the latest seed data is not the same as only showing locally learned domains, but it might be close enough.
The new filter becomes visible after enabling local learning.
> Add tracking domains filter that hides (most recent) remotely learned domains

- src/js/popup.js
- src/lib/i18n.js
- src/skin/popup.css
- src/skin/popup.html
The "Privacy Badger" title text now supports splitting to two lines.
This also improves keyboard tabbing order, removes a few i18n hacks, and makes room for us to widen the spacing between the Help/Share/Options corner buttons if we wish to do so later.
Before:
After:
> Improve popup header display on small screens

- src/js/background.js
- src/js/storage.js
- src/tests/lib/qunit_config.js
We currently load seed data from disk only on extension installation and updates. (Yellowlist and EFF's DNT policy hash list only get loaded from disk when they are empty in memory.)
This fixes #2930 by loading seed (and yellowlist and EFF's DNT policy hash list) data from disk on startup whenever its "successfully loaded" flag isn't set. If seed loading gets interrupted by an extension reload (or crash), the flag won't get set, and Privacy Badger will reattempt to load the seed on startup.
Existing installations will reload seed / yellowlist / EFF's DNT policy hash list assets from disk upon first updating to the new version that contains this patch. This will fix any broken installations.
> Retry loading local assets when their "successfully loaded" flag isn't set

- src/_locales/en_US/messages.json
- src/js/popup.js
- src/js/storage.js
- src/skin/popup.css
"An unexpected error occurred" storage errors in Firefox [may or may not have to do with low disk space](https://bugzilla.mozilla.org/show_bug.cgi?id=1555491#c18), but surfacing them to the user seems to do more harm than good at this point.
This removes the special message added in #2835, and ignores "An unexpected error occurred" storage writing errors (no action other than logging the error to the background page developer console).
Should be followed up by updating [the FAQ](https://github.com/EFForg/privacybadger-website/blob/master/content/en/faqs/I-found-a-bug!-What-do-I-do-now.md).
> Ignore "unexpected error" storage errors

- src/skin/popup.html
Stops space before "Donate to EFF" from being underlined. Fixes #2960 
Before:
After:
> Update popup.html to correctly underline the "Donate to EFF" link

- src/js/background.js
- src/js/webrequest.js
The infinite loop happens when initialization gets interrupted such as by unhandled JavaScript errors. While Privacy Badger will still be broken when this happens, it should not max out the CPU.
Follows up on #2909.
Fixes part of #2954.
> Remove infinite loop

- src/js/storage.js
Fixes (potentially) #2966, fixes #2954.
Follows up on #2955.
Now when Privacy Badger fails to read from storage, it will still function but with all settings reset to defaults, with the exception of the new user welcome page (and its in-popup reminder), which we specifically disable. It will be just as if the user installed Privacy Badger for the first time, only without the welcome page.
This should be an improvement over Privacy Badger failing to initialize and not doing anything useful while annoying the user with a bright red exclamation badge over its icon.
Unfortunately, we still don't know what causes Privacy Badger to fail to read from storage.
> Handle storage.local.read() returning undefined

- src/js/background.js
Following up on #2967. Fixes another part of #2966. This PR is this bit:
>We are going to follow this up with a fix for (1) where we deactivate the "failed to initialize" error when PB does in fact finish initializing successfully.
> Unset "failed to initialize" error upon successful initialization

- src/data/yellowlist.txt
- src/js/multiDomainFirstParties.js
Fixes #2976
Used Wireshark to identify `speech.platform.bing.com` as the requested resource.
Was able to verify that yellow listing bing.com resolved the issue with Edge's _Read along_ feature.
Reviewed https://github.com/EFForg/privacybadger/blob/master/doc/yellowlist-criteria.md before submitting.
> Adds Bing Speech Platform domain to Yellow List to resolve issue with Edge Read aloud feature

- src/js/background.js
- src/js/storage.js
When `chrome.storage.local.get()` fails to return an object [^1], and also when `chrome.storage.local` is `undefined` [^2].
Follows up on #2967 and https://github.com/EFForg/privacybadger/issues/2966#issuecomment-2153316523
Might fix issues like #2979.
[^1]: Fails to return something [truthy](https://developer.mozilla.org/en-US/docs/Glossary/Truthy), to be exact
[^2]: When calling `chrome.storage.local.get()` throws an exception, to be exact
> Retry reading from extension storage on startup

- doc/permissions.md
- src/_locales/en_US/messages.json
- src/js/background.js
- src/skin/options.html
- Switched the "Disable Google's Topics API" toggle on the options page to "Disable Google's 'Privacy Sandbox' Ad Tracking"
- To test, run `make runch`, visit chrome://settings/adPrivacy, and confirm that you the extension icon on the pages of all three features
- Visit the Options page and confirm that this toggle's link and text are correct
Follows up on d6e93e2c5787501041cc0b51cdb164de936a277a and #2888.
> Disable 'Privacy Sandbox' ad tracking by default

- src/_locales/en_US/messages.json
- src/js/popup.js
- src/skin/popup.css
- src/skin/popup.html
Following up on #2974, and in response to continuing error reports for non-Privacy related issues on YouTube, I copied the YouTube-specific message on the popup onto the error reporting form. I also edited to the message to explicit reference ads, since many of the continued error reports have to do with ads playing on YouTube.
Once the new text is approved, I'll re-run `make tx` to update the locale files
> Add YouTube-specific message to the error report page

- src/js/popup.js
- src/lib/i18n.js
- src/skin/popup.css
- src/skin/popup.html
- tests/selenium/popup_test.py
For testing, check the share overlay and the error report overlay. Add more text to the title until text wraps onto two lines.
> Fix close button misalignment in error report overlay

- src/data/socialwidgets.json
Fixes #2540, closes #2785.
If this works, we'll be able to remove the following text and image from https://livestream.eff.org/:
>Using EFF's Privacy Badger? If you'd like to log in to Twitch chat, give it your permission by shifting the "embed.twitch.tv" slider and reload the page.
In order for replacement to happen, we need to remove `twitch.tv` from the yellowlist, so that we can block `embed.twitch.tv`. This means we release this patch, wait for most clients to update, remove `twitch.tv`, and then see if we need to restore some subdomains of Twitch, or, if our replacements don't work well enough, restore all of `twitch.tv`.
> Add widget replacement for more Twitch embeds

- src/data/socialwidgets.json
- src/js/contentscripts/socialwidgets.js
- src/js/contentscripts/utils.js
- src/js/webrequest.js
Fixes #2989. Follows up on #2852.
Also fixes replacing Embedly frame loaded (nested) surrogate JS API-powered widgets:
- https://www.mediapart.fr/journal/france/290321/affaire-myriam-sakhri-la-famille-espere-une-reouverture-de-l-enquete (YouTube)
- https://medium.com/@samuelwestwood/time-saving-things-that-actually-work-trust-me-28461a6f4a41
Lazy loaded example that still doesn't work:
- https://kotaku.com/peach-is-a-monster-in-smash-ultimate-pros-say-1831613178
Surrogate JS API-powered example that no longer works (unrelated to this PR; a "loading" overlay hides our placeholder):
- https://www.aljazeera.com/program/talk-to-al-jazeera/2022/9/16/iran-raisi-no-benefit-in-direct-nuclear-negotiations-with-us
> Fix replacing some lazy-loaded widgets

- src/js/multiDomainFirstParties.js
There's a long complicated story here - WikiTide forked from Miraheze following a hairy internal dispute and then they later merged together again. Anyway, right now the domains `wikitide.net` and `miraheze.org` are controlled by the same entity.
Privacy Badger says: 
```
wikitide.net was seen tracking on the following sites:
miraheze.org
orain.org
sekaipedia.org
```
All of these domains are also technically first-parties controlled by Miraheze/Wikitide but since they let users add their own custom domains there's no point in listing every single one. I'm listing these two because my badger learned to block wikitide.net (I have local learning enabled) and it caused https://issue-tracker.miraheze.org/ to fail to load properly.
> Add Miraheze/Wikitide to MDFP

- src/data/socialwidgets.json
- src/js/contentscripts/socialwidgets.js
Examples:
- https://www.theverge.com/2024/7/31/24210511/bluecruisn-over-the-atlantic
- https://www.macrumors.com/2024/07/25/threads-app-gets-tweetdeck-dedicated-feeds/
- https://boingboing.net/2024/01/16/the-perfect-answer-to-god-made-trump-video-is-god-made-a-dictator.html
- https://fandomwire.com/i-was-paid-for-the-script-and-finished-it-unlike-zack-snyder-james-gunn-doesnt-regret-being-kicked-out-as-director-from-his-own-passion-project-14-years-ago/ (inline activation doesn't seem to work but maybe not PB's fault?)
> Add widget replacement placeholder for Threads

- src/data/schema.json
- src/js/options.js
- src/skin/options.html
- tests/selenium/widgets_test.py
The first part of #3007. We could make the deprecation more visible by doing something like #2783, but it doesn't feel like we need to in this case.
> Hide widget replacement toggle

- src/_locales/en_US/messages.json
- src/skin/options.html
Too much text means users tend not to read any of it, and we don't need to explain how basic forms work.
Also, "Add domain" is now "Add site".
The new, single-paragraph intro:
> Simplify intro text on the Disabled Sites tab

- src/js/contentscripts/socialwidgets.js
> Fix icon overlap on RTL widget placeholders

- src/data/socialwidgets.json
- src/js/contentscripts/socialwidgets.js
Seen on theverge.com, techdirt.com ([example](https://www.techdirt.com/2024/10/29/some-slightly-biased-thoughts-on-the-state-of-decentralized-social-media/)), beeradvocate.com
More examples:
- https://bsky.social/about/blog/post-embeds-guide
- toothpastefordinner.com
- bancodeseries.com.br
> Add widget replacement placeholder for Bluesky

- src/data/socialwidgets.json
- src/js/contentscripts/socialwidgets.js
Seen on theverge.com and toothpastefordinner.com
>[!NOTE]
>`instagram.com` is [currently on the yellowlist](https://github.com/EFForg/privacybadger/blob/8dba49fdf26c31a58afd094422b175ccf06ed234/src/data/pbconfig.json#L396), which means we have to manually move the toggle to "block" first for the widget replacement to work.
More examples:
- https://time.com/7020451/taylor-swift-kamala-harris-donald-trump-ai/
- https://deadline.com/2024/09/taylor-swift-endorses-kamala-harris-1236084389/
- https://www.euronews.com/green/2024/01/03/sweden-portugal-luxembourg-which-eu-countries-use-the-most-and-least-renewable-energy
- https://stylebyemilyhenderson.com/blog/5-color-palettes-to-freshen-up-a-tired-honey-oak-kitchen
- https://montreal.eater.com/maps/best-brunch-restaurants-montreal
- …
> Add widget replacement placeholder for Instagram

- src/js/background.js
- src/js/contentscripts/clobbercookie.js
- src/js/contentscripts/clobberlocalstorage.js
- src/js/contentscripts/supercookie.js
- src/js/heuristicblocking.js
- src/js/options.js
- src/js/popup.js
- src/js/storage.js
- src/js/webrequest.js
- src/tests/tests/htmlutils.js
- src/tests/tests/storage.js
- src/tests/tests/tabData.js
- src/tests/tests/utils.js
- tests/selenium/content_filtering_test.py
- tests/selenium/options_test.py
- tests/selenium/pbtest.py
Follows up on #2467 and 94adce8862cb5a3a3b0dc462c16d22e8431a3ed7 / 1518d01a66deb04b5dc27323fc8d73e78bc8b8a5.
There should be no functional difference in browsers that haven't implemented [`MessageSender.origin`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/MessageSender#origin).
Up-to-date browsers get an improved version of #2467. Also, we may learn to block more trackers as we will no longer sometimes fail to determine the originating frame URL of content script messages (1518d01a66deb04b5dc27323fc8d73e78bc8b8a5).
Regarding the mass renaming commits:
- https://web.dev/articles/same-site-same-origin
- not fully done, leaving more for later
> Prefer sender.origin for determining message sender's frame host

- src/js/webrequest.js
For clarity/explicitness, and to avoid URL parsing errors.
Follows up on #3039.
> Check when message sender is about:blank/"null"

- doc/sample-admin-policies/jid1-MnnxcxisBPnSXQ@jetpack.json
- doc/sample-admin-policies/sample-managed-storage-manifest-chrome.json
- src/data/schema.json
- src/js/storage.js
Fixes #3051. Should "just work" in MV3, but I need to test it.
Also fixes #2259, just not in the UI.
> Add ability to specify tracking domain actions in managed storage

- src/data/pbconfig.json
Blocking api.reddit.com breaks websites that use the Reddit API, e.g. https://redditmetis.com/user/spez
> Add api.reddit.com

- src/js/options.js
- tests/selenium/options_test.py
Can be restored for now by adding "all" to the options page query string.
Previously: #2768, #1603
Follows up on #2679.
> Remove "Show not-yet-blocked domains" filter from UI

- src/js/popup.js
If the user had not yet engaged with the welcome page but hadn't closed it either, showing the reminder just gets in the way of seeing Privacy Badger's popup.
> Don't show the welcome page reminder when the welcome page is still open

- src/js/background.js
- src/js/heuristicblocking.js
- src/js/incognito.js
- src/js/tabdata.js
Fixes #3036. Follows up on #3059.
It seems that `chrome.tabs.query()` can be really slow too.
The big idea behind these fixes is that if the mass tab query is slow for whatever reason, rather than fail completely, let's handle whatever specific issues arise from not having tab data.
It should be OK to not wait on:
- Tab incognito statuses because we play it safe and assume incognito when this data is missing. Potentially missing some local learning on browser startup when restoring tabs seems acceptable. Plus we already technically didn't wait on this, although this lookup ran basically before everything else.
- Updating tab icons because we already didn't wait on this.
- Tab URLs/base domains for learning from cookies because we already didn't wait on this.
- tabData's tab data because …
> Refactor mass tab lookups on startup

- src/js/options.js
- src/skin/options-layout.css
- src/skin/options.html
- Fixes #3086
- Hide the "how to disable" tip on the Options page for Android because the image doesn't show the correct steps for Firefox for Android. 
- The tip box is unnecessary because the extensions UI on Firefox for Android makes it harder to find the options page than the popup.
- I also fixed a visual bug with the tip box image being too wide on extremely narrow screens
- Confirmed the change on an Android Emulator:
> Hide "Disable" tip box on Options page on Firefox for Android

- src/_locales/en_US/messages.json
- src/skin/options.html
- src/skin/popup.html
The space between the first placeholder and the text is for Safari.
> Update old-style FAQ links

- src/_locales/en_US/messages.json
Add info on who makes Privacy Badger and what blocking trackers is for.
Related:
- https://privacybadger.org/#How-is-Privacy-Badger-different-from-Disconnect%2c-Adblock-Plus%2c-Ghostery%2c-and-other-blocking-extensions
- https://github.com/EFForg/privacybadger-website/issues/157
- https://github.com/EFForg/privacybadger/issues/1675#issuecomment-417058938
> Update extension description

- doc/fixing-broken-sites.md
- src/data/pbconfig.json
- src/js/background.js
- src/js/constants.js
- src/js/webrequest.js
- src/tests/tests/yellowlist.js
Fixes #3109
Related to #2395
This needs a followup MV3 PR where we regenerate site-specific domain override rules in response to `sitefixes` storage changes.
> Add site-specific domain overrides to pbconfig

- tests/selenium/popup_test.py
Should fix sporadic failures in Edge.
> Replace hardcoded wait with polling in popup tests

- src/js/tabdata.js
- src/js/webrequest.js
Fixes #3116.
With MV2 the background process should only start once, on browser startup. If tab data fails to initialize in MV2 under X (5?) seconds for whatever reason, do we want to show a "failed to initialize" error in response to opening the popup, or do we want to ignore it? We may want to ignore it. To be clear, 15 secs of `!badger.INITIALIZED` should produce "failed to initialize" but X secs of `!badger.tabData.INITIALIZED` probably shouldn't.
> Wait for tabData initialization when opening popup

- src/js/popup.js
- src/skin/popup.css
- src/skin/popup.html
Fixes https://github.com/EFForg/privacybadger/issues/3105
- Prevent keyboard navigation through hidden elements while preserving overlay transition effect
- I used `visibility: hidden` instead of `display: none` to preserve the transition
- Follow ARIA guidelines for focus after opening and closing a modal/dialogue
- NOTE: I don't think ARIA guidelines about "Esc" key being used to exit a modal/dialogue can be followed because "Esc" already closes extension popups. I don't think we should interfere with this behavior?
- Tested on Firefox and Chrome with VoiceOver screenreader navigation and tab navigation 
- Known issue: Tab navigation doesn't loop on the overlay on Firefox. It does on Chrome. I could address this by trapping focus manually …
> Fix keyboard navigation going through hidden elements in popup

- src/skin/popup.css
- src/skin/popup.html
Fixes #3139
The `role="dialog"` and `aria-modal="true"` are for marking the nudge/critical error/important update notification overlay as what it is, a modal. It doesn't actually prevent keyboard nav from going out of bounds, that's still an issue.
> Add focus indicator to CTA buttons/links in popup
